### ISSUE TITLE
DefaultHttpContext > Features > Throws Exception

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#1004]
Using Beta8 (or 7) I created a new empty project form the template and set a breakpoint where it prints "Hello World".

In the debugger, if I examine the "context" variable, Drill down into "Features", and then click "Results View" I get the following exception:

```
Message: The method or operation is not implemented.
Source: Microsoft.AspNet.Http.Features
Stacktrace: 
   at Microsoft.AspNet.Http.Features.FeatureCollection.KeyComparer.GetHashCode(KeyValuePair`2 obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<ExceptIterator>d__1`1.MoveNext()
   at Microsoft.AspNet.Http.Features.FeatureCollection.<GetEnumerator>d__14.MoveNext()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

```

I noticed that I can still "Get" and "Set" features so I'm not sure how serious this issue is, but as i'm working with "Features" for the first time, I'd like to make sure it's not breaking other things.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#445
