### ISSUE TITLE
Test tools need a corefx version bump

### ISSUE THREAD

**Issue by benaadams** [aspnet/Home#1021]
AppVeyor and Travis occasionally report an unrelated error

> Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Threading.Thread' to type 'System.Net.Http.WinHttpRequestState'.
   at System.Net.Http.WinHttpRequestState.FromIntPtr(IntPtr gcHandle)
   at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) 
fail: Exit code -532462766 from cmd
fail: Stack trace: 
   at View12e46788b72f4736b249ab6593dec757.Dnx(String command, String dnxDir, String dnvmUse) in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 1874
   at View12e46788b72f4736b249ab6593dec757.DnxTest(String projectFile, Boolean testParallel) in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 2369
   at View12e46788b72f4736b249ab6593dec757.<RenderViewLevel0>b__ed(String projectFile) in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 12015
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at View12e46788b72f4736b249ab6593dec757.<RenderViewLevel0>b__eb() in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 12015
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View12e46788b72f4736b249ab6593dec757.StartingTarget(String name) in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 3732
   at View12e46788b72f4736b249ab6593dec757.<RenderViewLevel0>b__8b() in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 4363
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View12e46788b72f4736b249ab6593dec757.StartingTarget(String name) in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 3732
   at View12e46788b72f4736b249ab6593dec757.<RenderViewLevel0>b__91() in c:\Users\appveyor\AppData\Local\Temp\1\81d2761eaf61430280513a6d748d9e6d-1.cs:line 4468
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

This has now been resolved in corefx https://github.com/dotnet/corefx/pull/4001

/cc @davidfowl

**Comment by muratg** [comment]
We'll be consuming the CoreFX build with the fixes soon and it should resolve this issue.

**Comment by benaadams** [comment]
This seems resolved now
