### ISSUE TITLE
ASP .Net 5 Beta 8 References Not Resolving VS 2015 

### ISSUE THREAD

**Issue by taylorc** [aspnet/Home#1055]
After creating an ASP .Net 5 Web Application the References will not resolve. 

Environment
Visual Studio 2015 Community Edition
NuGet 3.2.60914.10516
Resharper 9.2
IIS Express (VS 2015 Community Edition)
Windows 10

Steps to replicate
1. File --> New--> Project
2. Choose ASP.NET Web Application
3. Choose ASP.NET 5 Preview Templates Web Applicaiton (with Individual User Accounts for Authentication

The following is the text from the output window from the package restore:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\XXXXX\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe "C:\Users\XXXXX\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "F:\Working\Git\misc\SuperSecretWebApp\SuperSecretWebApp.Web" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/
  CACHE https://nuget.org/api/v2/
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/
Restoring packages for F:\Working\Git\misc\SuperSecretWebApp\SuperSecretWebApp.Web\project.json
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Collections'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Collections'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Collections'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Claims'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Security.Claims'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Claims'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Principal'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Security.Principal'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Principal'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Linq'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Linq'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Linq'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.ComponentModel'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.ComponentModel'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.ComponentModel'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.RegularExpressions'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Text.RegularExpressions'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.RegularExpressions'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Collections.Concurrent'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Collections.Concurrent'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Collections.Concurrent'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.IO.FileSystem'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.IO.FileSystem'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Diagnostics.Tools'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Tools'
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Diagnostics.Tools'
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Runtime' 2641ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Claims' 2358ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Principal' 2515ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Claims' 2547ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Security.Principal' 2680ms
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Linq.Expressions'
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.ComponentModel' 2734ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Collections' 3113ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.Encoding' 3031ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Text.Encoding' 3202ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.ComponentModel' 3026ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Linq.Expressions'
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Collections' 3235ms
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Linq.Expressions'
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Runtime' 3601ms
----------
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.UnzippedPackage.EnsureManifest()
   at NuGet.UnzippedPackage..ctor(IFileSystem fileSystem, String manifestPath)
   at NuGet.PackageInfo.get_Package()
   at Microsoft.Dnx.Runtime.NuGetDependencyResolver.<GetDependencies>d__4.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
NuGet Config files used:
    C:\Users\XXXXX\AppData\Roaming\NuGet\nuget.config
Feeds used:
    https://www.myget.org/F/aspnetmaster/api/v2/
    https://nuget.org/api/v2/
    C:\Program Files (x86)\Microsoft Web Tools\DNU
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\XXXXX\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe "C:\Users\XXXXX\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "F:\Working\Git\misc\GiraffeTracker\WebApplication1" -s "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858
Restoring packages for F:\Working\Git\misc\GiraffeTracker\WebApplication1\project.json
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Commands\7.0.0-beta8\EntityFramework.Commands.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Relational\7.0.0-beta8\EntityFramework.Relational.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Core\7.0.0-beta8\EntityFramework.Core.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Ix-Async\1.2.5\Ix-Async.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Remotion.Linq\2.0.0-beta-002\Remotion.Linq.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Relational.Design\7.0.0-beta8\EntityFramework.Relational.Design.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Compilation.CSharp\1.0.0-beta8\Microsoft.Dnx.Compilation.CSharp.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Compilation\1.0.0-beta8\Microsoft.Dnx.Compilation.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Runtime\1.0.0-beta8\Microsoft.Dnx.Runtime.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Loader\1.0.0-beta8\Microsoft.Dnx.Loader.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Newtonsoft.Json\6.0.6\Newtonsoft.Json.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.SqlServer\7.0.0-beta8\EntityFramework.SqlServer.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Cookies\1.0.0-beta8\Microsoft.AspNet.Authentication.Cookies.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication\1.0.0-beta8\Microsoft.AspNet.Authentication.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Facebook\1.0.0-beta8\Microsoft.AspNet.Authentication.Facebook.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.OAuth\1.0.0-beta8\Microsoft.AspNet.Authentication.OAuth.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Google\1.0.0-beta8\Microsoft.AspNet.Authentication.Google.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.MicrosoftAccount\1.0.0-beta8\Microsoft.AspNet.Authentication.MicrosoftAccount.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Twitter\1.0.0-beta8\Microsoft.AspNet.Authentication.Twitter.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Diagnostics.Entity\7.0.0-beta8\Microsoft.AspNet.Diagnostics.Entity.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Identity.EntityFramework\3.0.0-beta8\Microsoft.AspNet.Identity.EntityFramework.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Identity\3.0.0-beta8\Microsoft.AspNet.Identity.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Cryptography.KeyDerivation\1.0.0-beta8\Microsoft.AspNet.Cryptography.KeyDerivation.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Commands\7.0.0-beta8\EntityFramework.Commands.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Relational\7.0.0-beta8\EntityFramework.Relational.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Core\7.0.0-beta8\EntityFramework.Core.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Ix-Async\1.2.5\Ix-Async.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Remotion.Linq\2.0.0-beta-002\Remotion.Linq.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Linq.Queryable\4.0.1-beta-23409\System.Linq.Queryable.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.ObjectModel\4.0.11-beta-23409\System.ObjectModel.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Data.Common\4.0.1-beta-23409\System.Data.Common.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.Relational.Design\7.0.0-beta8\EntityFramework.Relational.Design.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Compilation.CSharp\1.0.0-beta8\Microsoft.Dnx.Compilation.CSharp.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Compilation\1.0.0-beta8\Microsoft.Dnx.Compilation.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Runtime\1.0.0-beta8\Microsoft.Dnx.Runtime.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.Dnx.Loader\1.0.0-beta8\Microsoft.Dnx.Loader.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Runtime.Loader\4.0.0-beta-23409\System.Runtime.Loader.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.AppContext\4.0.1-beta-23409\System.AppContext.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Xml.ReaderWriter\4.0.11-beta-23409\System.Xml.ReaderWriter.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Newtonsoft.Json\6.0.6\Newtonsoft.Json.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\EntityFramework.SqlServer\7.0.0-beta8\EntityFramework.SqlServer.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Data.SqlClient\4.0.0-beta-23409\System.Data.SqlClient.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Data.Common\4.0.1-beta-23409\System.Data.Common.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\System.Text.Encoding.CodePages\4.0.1-beta-23409\System.Text.Encoding.CodePages.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Cookies\1.0.0-beta8\Microsoft.AspNet.Authentication.Cookies.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication\1.0.0-beta8\Microsoft.AspNet.Authentication.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Facebook\1.0.0-beta8\Microsoft.AspNet.Authentication.Facebook.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.OAuth\1.0.0-beta8\Microsoft.AspNet.Authentication.OAuth.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Google\1.0.0-beta8\Microsoft.AspNet.Authentication.Google.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.MicrosoftAccount\1.0.0-beta8\Microsoft.AspNet.Authentication.MicrosoftAccount.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Authentication.Twitter\1.0.0-beta8\Microsoft.AspNet.Authentication.Twitter.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Diagnostics.Entity\7.0.0-beta8\Microsoft.AspNet.Diagnostics.Entity.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Identity.EntityFramework\3.0.0-beta8\Microsoft.AspNet.Identity.EntityFramework.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Identity\3.0.0-beta8\Microsoft.AspNet.Identity.nuspec
  OPEN C:\Program Files (x86)\Microsoft Web Tools\DNU\Microsoft.AspNet.Cryptography.KeyDerivation\1.0.0-beta8\Microsoft.AspNet.Cryptography.KeyDerivation.nuspec
----------
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.UnzippedPackage.EnsureManifest()
   at NuGet.UnzippedPackage..ctor(IFileSystem fileSystem, String manifestPath)
   at NuGet.PackageInfo.get_Package()
   at Microsoft.Dnx.Runtime.NuGetDependencyResolver.<GetDependencies>d__4.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
NuGet Config files used:
    C:\Users\XXXXX\AppData\Roaming\NuGet\nuget.config
Feeds used:
    C:\Program Files (x86)\Microsoft Web Tools\DNU

PROJECT.JSON
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-WebApplication1-0e5d0870-3df0-4e08-92cc-1dfdfc4eea84",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-beta8",
    "EntityFramework.SqlServer": "7.0.0-beta8",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta8",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta8",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta8",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta8",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta8",
    "Microsoft.Framework.Logging": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Debug" : "1.0.0-beta8",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta8"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}

**Comment by agc93** [comment]
I am having the same issue. Any luck on working around it or sourcing a fix?

**Comment by taylorc** [comment]
No workaround or fix nor any interest from microsoft.

**Comment by davidfowl** [comment]
try deleting your caches and packages folder

**Comment by taylorc** [comment]
Deleting all folder/files from %userprofile%\.dnx\packages.

Then I had to delete all files/folders from %userprofile%\AppData\Roaming\npm-cache

This resolved the issue

**Comment by agc93** [comment]
Can confirm that deleting the contents of  %userprofile%.dnx\packages also worked for me, in case any other users find this.
