### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.AspNet.Builder.RequestDelegate' from assembly 'Microsoft.AspNet.Http.Abstractions'

### ISSUE THREAD

**Issue by yuezhongxin** [aspnet/Home#1138]
Exception message: 

```
2015-11-30 11:52:26.384 +08:00 [Error] Application startup exception
System.TypeLoadException: Could not load type 'Microsoft.AspNet.Builder.RequestDelegate' from assembly 'Microsoft.AspNet.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher..ctor(ConstructorInfo constructor)
   at Microsoft.Extensions.Internal.ActivatorUtilities.<>c.<CreateInstance>b__1_1(ConstructorInfo constructor)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNet.Builder.UseMiddlewareExtensions.<>c__DisplayClass2_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNet.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
```

project.json:

```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "EntityFramework.Core": "7.0.0-rc2-16432",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc2-15933",
    "Microsoft.AspNet.Mvc": "6.0.0-rc2-16498",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc2-16088",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Serilog.Framework.Logging": "1.0.0-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by Eilon** [comment]
You can't mix RC1 and RC2 dependencies. Pick one or the other.

**Comment by yuezhongxin** [comment]
Thank you, I modified `project.json` file, it works.

```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc2-15933",
    "Microsoft.AspNet.Mvc": "6.0.0-rc2-16498",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc2-16088",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc2-15977",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc2-15866",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-15866",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-15866",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-15867",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-15867",
    "Serilog.Framework.Logging": "1.0.0-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by HelloJesse** [comment]
@yuezhongxin that's why I received a email from 蟋蟀..... it's you!
