### ISSUE TITLE
dnu restore fails with System.TypeInitializationException

### ISSUE THREAD

**Issue by eBerdnA** [aspnet/Home#1162]
I have two different linux machines. Both are running Ubuntu 14.04. According to `dnvm list` I'm using ``1.0.0-rc1-final coreclr x64`` on both systems.

On both systems I'm simply trying to run the ConsoleApp example which can be found here: http://docs.efproject.net/en/latest/getting-started/linux.html

No problem on the first machine but on the second machine `dnu restore` causes the following error.
```
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16202

----------
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'libcurl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.HttpInitializer.EnsureCurlIsInitialized()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.libcurl..cctor()
   --- End of inner exception stack trace ---
   at Interop.libcurl.curl_version_info(Int32 curlVersionStamp)
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClient..ctor()
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource..ctor(String baseUri, String userName, String password, Reports reports)
   at Microsoft.Dnx.Tooling.PackageFeedCache.CreatePackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.PackageFeedCache.<>c__DisplayClass1_0.<GetPackageFeed>b__0(PackageSource _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Dnx.Tooling.PackageFeedCache.GetPackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 effectiveSources, PackageFeedCache packageFeeds, SummaryContext summary)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
```
I really can't find the difference which is causing this behaviour.

**Comment by eBerdnA** [comment]
Found the solution. The machine in question had a old version of mono installed. After updating mono dnu restore works as expected.
