### ISSUE TITLE
Question: How to resolve "No service for type 'Microsoft.Dnx.Runtime.IApplicationEnvironment' has been registered"

### ISSUE THREAD

**Issue by sherry-ummen** [aspnet/Home#1198]
Hi,

I saw lot of issues around the same problem but I could get my problem resolved following those. I am sorry if I failed to understand but please help a bit.

Here are the details:
```
c:\Users\NISU\OneDrive\Edu\ASP.NetMVC5\TheWorld>dnvm list

Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-beta8       clr     x64          win
       1.0.0-beta8       clr     x86          win
  *    1.0.0-rc1-update1 clr     x64          win             default
       1.0.0-rc1-update1 clr     x86          win
       1.0.0-rc1-update1 coreclr x64          win
       1.0.0-rc2-16355   clr     x86          win
```
I am using yo generator-aspnet (web application)

I get the exception when I do "dnx web"

```
c:\Users\NISU\OneDrive\Edu\ASP.NetMVC5\TheWorld>dnx web
System.InvalidOperationException: No service for type 'Microsoft.Dnx.Runtime.IApplicationEnvironment' has been registered.
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by davidfowl** [comment]
https://github.com/aspnet/Announcements/issues/104

**Comment by sherry-ummen** [comment]
Thanks so how can I resolve this in my generated code or I cannot?

**Comment by davidfowl** [comment]
Use the right assemblies as described in the announcement.

**Comment by davidfowl** [comment]
Use `Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment` instead of `Microsoft.Dnx.Runtime.IApplicationEnvironment`

**Comment by skamguia** [comment]
I am having the same issue but on OS X 10.11.3. I generated the project using yeoman as well. Has there been a resolution and if so could you post? Best regards

**Comment by davidfowl** [comment]
Not sure what you mean. I stated the solution to this problem in my last comment.

**Comment by sherry-ummen** [comment]
Thanks
