### ISSUE TITLE
Issue running aspnet 5 code from Linux

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#1273]
I worked through some issues w/ the help of JabbR to get a dummy aspnet 5 application running on Linux.

However, I have a real project that works in VS 2015 on Windows, and from command line on windows, but it throws the following error on the latest version of Ubuntu.
```
Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'FileUpload.Web, Culture=neutral, PublicKeyToken=null' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
File name: 'FileUpload.Web, Culture=neutral, PublicKeyToken=null' ---> Microsoft.Dnx.Compilation.CSharp.RoslynCompilationException: /media/sf_gitbase/FileUpload/src/FileUpload.Web/Api/UploadController.cs(32,13): DNXCore,Version=v5.0 error CS0012: The type 'Stream' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Dnx.Compilation.CSharp.RoslynProjectReference.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Compilation.CompilationEngine.LoadProject(Project project, FrameworkName targetFramework, String aspect, IAssemblyLoadContext loadContext, AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
```

Here is a link to the very simple project I was using: https://github.com/Sharpiro/FileUploader

**Comment by MaximRouiller** [comment]
Have you seen this part of the error message?

> error CS0012: The type 'Stream' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by Sharpiro** [comment]
@MaximRouiller 

I did notice that.  But my concern is, why should I need to add/change literally anything involved in the source/references when the project runs perfectly well on Windows?

If it's a linux library i am missing then that is more understandable.

**Comment by MaximRouiller** [comment]
Which version of the runtime are you using? Which one is installed on Windows and which one is installed on Linux? `4.0.11.0` refers to a version that looks like it's still in beta

**Comment by Sharpiro** [comment]
I'm using RC1 Update1 Core for both Linux and Windows

As far as frameworks i'm really unsure of what to be using these days.  The web project defaults to dnxcore50, but the class library defaults to dotnet5.4.  If someone could tell me what framework i should be using for asp.net 5 core development these days, that'd be great.

If you look at the simple project i linked you see that there are a wide range of dependencies from beta up to rc2.  But the project does in fact work in windows.

**Comment by MaximRouiller** [comment]
Among the dependencies, you should try to bring them to the latest RC. 

Otherwise you are running with packages that were built at different time and not thought to be run together. Can this work? Yeah maybe. If this doesn't work? We'll tell you to update your dependencies. 

I'm not even sure you should have RC2 in there.

**Comment by Sharpiro** [comment]
i'll see if i can get everything RC1 and then report back.
