### ISSUE TITLE
Feeds need Microsoft.DotNet.CoreHost

### ISSUE THREAD

**Issue by benaadams** [aspnet/Home#1289]
Feed `dotnet-core` has `Microsoft.DotNet.CoreHost` https://dotnet.myget.org/gallery/dotnet-core
Feed `aspnetcidev` does not https://www.myget.org/gallery/aspnetcidev

Which causes builds to fail:

```
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc2-16496'
Using makefile: makefile.shade
info: Exec
info:   program: dotnet
info:   commandline: restore ../../tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode
info:   workingdir: I:\Work\GitHub\KestrelHttpServer\src/Microsoft.AspNetCore.Server.Kestrel
info:   workingdir: I:\Work\GitHub\KestrelHttpServer\src/Microsoft.AspNetCore.Server.Kestrel
info : Restoring packages for I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.GeneratedCode\project.json...
error: Unable to resolve Microsoft.DotNet.CoreHost (>= 0.0.1-beta-00001) for DNXCore,Version=v5.0.
info : Committing restore...
info : Restore failed in 2879ms.
fail: Exit code 1 from dotnet
fail: Stack trace:
   at View2f7f06fb539c40a8b4fe694d84efb675.RenderViewLevel0() in c:\Users\Ben\AppData\Local\Temp\ddd9b6f3bdab47e59c5e68fec9ce589f-1.cs:line 11358
```

**Comment by pranavkm** [comment]
Is that being pulled in transitively? The package has an odd version (`v0.0.1-beta-00001`) while our build scripts is specifically mirroring `rc2` packages. cc @NTaylorMullen

**Comment by benaadams** [comment]
I assume its in some package that's been updated recently e.g. dotnet, corecli etc? Just tried a repo delete -> clone -> build for Kestrel to make sure I don't have any spurious extras, but errors with same.

Isn't the latest merge on Kestrel as I was geetting before that https://github.com/aspnet/KestrelHttpServer/commit/c5a8792ece9157698555947f159093892929cd93
But I did start getting it after the latest mygetfeed update serveral hours ago

AppVeyor is erroring with same https://ci.appveyor.com/project/aspnet-ci/kestrelhttpserver/build/1.0.1218#L871
Travis is erroring with same https://travis-ci.org/aspnet/KestrelHttpServer/builds/107934640#L2589

```
> ./build
Attempting to gather dependencies information for package 'KoreBuild-dotnet.0.2.1-rc2-15624' with respect to project '.build', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'KoreBuild-dotnet.0.2.1-rc2-15624' with DependencyBehavior 'Lowest'
Resolving actions to install package 'KoreBuild-dotnet.0.2.1-rc2-15624'
Resolved actions to install package 'KoreBuild-dotnet.0.2.1-rc2-15624'
Adding package 'KoreBuild-dotnet.0.2.1-rc2-15624' to folder '.build'
Added package 'KoreBuild-dotnet.0.2.1-rc2-15624' to folder '.build'
Successfully installed 'KoreBuild-dotnet 0.2.1-rc2-15624' to .build
Attempting to gather dependencies information for package 'Sake.0.2.2' with respect to project 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Sake.0.2.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Sake.0.2.2'
Resolved actions to install package 'Sake.0.2.2'
Adding package 'Sake.0.2.2' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Added package 'Sake.0.2.2' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Successfully installed 'Sake 0.2.2' to I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\
Attempting to gather dependencies information for package 'xunit.runner.console.2.1.0' with respect to project 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'xunit.runner.console.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xunit.runner.console.2.1.0'
Resolved actions to install package 'xunit.runner.console.2.1.0'
Adding package 'xunit.runner.console.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Added package 'xunit.runner.console.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Successfully installed 'xunit.runner.console 2.1.0' to I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\
Attempting to gather dependencies information for package 'xunit.core.2.1.0' with respect to project 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'xunit.core.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xunit.core.2.1.0'
Resolved actions to install package 'xunit.core.2.1.0'
Adding package 'xunit.abstractions.2.0.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Added package 'xunit.abstractions.2.0.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Successfully installed 'xunit.abstractions 2.0.0' to I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\
Adding package 'xunit.extensibility.core.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Added package 'xunit.extensibility.core.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Successfully installed 'xunit.extensibility.core 2.1.0' to I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\
Adding package 'xunit.extensibility.execution.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Added package 'xunit.extensibility.execution.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Successfully installed 'xunit.extensibility.execution 2.1.0' to I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\
Adding package 'xunit.core.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Added package 'xunit.core.2.1.0' to folder 'I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\'
Successfully installed 'xunit.core 2.1.0' to I:\Work\GitHub\KestrelHttpServer\.build\KoreBuild-dotnet\build\
dotnet_install: Preparing to install .NET Tools to C:\Users\Ben\AppData\Local\Microsoft\dotnet
dotnet_install: Latest version: 1.0.0.001248
dotnet_install: Local Version: 1.0.1.001200
dotnet_install: Downloading dotnet-win-x64.latest.zip from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest
dotnet_install: Extracting zip
dotnet_install: The .NET Tools have been installed to C:\Users\Ben\AppData\Local\Microsoft\dotnet\cli!
dotnet_install: Add 'C:\Users\Ben\AppData\Local\Microsoft\dotnet\cli\bin' to your PATH to use dotnet
Adding C:\Users\Ben\AppData\Local\Microsoft\dotnet\cli\bin to PATH
Setting DOTNET_HOME to C:\Users\Ben\AppData\Local\Microsoft\dotnet\cli
Determining latest version
'dnx-coreclr-win-x86.1.0.0-rc2-16496' is already installed in C:\Users\Ben\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc2-16496.
Adding C:\Users\Ben\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc2-16496\bin to process PATH
Updating alias 'default' to 'dnx-coreclr-win-x86.1.0.0-rc2-16496'
'dnx-clr-win-x86.1.0.0-rc2-16496' is already installed in C:\Users\Ben\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16496.
Adding C:\Users\Ben\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16496\bin to process PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc2-16496'
Using makefile: makefile.shade
info: Exec
info:   program: dotnet
info:   commandline: restore ../../tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode
info:   workingdir: I:\Work\GitHub\KestrelHttpServer\src/Microsoft.AspNetCore.Server.Kestrel
log  : Restoring packages for I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.GeneratedCode\project.json...
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json.
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json.
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/netstandard.library/index.json
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/netstandard.library/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json.
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json.
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json.
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/netstandard.library/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json.
info :   CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/netstandard.library/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json 520ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json 520ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json 542ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 537ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 538ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json 544ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json 533ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json 537ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json 551ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.features/index.json 561ms
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.dotnet.corehost/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.corehost/index.json.
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.dotnet.corehost/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.corehost/index.json.
info :   NotFound https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.dotnet.corehost/index.json 310ms
info :   NotFound https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.dotnet.corehost/index.json 319ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.corehost/index.json 478ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.corehost/index.json 489ms
error: Unable to resolve Microsoft.DotNet.CoreHost (>= 0.0.1-beta-00001) for DNXCore,Version=v5.0.
log  : Committing restore...
log  : Restore failed in 2491ms.

Errors in I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.GeneratedCode\project.json
    Unable to resolve Microsoft.DotNet.CoreHost (>= 0.0.1-beta-00001) for DNXCore,Version=v5.0.

NuGet Config files used:
    I:\Work\GitHub\KestrelHttpServer\NuGet.Config
    C:\Users\Ben\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
    https://api.nuget.org/v3/index.json
fail: Exit code 1 from dotnet
fail: Stack trace:
   at Viewcc1ac69f750c4e628d27a96e9d7ac101.RenderViewLevel0() in c:\Users\Ben\AppData\Local\Temp\cd169b0e5cd047d687beb09925933589-1.cs:line 11644
   at Viewcc1ac69f750c4e628d27a96e9d7ac101.Render() in c:\Users\Ben\AppData\Local\Temp\cd169b0e5cd047d687beb09925933589-1.cs:line 12207
   at Sake.Engine.Loader.DefaultLoader.Load(Options options)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
I:\Work\GitHub\KestrelHttpServer [aspnet/dev]>
```

**Comment by benaadams** [comment]
Searching all files
```
Find all "Microsoft.DotNet.CoreHost", Match case, Whole word, Subfolders, Find Results 1, "I:\Work\GitHub\KestrelHttpServer", "*.*"
  I:\Work\GitHub\KestrelHttpServer\samples\LargeResponseApp\project.lock.json(878):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\samples\LargeResponseApp\project.lock.json(2912):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\samples\LargeResponseApp\project.lock.json(4934):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\samples\SampleApp\project.lock.json(922):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\samples\SampleApp\project.lock.json(3035):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\samples\SampleApp\project.lock.json(5146):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.GeneratedCode\project.lock.json(450):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.GeneratedCode\project.lock.json(1943):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.GeneratedCode\project.lock.json(3845):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.LibuvCopier\project.lock.json(72):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.LibuvCopier\project.lock.json(672):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  I:\Work\GitHub\KestrelHttpServer\tools\Microsoft.AspNetCore.Server.Kestrel.LibuvCopier\project.lock.json(1878):          "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
  Matching lines: 12    Matching files: 4    Total files searched: 390
```

**Comment by benaadams** [comment]
In `.lock` file seems to be `NETStandard.Library/1.0.0-rc2-23805`
```
"NETStandard.Library/1.0.0-rc2-23805": {
    "type": "package",
    "dependencies": {
      "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001",
      "NETStandard.Platform": "1.0.0-rc2-23805",
      "System.Collections.Concurrent": "4.0.12-rc2-23805",
      "System.Linq": "4.0.2-rc2-23805",
      "System.Runtime.Numerics": "4.0.1-rc2-23805",
      "System.Text.RegularExpressions": "4.0.12-rc2-23805"
    }
},
```

**Comment by benaadams** [comment]
build works for Kestrel if delete from `makefile.shade`
```
exec program='dotnet' commandline='restore ../../tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode' workingdir='${kestrelSrcDir}'
exec program='dotnet' commandline='run -p ../../tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode Http/FrameHeaders.Generated.cs Http/Frame.Generated.cs' workingdir='${kestrelSrcDir}'

exec program='dotnet' commandline='restore' workingdir='${kestrelSrcDir}'
exec program='dotnet' commandline='restore ../../tools/Microsoft.AspNetCore.Server.Kestrel.LibuvCopier' workingdir='${kestrelSrcDir}'
exec program='dotnet' commandline='run -p ../../tools/Microsoft.AspNetCore.Server.Kestrel.LibuvCopier' workingdir='${kestrelSrcDir}'
```
delete all `samples\`
delete all `tools\` except for keyfile

**Comment by pranavkm** [comment]
Thanks for investigating this. I'm going to update our build scripts to clone this package along with the other CoreCLR packages.

**Comment by NTaylorMullen** [comment]
When we moved to the dotnet-core feed we decided to only pick up rc2 packages under the assumption that all other non-rc2 packages were unused. This seems to be the first package found that's required and not rc2.

**Comment by benaadams** [comment]
Adding to `NuGet.Config`
```
    <add key="DotNetDev" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```
Is also a work around

**Comment by benaadams** [comment]
Yeah... no; that makes things go very strange

**Comment by benaadams** [comment]
However using it briefly then removing it fixes things O_o

**Comment by GuardRex** [comment]
@benaadams This this applies now ...

"Tell Dexeter we've come full circle!" - First Decider Draith (Leonard Maguire), Dr. Who: Full Circle, 1980

**Comment by benaadams** [comment]
But then I get hangs ;-/

**Comment by GuardRex** [comment]
I had a hang restoring an hour ago, but this current project I'm working on just :sparkles: magically :sparkles: restored and compiled ok (but the restore was very slow ... maybe 20 minutes).

Are you using the @davidfowl CLI samples feed group? https://github.com/aspnet/cli-samples/blob/master/NuGet.Config

At the end, I added (the probably useless entry) ...
```xml
<add key="AspNetvNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
```
