### ISSUE TITLE
Can not run  web app on Ubuntu via coreclr RC1 update2

### ISSUE THREAD

**Issue by DormancyCypress** [aspnet/Home#1382]
I want to setup a cross platform work environment , developing on Windows 7 via Vs2015, and run it on Ubuntu 14.04.
 It works well on Windows, Kestrel, But failed  running  on Ubuntu.

When I execute command`dnu restore`, error msg like this: 

```
rqing@rqing-VirtualBox:~/shared/demo/AspNetCoreDemo/src/DNXWebDemo$ dnu restore
**Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16609
**
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /media/sf_Shared/demo/AspNetCoreDemo/src/DNXWebDemo/project.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.iisplatformhandler/index.json
Warning: FindPackagesById: Microsoft.AspNet.IISPlatformHandler
  The value cannot be null or empty.
Parameter name: UserName
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.iisplatformhandler/index.json
Warning: FindPackagesById: Microsoft.AspNet.IISPlatformHandler
  The value cannot be null or empty.
Parameter name: UserName
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.iisplatformhandler/index.json
Error: FindPackagesById: Microsoft.AspNet.IISPlatformHandler
 The value cannot be null or empty.
Parameter name: UserName
  .......
----------
System.ArgumentException: The value cannot be null or empty.
Parameter name: UserName
   at System.Net.Http.CurlHandler.EasyRequest.SetProxyOptions(Uri requestUri)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<GetAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
........
**Restore failed
The value cannot be null or empty.
Parameter name: UserName

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
**
```

Which shows it failed to download depency lib, but I don't know how to fix it ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
