### ISSUE TITLE
Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf()' on Windows 8

### ISSUE THREAD

**Issue by aplex** [aspnet/Home#1389]
On clean Windows 8.0 x64 we receive a "method not found" exception from Kestrel on application start.

Runtime: dnx-clr-win-x86.1.0.0-rc1-update2
Kestrel package version: Microsoft.AspNet.Server.Kestrel 1.0.0-rc1-final

The same app works fine on Windows 8.1/10 x64

```
System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf()'.
   at Microsoft.AspNet.Server.Kestrel.Networking.UvWriteReq.Init(UvLoopHandle loop)
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteContext.DoWriteIfNeeded()
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteAllPending()
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.<>c.<ScheduleWrite>b__15_0(SocketOutput _this)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.<>c__30`1.<Post>b__30_0(Object callback2, Object state2)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.DoPostWork() System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf()'.
   at Microsoft.AspNet.Server.Kestrel.Networking.UvWriteReq.Init(UvLoopHandle loop)
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteContext.DoWriteIfNeeded()
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteAllPending()
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.<>c.<ScheduleWrite>b__15_0(SocketOutput _this)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.<>c__30`1.<Post>b__30_0(Object callback2, Object state2)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.DoPostWork()

```

**Comment by davidfowl** [comment]
On the clean Windows 8.0 x64 machine. What version of .NET Framework is installed?

**Comment by aplex** [comment]
This is a VM with Windows 8 msdn image without additional software or updates installed (only with vmware tools).  So the .Net version is the one bundled with Win 8. 

From registry branch HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework , it looks like the version is v4.0.30319

**Comment by moozzyk** [comment]
[Marshal.SizeOf<T> Method ()](https://msdn.microsoft.com/en-us/library/dn261466(v=vs.110).aspx)

_Supported in the .NET Framework 4.5.1 and later versions_

**Comment by aplex** [comment]
As you can see from the stack trace, I'm not calling this method directly, but something inside of Kestrel  does.

Also, I was under impression that the needed .Net Framework runtime is bundled with the app, so that the app would not require any specific .Net version to be installed on this PC. In my case, there is a 10 mb folder "runtimes/dnx-clr-win-x86.1.0.0-rc1-update2", which, I thought, contains all the stuff needed to run the app (alongside with  nuget packages in a folder nearby).

**Comment by moozzyk** [comment]
You are running using clr runtime and not coreclr so your app just uses .NET Framework. For full framework .NET Framework 4.5.1 is the minimum supported version.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
