### ISSUE TITLE
SqlServer Session Exception in RC2 ASP.NET Core Web Application (.NET Framework)

### ISSUE THREAD

**Issue by mupedersen** [aspnet/Home#1560]
When trying to access the Session in a RC2 ASP.NET Core Web Application (.NET Framework) I get this exception:  

Could not load file or assembly 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 

It works in a RC2 ASP.NET Core Web Application (.NET Core).

Details:
```
Controller:
public class HomeController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.SetString("hello", "world"); // Exception
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";
            var x = HttpContext.Session.GetString("hello");
            return View();
        }

project.json:
{
  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.AspNetCore.Session": "1.0.0-rc2-final",
    "Microsoft.Extensions.Caching.SqlServer": "1.0.0-rc2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "net461": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

Startup.cs:
 public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
            services.AddDistributedSqlServerCache(options =>
            {
                options.ConnectionString = "xxx";
                options.SchemaName = "dbo";
                options.TableName = "SessionData";

            });
            services.AddSession(options =>
            {
                options.CookieName = ".AdventureWorks.Session";
                options.IdleTimeout = TimeSpan.FromSeconds(10);
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            app.UseSession();




StackTrace:
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.GetCacheItem(String key, Boolean includeValue)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.GetCacheItem(String key)
   at Microsoft.Extensions.Caching.SqlServer.SqlServerCache.Get(String key)
   at Microsoft.AspNetCore.Session.DistributedSession.Load()
   at Microsoft.AspNetCore.Session.DistributedSession.Set(String key, Byte[] value)
   at Microsoft.AspNetCore.Http.SessionExtensions.SetString(ISession session, String key, String value)
   at WebApplication2.Controllers.HomeController.Index() in C:\project\WebApplication2\src\WebApplication2\Controllers\HomeController.cs:line 14
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.ExecuteAsync(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionExecutor.ExecuteAsync(ObjectMethodExecutor actionMethodExecutor, Object instance, Object[] orderedActionArguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
```

**Comment by GuardRex** [comment]
@mupedersen Similar exception to when .NET 4.6.1 isn't installed on the machine. Check Programs & Features and confirm the framework is installed.

**Comment by mupedersen** [comment]
4.6.1 is installed (4.6.0.1055) on my machine:

PSChildName    Version          Release
-----------    -------          -------   
Client         4.6.01055        394271
Full           4.6.01055        394271

**Comment by GuardRex** [comment]
Ok ... worth a check since a similarly-worded exception appears when the .NET Framework version isn't installed.

**Comment by Sheens1983** [comment]
I receive this exact same error as well. My project has been working fine with session variables until I attempted to add a SQL Server store for session variables. This is done by adding in the package "Microsoft.Extensions.Caching.SqlServer". Try removing this from your project unless you wish to store sessions in the DB.

I would like to understand the issue behind this though as I am deploying my project to a web farm so I need to implement the Session State using SQL server

**Comment by GuardRex** [comment]
Not much out there on this one: http://stackoverflow.com/questions/37305514/asp-net-core-rc2-crashes-on-full-net-framework-when-using-distributed-caching ... and I noticed that caching samples are targeting `net451`. I recommend you close this issue here and re-open this over in https://github.com/aspnet/Caching/issues, where more caching pro :eyes: will see it.

**Comment by FourLeafClover** [comment]
Hello. HttpContext.Session.SetString("hello", "world"); 
always error: Session has not been configured for this application or request.
how you fix this. i have import aspnetcore.session.   and add the code in the startup.cs
<pre>
     app.UseSession();
     app.addSession
</pre>

**Comment by mupedersen** [comment]
Seems to be fixed in the RTM
