### ISSUE TITLE
Controller unit tests failing in CTP4 - missing assemblies

### ISSUE THREAD

**Issue by adubs** [aspnet/Home#161]
Yo,

Getting the following errors when trying to run controller unit tests

```
'AspNet' does not exist in the namespace 'Microsoft'

   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoaderEngine loaderEngine)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name)
   at klr.host.LoaderContainer.Load(String name)
   at klr.hosting.RuntimeBootstrapper.<>c__DisplayClass0.<ExecuteAsync>b__7(AssemblyName assemblyName)
   at klr.hosting.RuntimeBootstrapper.<>c__DisplayClass0.<ExecuteAsync>b__10(Object sender, ResolveEventArgs a)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

proj file is set up with the following frameworks:

```json
    "frameworks": {
        "net451": {
            "dependencies": {
            }
        },
                "k10" : { 
            "dependencies": {
                "System.Runtime": "4.0.20.0"
            }
        },
        "aspnet50": { },
        "aspnetcore50": { }
    }
```

and dependencies:

```json
    "dependencies": {
        "Xunit.KRunner": "1.0.0-alpha4",
        "Microsoft.AspNet.Diagnostics": "1.0.0-alpha4",
        "Microsoft.AspNet.Hosting": "1.0.0-alpha4",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-alpha4",
        "Microsoft.AspNet.Server.IIS": "1.0.0-alpha4",
        "Microsoft.AspNet.Mvc": "6.0.0-alpha4",
    },
```

**Comment by danroth27** [comment]
@adubs Let us know if you are still seeing issue with the latest xUnit test runner.
