### ISSUE TITLE
Application does not run after upgrading to 1.0 RTM

### ISSUE THREAD

**Issue by hiredgunhouse** [aspnet/Home#1614]
When I try to run `dotnet run` I get following exception:
Unhandled Exception: System.TypeLoadException: Method 'Log' in type 'Microsoft.Extensions.Logging.Logger' from assembly 'Microsoft.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at Microsoft.AspNet.Hosting.WebHostBuilder..ctor(IConfiguration config, Boolean captureStartupErrors)
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at XXXXXXXXXXXXX.Company.App.Startup.Main(String[] args) in C:\XXXXXXXXXXXXX.src\Company.App\Startup.cs:line 64

**Comment by Tratcher** [comment]
Want to share your project.json? It sounds like your dependencies are out of sync. Or push the whole project to a github repo.

**Comment by hiredgunhouse** [comment]
Sorry, this was a mess of dependencies which is resolved now, I'm closing this issue.
