### ISSUE TITLE
When publishing the Asp.Net RC2 application to azure, facing one issue - Could not load type 'System.ICloneable' 

### ISSUE THREAD

**Issue by premchandpl** [aspnet/Home#1653]
Configuring the following project for use with IIS: 'D:\local\Temp\PublishTemp\MyProject.Web126'
  Updating web.config at 'D:\local\Temp\PublishTemp\MyProject.Web126\web.config'
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [D:\home\site\repository\tree\master\cloud\src\solution\MyProject.Web\MyProject.Web.xproj]
  System.TypeLoadException: Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
     at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ProjectReaderSettings settings)
     at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
     at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.GetProjectContext(String applicationBasePath, String framework)
     at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
     at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
     at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)

Need to know if anybody facing this issue and if somebody had any solution, can you share that solution?

**Comment by memark** [comment]
Did you ever find a solution @premchandpl?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
