### ISSUE TITLE
Unable to run the Localization sample

### ISSUE THREAD

**Issue by hishamco** [aspnet/Home#1785]
This is not a localization specific, I just moved the issue from https://github.com/aspnet/Localization/issues/295 to home as @pranavkm suggest

**Comment by hishamco** [comment]
@ryanbrandenburg can you please look to this, coz I blocked!!

**Comment by ryanbrandenburg** [comment]
@hishamco what error are you getting when you run `.\build.cmd`? I'm able to run it successfully, but that's after having successfully run `build.cmd`.

**Comment by hishamco** [comment]
After run `git clean -xdf` and run the `build.cmd` I got this

Installed:
    10 package(s) to C:\Users\Dell\Source\Repos\Localization\src\Microsoft.Extensions.Localization\project.json
    10 package(s) to C:\Users\Dell\Source\Repos\Localization\src\Microsoft.AspNetCore.Localization.Routing\project.json
    9 package(s) to C:\Users\Dell\Source\Repos\Localization\src\Microsoft.AspNetCore.Localization\project.json
    27 package(s) to C:\Users\Dell\Source\Repos\Localization\test\LocalizationWebsite\project.json
    26 package(s) to C:\Users\Dell\Source\Repos\Localization\test\Microsoft.AspNetCore.Localization.Routing.Tests\project.json
    16 package(s) to C:\Users\Dell\Source\Repos\Localization\test\Microsoft.AspNetCore.Localization.FunctionalTests\project.json
    24 package(s) to C:\Users\Dell\Source\Repos\Localization\test\Microsoft.AspNetCore.Localization.Tests\project.json
    27 package(s) to C:\Users\Dell\Source\Repos\Localization\samples\LocalizationSample\project.json
    10 package(s) to C:\Users\Dell\Source\Repos\Localization\test\ResourcesClassLibraryWithAttribute\project.json
    11 package(s) to C:\Users\Dell\Source\Repos\Localization\test\Microsoft.Extensions.Localization.Tests\project.json
fail: Exit code 1 from dotnet
**fail: Stack trace:**
   at Viewc38c1ceb1b594679b917dc71ce1112ed.<RenderViewLevel0>b__a2() in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 9339
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewc38c1ceb1b594679b917dc71ce1112ed.StartingTarget(String name) in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 3591
   at Viewc38c1ceb1b594679b917dc71ce1112ed.<RenderViewLevel0>b__63() in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 4021
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewc38c1ceb1b594679b917dc71ce1112ed.StartingTarget(String name) in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 3591
   at Viewc38c1ceb1b594679b917dc71ce1112ed.<RenderViewLevel0>b__64() in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 4038
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewc38c1ceb1b594679b917dc71ce1112ed.StartingTarget(String name) in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 3591
   at Viewc38c1ceb1b594679b917dc71ce1112ed.<RenderViewLevel0>b__65() in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 4055
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewc38c1ceb1b594679b917dc71ce1112ed.StartingTarget(String name) in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 3591
   at Viewc38c1ceb1b594679b917dc71ce1112ed.<RenderViewLevel0>b__66() in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 4072
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Viewc38c1ceb1b594679b917dc71ce1112ed.<RenderViewLevel0>b__5e() in c:\Users\Dell\AppData\Local\Temp\206d37d9673f473882ecd8e7fdee8bc7-1.cs:line 3928
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by hishamco** [comment]
BTW when I run the localization sample I got this

The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-00' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002392
      1.0.0-rc2-3002702
      1.0.1
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.

I'm wonder why it shows the versions that inside the "shared", while previously when I run 'dotnet --version` is shows the one in `sdk` folder

**Comment by pranavkm** [comment]
@hishamco we're waiting on the CLI for 1.0.0 that bundles the 1.1.0 shared runtime to become available. You could try installing the runtime separately - https://dotnetcli.blob.core.windows.net/dotnet/release/1.1.0/Installers/1.1.0-preview1-001100-00/dotnet-win-x64.1.1.0-preview1-001100-00.exe, but I'd recommend waiting for the installers to become public. https://www.microsoft.com/net/download should have the links for this once it becomes available.

**Comment by hishamco** [comment]
thanks @pranavkm I will try it, but can you tell me how can I update the runtime to the latest bits (nightly builds) from the command line, I was remember doing `dnvm upgrade`

**Comment by hishamco** [comment]
Thanks a lot it works like a charm :)

**Comment by pranavkm** [comment]
> but can you tell me how can I update the runtime to the latest bits

We use some a couple of scripts for this - https://github.com/aspnet/KoreBuild/tree/dev/build/dotnet - but they aren't designed to be commonly consumed.

**Comment by hishamco** [comment]
Thanks a lot @pranavkm
