### ISSUE TITLE
fail: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, Pub licKeyToken=adb9793829ddae60[0]

### ISSUE THREAD

**Issue by jindovu** [aspnet/Home#1793]
Hi everyone
        Today I got a problem and I don't know why it happened, I integration between caching redis and .net core version RC2, Anyone can help 
`fail: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, Pub
licKeyToken=adb9793829ddae60[0]
      UvConnectionCb
fail: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, Pub
licKeyToken=adb9793829ddae60[0]
      UbReadCb
System.TypeLoadException: Method 'get_RawTarget' in type 'Microsoft.AspNetCore.S
erver.Kestrel.Http.Frame`1' from assembly 'Microsoft.AspNetCore.Server.Kestrel,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have
 an implementation.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.<>c__DisplayClass11_0`1.
<Start>b__0(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Connection.Start()
   at Microsoft.AspNetCore.Server.Kestrel.Http.ListenerPrimary.DispatchConnectio
n(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListenerPrimary.OnConnection(U
vStreamHandle listenSocket, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.ConnectionCallback(UvStr
eamHandle stream, Int32 status, Exception error, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvStreamHandle.UvConnection
Cb(IntPtr handle, Int32 status)
System.TypeLoadException: Method 'get_RawTarget' in type 'Microsoft.AspNetCore.S
erver.Kestrel.Http.Frame`1' from assembly 'Microsoft.AspNetCore.Server.Kestrel,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have
 an implementation.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.<>c__DisplayClass11_0`1.
<Start>b__0(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Connection.Start()
   at Microsoft.AspNetCore.Server.Kestrel.Http.ListenerSecondary.ReadStartCallba
ck(UvStreamHandle handle, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvStreamHandle.UvReadCb(Int
Ptr handle, Int32 status, uv_buf_t& buf)
Unhandled Exception: System.TypeLoadException: Method 'get_RawTarget' in type 'M
icrosoft.AspNetCore.Server.Kestrel.Http.Frame`1' from assembly 'Microsoft.AspNet
Core.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829
ddae60' does not have an implementation.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.<>c__DisplayClass11_0`1.
<Start>b__0(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Connection.Start()
   at Microsoft.AspNetCore.Server.Kestrel.Http.ListenerPrimary.DispatchConnectio
n(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListenerPrimary.OnConnection(U
vStreamHandle listenSocket, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.ConnectionCallback(UvStr
eamHandle stream, Int32 status, Exception error, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvStreamHandle.UvConnection
Cb(IntPtr handle, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.NativeMethods.uv_run(
UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.run(UvLoopHandle hand
le, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart(Object param
eter)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.Stop(TimeSpan timeout)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, Cancella
tionToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)`

**Comment by Tratcher** [comment]
Also remove `Microsoft.Owin.Security.Jwt`, it doesn't work with ASP.NET Core.

**Comment by jindovu** [comment]
oh yes, Thanks Tratcher for your recommended

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
