### ISSUE TITLE
.NET Core web app fails to run from a path containing a question mark

### ISSUE THREAD

**Issue by yaakov-h** [aspnet/Home#1890]
**Operating System:** macOS "Sierra" 12.12.2
**.NET Core SDK:** [.NET Core 1.1 x64 SDK 1.0.0](https://download.microsoft.com/download/1/4/1/141760B3-805B-4583-B17C-8C5BC5A876AB/Installers/dotnet-dev-osx-x64.1.0.0-preview2-1-003177.pkg)

I created a new folder at `/Users/yaakov/Development/Projects/Who knows?/BuzzerServer`.

I then created a new web project with `dotnet new -t Web`, ran `dotnet restore` and `dotnet run`.

This resulted in the following exception:

```
Project BuzzerServer (.NETCoreApp,Version=v1.1) will be compiled because inputs were modified
Compiling BuzzerServer for .NETCoreApp,Version=v1.1
/Users/yaakov/Development/Projects/Who knows?/BuzzerServer/project.lock.json(1,0): warning NU1006: Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.0939920
 


Unhandled Exception: System.ArgumentException: Invalid directory on URL.
   at System.Security.Util.DirectoryString.CreateSeparatedString(String directory)
   at System.Security.Util.URLString.ParseString(String url, Boolean parsed)
   at System.Security.Util.URLString.GetFileName()
   at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
   at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStartup(IWebHostBuilder hostBuilder, Type startupType)
   at WebApplication.Program.Main(String[] args) in /Users/yaakov/Development/Projects/Who knows?/BuzzerServer/Program.cs:line 14
```

If I move the folder to a path that does not contain a question mark, the project runs successfully.

```
Compiling BuzzerServer for .NETCoreApp,Version=v1.1

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.1489371
 

info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/Users/yaakov/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Content root path: /Users/yaakov/Development/Projects/Active/BuzzerServer
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#14717
