### ISSUE TITLE
Yeoman Generator - Dot Net Restore does not work

### ISSUE THREAD

**Issue by ebetron** [aspnet/Home#1925]
Running Mac OSX 10.9.5

Followed the instructions to install .NET Core SDK on https://www.microsoft.com/net/core#macos

dotnet new command throws exception: 
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'CCRandomGenerateBytes' in DLL '/usr/lib/system/libcommonCrypto'.
   at Interop.CommonCrypto.CCRandomGenerateBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytesApple(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

.NET Core Version: 1.0.0-preview-2-1-003177

**Comment by peterblazejewicz** [comment]
@ebetron 
You could close this now.

dup: https://github.com/OmniSharp/generator-aspnet/issues/893
