### ISSUE TITLE
'dotnet PublishedAspNetCore.dll' crashes if working directory is not publish folder where the dll resides

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#1988]
_From @ChristophB125 on April 6, 2017 10:43_

## Steps to reproduce
1.) 'dotnet publish' an asp.net core (1.1) app. 
2.) One can run the app by pointing dotnet to the main dll in the publish folder 'dotnet 'MyAspNetCoreDllInPublishFolder.dll'. However, this only works if the current directory is the publish folder where the dll resides.

## Expected  behavior
I can just specify the full path to the dll to be run and as long as the dll is inside the publish folder, it should just work

## Actual behavior
It crashes:

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not
 optional. The physical path is 'C:\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MyProduct.Startup..ctor(IHostingEnvironment env) in D:\_Builds\1\1\s\MyProduct\Startup.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type star
tupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCa
llSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvide
r provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider prov
ider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider p
rovider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyProduct.Program.Main(String[] args) in D:\_Builds\1\1\s\MyProduct\Program.cs:line 14

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

_Copied from original issue: dotnet/cli#6257_

**Comment by livarcocc** [comment]
I believe in this case you need to change the path of where the appsettings.json file is located. There is a property to do that, but I don't remember exactly which one. I think I saw @vijayrkn replying to an issue here about it already. So, maybe he can help.

Meanwhile, I am moving this issue to asp.net, this isn't really a CLI code that you are hitting.

**Comment by vijayrkn** [comment]
Related? - https://github.com/dotnet/cli/pull/1382

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by bergmeister** [comment]
@Eilon I think it is unreasonable to close this bug simply because no update was provided from the MS side.

**Comment by Eilon** [comment]
@bergmeister I believe this issue is by design. The current directory is incorrect, so the app can't find a required file, so the app crashes. There are no plans to change how the configuration files are located.
