### ISSUE TITLE
Accessing any URL on project run results in this

### ISSUE THREAD

**Issue by nixxholas** [aspnet/Home#2145]
```
System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestStream.Seek(Int64 offset, SeekOrigin origin)
   at SharpRaven.Core.Data.DefaultHttpRequestBodyConverter.TryConvert(HttpContext httpContext, Object& converted)
```

In case you need to see what happens before that,

```
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/Users/nixholas/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Development
Content root path: /Users/nixholas/Projects/Volt/Volt
Now listening on: http://localhost:49982
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:49982/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Volt.Controllers.Views.HomeController.Index (Volt) with arguments ((null)) - ModelState is Valid
```

**Comment by davidfowl** [comment]
The exception and call stack are pretty clear on what the issue is, you can't seek the request stream. 

> SharpRaven.Core.Data.DefaultHttpRequestBodyConverter.TryConvert

This component is doing the wrong thing. What is it?

**Comment by nixxholas** [comment]
@davidfowl Apologies. That was my own error. Here's the one.

**While running dotnet run:**
```
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:52593/img/bg-pattern.png
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:52593/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.RequireHttpsAttribute'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.RequireHttpsAttribute'.
info: Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor[1]
      Executing RedirectResult, redirecting to https://localhost/.
info: Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor[1]
      Executing RedirectResult, redirecting to https://localhost/oops/404.
```

**While running via MacOS' Visual Studio:**
```
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HL76EO1R1G77" bad request data: "Invalid request line: <0x16><0x03><0x01><0x00><0xB1><0x01><0x00><0x00><0xAD><0x03><0x01>K<0xE4>r@<0x82>9'#L<0xD7><0x0A>"
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Invalid request line: <0x16><0x03><0x01><0x00><0xB1><0x01><0x00><0x00><0xAD><0x03><0x01>K<0xE4>r@<0x82>9'#L<0xD7><0x0A>
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2017-08-19T04:10:29.1852930Z","tags":{"ai.internal.sdkVersion":"aspnet5c:2.0.1","ai.application.ver":"1.0.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Connection id \"0HL76EO1R1G76\" stopped.","severityLevel":"Verbose","properties":{"DeveloperMode":"true","CategoryName":"Microsoft.AspNetCore.Server.Kestrel","AspNetCoreEnvironment":"Development","ConnectionId":"0HL76EO1R1G76","{OriginalFormat}":"Connection id \"{ConnectionId}\" stopped."}}}}
Microsoft.AspNetCore.Server.Kestrel:Information: Connection id "0HL76EO1R1G77" bad request data: "Invalid request line: <0x16><0x03><0x01><0x00><0xB1><0x01><0x00><0x00><0xAD><0x03><0x01>K<0xE4>r@<0x82>9'#L<0xD7><0x0A>"

Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Invalid request line: <0x16><0x03><0x01><0x00><0xB1><0x01><0x00><0x00><0xAD><0x03><0x01>K<0xE4>r@<0x82>9'#L<0xD7><0x0A>

```

**Comment by davidfowl** [comment]
Did you connect to kestrel via https while only running via http?

**Comment by nixxholas** [comment]
I don't think so, I've been able to connect via https for a long time. Here's some lines of code that could be relevant.

**Startup.cs:**
```
services.AddMvc(options =>
            {
                options.Filters.Add(new RequireHttpsAttribute());
            })
            // https://stackoverflow.com/questions/41305294/converting-infinitely-nested-objects-in-net-core
            .AddJsonOptions(options =>
            {
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            });
```

**Program.cs:**
```
var cert = new X509Certificate2("xxxx", "xxxx");
            
            var host = new WebHostBuilder()
                .UseKestrel(options => {
					options.UseHttps(("xxxx", "xxxx"));
            })
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

            host.Run();
```

**Comment by nixxholas** [comment]
Debugging on Windows works, not on Mac.

<img width="1437" alt="screen shot 2017-08-19 at 12 55 35 pm" src="https://user-images.githubusercontent.com/4703269/29483661-cf09f9aa-84dd-11e7-97c1-2295716d0d9a.png">

**Comment by davidfowl** [comment]
That error message you got usually happens when you're hitting an http end point via https. Are you *sure* that you are binding to an HTTPS endpoint on OSX?

On windows are you using kestrel directly or are you using IIS?

**Comment by nixxholas** [comment]
@davidfowl Apologies for the hassle to you. Windows, IIS. 

I am not sure because development on Mac since the VS preview had no problems with the current setup. Is there a guide for binding the endpoint?

**Comment by davidfowl** [comment]
> @davidfowl Apologies for the hassle to you. Windows, IIS.

No worries .

@nixxholas yea from the looks of it you're using IIS for https and on OSX there's nothing that's why it's failing.

> Is there a guide for binding the endpoint?

The HTTPS story is different if you're using IIS vs not. Look at this doc for more details https://docs.microsoft.com/en-us/aspnet/core/security/https.

**Comment by nixxholas** [comment]
@davidfowl Have implemented Kestrel's HTTPS as advised. Thank you!
