### ISSUE TITLE
UseOpenIdConnectAuthentication InvalidOperationException

### ISSUE THREAD

**Issue by jayslife** [aspnet/Home#2196]
I am getting the same error as Edward that is tracked here #2155.
We are still using: netcoreapp1.1 
Error
```
Unhandled Exception: System.InvalidOperationException: Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware..ctor(RequestDelegate next, IDataProtectionProvider dataProtectionProvider, ILoggerFactory loggerFactory, UrlEncoder encoder, IServiceProvider services, IOptions``1 sharedOptions, IOptions``1 options, HtmlEncoder htmlEncoder)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```

This error only occurs when trying to run my site from the command line via **dotnet run**,but not when project is built and ran in Visual Studios.
I don't have a custom IOptionsMonitor as was the issue from the other ticket.

Here is my 
```
var baseUrl = appSettings.Value.BaseUrl;
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",
                Authority = baseUrl,
                //should be true in prod!
                RequireHttpsMetadata = false,
                ClientId = "customclient",
                ClientSecret = "secretissafewithme",
                ResponseType = "code id_token",
                Scope = {"api1", "offline_access"},
                GetClaimsFromUserInfoEndpoint = true,

                SaveTokens = true,

                TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role,
                },
                //UseTokenLifetime = true,
                Events = new OpenIdConnectEvents
                {
                    // Called when authentication is completed. This is the last event, assuming that authentication succeeds. 
                    // After this event is handled, the user is signed into the app.
                    OnTicketReceived = async trc =>
                    {
                        await Task.Run(() =>
                        {
                            // store both tokens in the claims/cookie.
                            var identity = trc.Ticket.Principal.Identity as ClaimsIdentity;
                            identity.AddClaims(new[]
                            {
                                new Claim("access_token", trc.Ticket.Properties.GetTokenValue("access_token")),
                                new Claim("refresh_token", trc.Ticket.Properties.GetTokenValue("refresh_token")),
                                new Claim("expires_at", trc.Ticket.Properties.GetTokenValue("expires_at")),
                            });

                            // cookie is good for multiple requests
                            trc.Properties.IsPersistent = true;
                            // set 12h expiration
                            trc.Properties.ExpiresUtc = DateTimeOffset
                                .Parse(trc.Ticket.Properties.GetTokenValue("expires_at")).AddHours(12);
                        });
                    },
                },
            });
```

I would like to run without the use of Visual Studios, which it runs perfectly fine on. Any thoughts  @HaoK?

**Comment by Tratcher** [comment]
Sounds like a configuration issue. I bet `Authority = baseUrl,` is null.

**Comment by jayslife** [comment]
I updated the snip-it above, the baseurl comes from the app settings and is configured properly. reminder this works fine when ran in Visual Studios.

**Comment by Tratcher** [comment]
Write baseUrl out to the console to be sure.

**Comment by jayslife** [comment]
I'm not not sure how to do that as this is failing in in Main during the host build/run process.

**Comment by Tratcher** [comment]
`Console.Writeline(appSettings.Value.BaseUrl);` in startup.

**Comment by jayslife** [comment]
You are correct in your assumption as i added 
`if(string.IsNullOrEmpty(baseUrl))
                Console.WriteLine("base url is null");`

base url is null gets outputted.

I also know why this is happening.

For future reference: We have appsettings.json and appsettings.Development.json. In our setup the appsettings.json get populated by the build server; therefore, the settings appsettings.Development.json arn't being used by dotnet build without specifying the environment.
