### ISSUE TITLE
Running k web from mapped network drive causes unhandled exception (klr.exe has stopped working)

### ISSUE THREAD

**Issue by clintkolodziej** [aspnet/Home#24]
When running the 'k web' command from one of the samples (HelloWeb, HelloMvc) from a mapped network drive (w:) I get the following unhandled exception.  Probably not a bad idea to just output an error message, or a security confirmation message asking the user if it is safe to run, rather than crashing out the klr.exe.

Output from the command:

`W:\repositories\Home\samples\HelloMvc>k web`

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation. ---> System.Reflection.TargetInvocat
ionException: Exception has been thrown by the target of an invocation. ---> Sys
tem.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.Host
ing' or one of its dependencies. Operation is not supported. (Exception from HRE
SULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load
 an assembly from a network location which would have caused the assembly to be
sandboxed in previous versions of the .NET Framework. This release of the .NET F
ramework does not enable CAS policy by default, so this load may be dangerous. I
f this load is not intended to sandbox the assembly, please enable the loadFromR
emoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more
information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence
)
   at System.Reflection.Assembly.LoadFile(String path)
   at klr.hosting.LoaderEngine.LoadFile(String path)
   at klr.host.DefaultLoaderEngine.LoadFile(String path)
   at Microsoft.Framework.Runtime.Loader.NuGet.NuGetAssemblyLoader.Load(LoadCont
ext loadContext)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoader.LoadImpl(LoadContext loa
dContext, Stopwatch sw)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoader.Load(LoadContext loadCon
text)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoader.LoadAssembly(LoadContext
 loadContext)
   at Microsoft.Framework.Runtime.DefaultHost.Load(String name)
   at klr.host.HostContainer.Load(String name)
   at klr.hosting.RuntimeBootstrapper.<>c__DisplayClass0.<Execute>b__8(AssemblyN
ame assemblyName)
   at klr.hosting.RuntimeBootstrapper.<>c__DisplayClass0.<Execute>b__11(Object s
ender, ResolveEventArgs a)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String a
ssemblyFullName)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String cod
eBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String code
Base, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& s
tackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntros
pection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName as
semblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationNa
me)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at klr.host.Bootstrapper.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at klr.hosting.RuntimeBootstrapper.Execute(String[] args)
   at DomainManager.Main(Int32 argc, String[] argv)
```

**Comment by masaeedu** [comment]
Is there a workaround for this?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
