### ISSUE TITLE
What am I doing wrong to get this error? DPAPI NG (With SID)

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2517]
_From @eyrenshaw on Monday, March 13, 2017 4:54:27 PM_

I must be missing something with this setup.  Any ideas would be appreciated!

I have 2012 R2 server. 
I see my SID on that server (S-1-5-21-606747145-1060...)
The share location for the key (I have full rights to the location)

I setup the following in code:

`var serviceCollection = new ServiceCollection();
serviceCollection.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(sharedKeyDirectory))
                .ProtectKeysWithDpapiNG("SID=S-1-5-21-606747145-1060...", DpapiNGProtectionDescriptorFlags.None).SetApplicationName("myApp");

            return serviceCollection.BuildServiceProvider();`

**Not matter what I do I get the following error:**

System.Security.Cryptography.CryptographicException: Encryption failed.
   at Microsoft.AspNetCore.Cryptography.UnsafeNativeMethods.ThrowExceptionForNCryptStatusImpl(Int32 ntstatus)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNGCore(NCryptDescriptorHandle protectionDescriptorHandle, Byte* pbData, UInt32 cbData)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNG(ISecret secret, NCryptDescriptorHandle protectionDescriptorHandle)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiNGXmlEncryptor.Encrypt(XElement plaintextElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)

_Copied from original issue: aspnet/DataProtection#205_

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Thursday, May 4, 2017 12:48:45 PM_

@eyrenshaw I'm able to reproduce the error too. Unfortunately, "Encryption failed" is a generic error that often hides another problem. To make sure we are both seeing the same error, can you provide more information from Windows logging?

1. Launch Event Viewer from Start Menu > Administrative Tools > Event Viewer.
2. The ncrypt logger is found in Event Viewer > Application and Services Logs > Microsoft > Windows > Crypto-NCrypt > Operational.
3. Right click on "Operational" and select "Enable log" from the context menu.
4. Re-run your .NET app that produces the error.
5. One or more errors should appear in the logger when you click "Refresh". 

Any additional info you can share from this logger will help us be sure we've traced down the source of the issue. My logger shows two errors. The first one ("Protect Secret operation failed", return code 0x80090034) is the generic error that .NET is throwing. The second error is the real issue that was wrapped by the first. In my repro, it's "Protect Key operation failed.", return code 0x80070005. I'm still investigating a fix for this, but want to make sure this is the same thing you are seeing.

Don't forget to disable the logger after you're finished. (Right click on "Operational" and select "Disable log")

**Comment by aspnet-hello** [comment]
_From @eyrenshaw on Thursday, May 4, 2017 4:36:41 PM_

Hi Nate,

Yes I am seeing the same thing in the event logs:

First event ---
Protect Key operation failed.

Cryptographic Parameters:
       Protector Name:        SID
       Protector Attributes:
                       S-1-5-21-60674714...
       Flags:         0x40
Failure Information:
       Return Code:   0x8007054B


Second event ---
Protect Secret operation failed.

Cryptographic Parameters:
      Flags:       0x40
Failure Information:
      Return Code: 0x80090034

Thank you for taking a look. It will be great to get this working.

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Thursday, May 4, 2017 5:00:00 PM_

Thanks. The error code you're getting (0x8007054B) is ERROR_NO_SUCH_DOMAIN. Can you tell me more about your domain infrastructure? i.e. what type of domain controllers do you have and how many? what's the domain environment? Are you able to ping the domain controller from the box that produces this error?

**Comment by aspnet-hello** [comment]
_From @comburo on Wednesday, June 21, 2017 5:31:39 AM_

I'm seeing the same issue.
I am able to ping the domain controllers, but I know little else about the domain configuration, since that is handled outside my team. I know the domain works for this server, because I can log in with my domain account and it runs on of our applications that runs under domain credentials and allows people to log in using their domain credentials.

**Comment by aspnet-hello** [comment]
_From @j-tee on Friday, June 23, 2017 9:52:45 AM_

Just got into a similar difficulty here. Wished you had found a solution

**Comment by aspnet-hello** [comment]
_From @carl-thomas on Monday, July 3, 2017 9:30:43 AM_

I am trying to use a certificate and I get the following error in the Event Viewer NCrypt log
```
Protect Key operation failed.

 Cryptographic Parameters:
 	Protector Name:	CERTIFICATE
 	Protector Attributes:
			HashId:‎***
 	Flags:		0x40
 Failure Information:
 	Return Code:	0x80090005
```

```
Protect Secret operation failed.

 Cryptographic Parameters:
 	Flags:		0x40
 Failure Information:
 	Return Code:	0x80090034
```

This error is not very descriptive. What is this error telling me? It cannot read the certificate? The certificates private key? It just failed during encryption??

Can anyone help?

**Comment by blowdart** [comment]
This is really old, but it looks like this is a bug in Windows unfortunately, so we await a fix from them
