### ISSUE TITLE
ProtectKeysWithDpapiNG using certificate from LocalMachine store fails

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2521]
_From @scorgatelli on Thursday, September 8, 2016 2:32:49 PM_

Using this configuration, where the identified certificate is in the `LocalMachine\My` cert store,

``` c#
services.AddDataProtection()
  .PersistKeysToFileSystem(new DirectoryInfo(_keyDirectory))
  .ProtectKeysWithDpapiNG("CERTIFICATE=HashId:4DA11316E5943B27454001515BB0C8DC1BFDC347",
    flags: DpapiNGProtectionDescriptorFlags.None)
```

I get the following exception when trying to protect some data:

```
System.Security.Cryptography.CryptographicException: Encryption failed.
   at Microsoft.AspNetCore.Cryptography.UnsafeNativeMethods.ThrowExceptionForNCryptStatusImpl(Int32 ntstatus)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNGCore(NCryptDescriptorHandle protectionDescriptorHandle, Byte* pbData, UInt32 cbData)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNG(ISecret secret, NCryptDescriptorHandle protectionDescriptorHandle)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiNGXmlEncryptor.Encrypt(XElement plaintextElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
```

I get the same error whether I run the application manually using `dotnet run` or under IIS. I have granted both my user and the app pool identity permissions to the private key for the certificate. When I run it using `dotnet run` using a cert from the current user store it works fine.

I created the certificate using:

```
new-selfsignedcertificate -DnsName "testcert" -CertStoreLocation "cert:\LocalMachine\My" -KeyAlgorithm RSA -KeyLength 2048 -KeyExportPolicy Exportable -NotAfter "Friday, August 29, 2036 12:00:00 AM"
```

Any ideas on how I can get this working?

Thanks

_Copied from original issue: aspnet/DataProtection#176_

**Comment by aspnet-hello** [comment]
_From @muratg on Friday, September 23, 2016 10:27:45 AM_

@blowdart any idea what the issue may be?

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, September 23, 2016 10:30:27 AM_

Nope. Have a dev singlestep it and see what we're getting back from Protect().

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, September 26, 2016 3:39:33 PM_

Assigning to @mikaelm12 for Investigation.

**Comment by aspnet-hello** [comment]
_From @blowdart on Thursday, September 29, 2016 2:59:06 PM_

So @mikaelm12 figured out that it'll encrypt just fine, but when it decrypts the cert has to be trusted. Which of course self signed certs are not.

Pop the cert in the root CA store and see if that solves it.

**Comment by aspnet-hello** [comment]
_From @Excommunicated on Friday, October 7, 2016 6:35:04 AM_

I also get the same error as reported by @scorgatelli, The main difference is that my certificate is not self signed, and is issued by a Trusted Authority. 
The issue appears to be that the certificate must be in the executing users local certificate store. Certificates in the local machine store will fail with the original reported exception.

**Comment by aspnet-hello** [comment]
_From @mrsquish on Monday, May 8, 2017 7:58:19 PM_

Thought this was going to be my saving grace to get DataProtection working on Service Fabric, but alas due to the error it's yet another failed solution.

**Comment by aspnet-hello** [comment]
_From @patnolan on Monday, June 12, 2017 11:12:14 PM_

Hi...Has there been any progress around a solution for this issue?

I'm using ASPNetCore and want to use ProtectKeysWithDpapiNG to encrypt a password but I'm getting the following exception when executing "protector.Protect("password");" (see stack trace below)
System.Security.Cryptography.CryptographicException: 'The specified data could not be decrypted.'

I'm using a .pfx file which has been installed for the Current User. To create the .pfx file I used makecert and pvk2pfx.

Am I doing something wrong? Should this work?

**My Code...**

**AddDataProtection in ConfigureServices(IServiceCollection services) code**
```
using (var store = new X509Store(StoreName.My, StoreLocation.CurrentUser))
{
     store.Open(OpenFlags.ReadOnly);
     var protection = services.AddDataProtection();
     protection.ProtectKeysWithDpapiNG($"CERTIFICATE=HashId:{<thumbprint>}", flags: 
     DpapiNGProtectionDescriptorFlags.None);

     protection.PersistKeysToFileSystem(new DirectoryInfo(<location>));
     protection.SetApplicationName("<appname>");
}
```

**CreateProtector code**
```
var protection = app.ApplicationServices.GetDataProtectionProvider();
var protector = protection.CreateProtector("<protector>");
var test = protector.Protect("password");
```

**StackTrace**	
```   at Microsoft.AspNetCore.Cryptography.UnsafeNativeMethods.ThrowExceptionForNCryptStatusImpl(Int32 ntstatus)\r\n   
at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiNGCore(Byte* pbData, UInt32 cbData)\r\n   
at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiNG(Byte[] protectedData)\r\n   
at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiNGXmlDecryptor.Decrypt(XElement encryptedElement)\r\n  
 at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)\r\n   
at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)\r\n   
at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyEncryptorDelegate>b__0()\r\n   
at System.Lazy`1.CreateValue()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
at System.Lazy`1.get_Value()\r\n  
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)\r\n   
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()\r\n   
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\r\n   
at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)
```

**Comment by aspnet-hello** [comment]
_From @patnolan on Tuesday, June 13, 2017 3:55:03 AM_

Followed the advice in #215 and generated my new .pfx using openssl instead of makecert and it works!

openssl genrsa -out priva
openssl req -new -x509 -key private.key -out publickey.cer -days 365
openssl pkcs12 -export -out public_privatekey.pfx -inkey private.key -in publickey.cer

**Comment by aspnet-hello** [comment]
_From @htuomola on Friday, November 17, 2017 5:13:20 AM_

Like @mrsquish I tried to use this for Service Fabric multi-node data protection but it fails with "CryptographicException: Invalid provider type specified". Even tried with a CA-issued valid certificate (in LocalMachine\My store), to no awail. Haven't tried running this on service fabric VMs in azure yet, to see if the problem happens there too.

Stacktrace/log:
```
[Error] An exception occurred while processing the key element '"<key id=\"7a7c6e7f-1ca4-4930-9164-bcd6c13db5f6\" version=\"1\" />"'.
System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey)
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
```

**Comment by blowdart** [comment]
makecert is deprecated, and uses older certificate providers, so it's not that unexpected it'll choke on ServiceBus.

Use [Powershell](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps) instead.
