### ISSUE TITLE
Help: Not Issue With Home But.. (xunit/aspnet.xunit)

### ISSUE THREAD

**Issue by kscott5** [aspnet/Home#267]
There's not Issues tab for the Xunit or ASPNET.Xunit repository but still need your help. I'm trying to execute build.cmd script and it fails on tests. Basically, failing to discover Mvc.dll.

```powershell
PS F:\apps\pcsc\GreenShelter> .\build.cmd >> build.log

Adding F:\tools\.kre\packages\KRE-CLR-x86.1.0.0-rc1-10877\bin to process PATH
info: Target default
info: Target pre-clean
info: Target target-dir-clean
info: Target build-clean
info: Target clean
info: Target post-clean
info: Target validate
info: Target repo-initialize
info: Exec
info:   program: cmd
info:   commandline: /C kpm restore
info:   workingdir: F:\apps\pcsc\GreenShelter
Restoring packages for F:\apps\pcsc\GreenShelter\src\Mvc\project.json
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById?id='Microsoft.Framework.ConfigurationModel'&$skiptoken='Microsoft.Framework.ConfigurationModel','1.0.0-rc1-10675'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel.Json'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel.Json'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging.NLog'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging.NLog'
Resolving complete, 241ms elapsed
Restore complete, 247ms elapsed
Restoring packages for F:\apps\pcsc\GreenShelter\test\Mvc\project.json
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById?id='Microsoft.Framework.ConfigurationModel'&$skiptoken='Microsoft.Framework.ConfigurationModel','1.0.0-rc1-10675'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel.Json'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel.Json'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='xunit.runner.kre'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='xunit.runner.kre'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging.NLog'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging.NLog'
Resolving complete, 48ms elapsed
Restore complete, 48ms elapsed
Total time 477ms
info: Target initialize
info: Target build-compile
info: Exec
info:   program: cmd
info:   commandline: /C kpm build src\Mvc --configuration Debug
info:   workingdir: F:\apps\pcsc\GreenShelter

Building Mvc for Asp.Net,Version=v5.0
  Using Project dependency Mvc 1.0.0.0
    Source: F:\apps\pcsc\GreenShelter\src\Mvc\project.json

  Using Package dependency Microsoft.Framework.ConfigurationModel 1.0.0-rc1-10694
    Source: F:\tools\.kpm\packages\Microsoft.Framework.ConfigurationModel\1.0.0-rc1-10694
    File: lib\aspnet50\Microsoft.Framework.ConfigurationModel.dll

  Using Package dependency Microsoft.Framework.ConfigurationModel.Json 1.0.0-rc1-10694
    Source: F:\tools\.kpm\packages\Microsoft.Framework.ConfigurationModel.Json\1.0.0-rc1-10694
    File: lib\aspnet50\Microsoft.Framework.ConfigurationModel.Json.dll

  Using Package dependency Microsoft.Framework.Logging 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Framework.Logging\1.0.0-beta1
    File: lib\aspnet50\Microsoft.Framework.Logging.dll

  Using Package dependency Microsoft.Framework.Logging.Console 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Framework.Logging.Console\1.0.0-beta1
    File: lib\aspnet50\Microsoft.Framework.Logging.Console.dll

  Using Package dependency Kestrel 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Kestrel\1.0.0-beta1
    File: lib\aspnet50\Kestrel.dll

  Using Package dependency Microsoft.AspNet.Diagnostics 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Diagnostics\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Diagnostics.dll

  Using Package dependency Microsoft.AspNet.Hosting 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Hosting\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Hosting.dll

  Using Package dependency Microsoft.AspNet.Mvc 6.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Mvc\6.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Mvc.dll

  Using Package dependency Microsoft.AspNet.Mvc.Core 6.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Mvc.Core\6.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Mvc.Core.dll

  Using Package dependency Microsoft.AspNet.Routing 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Routing\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Routing.dll

  Using Package dependency Microsoft.AspNet.Server.WebListener 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Server.WebListener\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Server.WebListener.dll

  Using Package dependency Microsoft.AspNet.StaticFiles 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.StaticFiles\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.StaticFiles.dll

  Using Package dependency Mongodb 1.7.1.4791
    Source: F:\tools\.kpm\packages\Mongodb\1.7.1.4791

  Using Package dependency MongoDB.AspNet.Identity 1.0.5
    Source: F:\tools\.kpm\packages\MongoDB.AspNet.Identity\1.0.5
    File: lib\net45\MongoDB.AspNet.Identity.dll

  Using Package dependency Microsoft.Framework.Logging.NLog 1.0.0-rc1-10702
    Source: F:\tools\.kpm\packages\Microsoft.Framework.Logging.NLog\1.0.0-rc1-10702
    File: lib\aspnet50\Microsoft.Framework.Logging.NLog.dll

  Using Package dependency Newtonsoft.Json 6.0.6
    Source: F:\tools\.kpm\packages\Newtonsoft.Json\6.0.6
    File: lib\net45\Newtonsoft.Json.dll

  Using Package dependency Microsoft.Framework.Logging.Interfaces 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Framework.Logging.Interfaces\1.0.0-beta1
    File: lib\aspnet50\Microsoft.Framework.Logging.Interfaces.dll

  Using Package dependency Microsoft.AspNet.Server.Kestrel 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Server.Kestrel.dll

  Using Package dependency Microsoft.AspNet.FeatureModel 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.FeatureModel\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.FeatureModel.dll

  Using Package dependency Microsoft.AspNet.Http 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Http\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Http.dll

  Using Package dependency Microsoft.AspNet.PipelineCore 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.PipelineCore\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.PipelineCore.dll

  Using Package dependency Microsoft.AspNet.RequestContainer 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.RequestContainer\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.RequestContainer.dll

  Using Package dependency Microsoft.AspNet.Security.DataProtection 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Security.DataProtection\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Security.DataProtection.dll

  Using Package dependency Microsoft.Framework.DependencyInjection 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Framework.DependencyInjection\1.0.0-beta1
    File: lib\aspnet50\Microsoft.Framework.DependencyInjection.dll

  Using Package dependency Microsoft.Framework.OptionsModel 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Framework.OptionsModel\1.0.0-beta1
    File: lib\aspnet50\Microsoft.Framework.OptionsModel.dll

  Using Package dependency Microsoft.AspNet.Mvc.Razor 6.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Mvc.Razor\6.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Mvc.Razor.dll

  Using Package dependency Microsoft.AspNet.FileSystems 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.FileSystems\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.FileSystems.dll

  Using Package dependency Microsoft.AspNet.Mvc.HeaderValueAbstractions 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Mvc.HeaderValueAbstractions\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Mvc.HeaderValueAbstractions.dll

  Using Package dependency Microsoft.AspNet.Mvc.ModelBinding 6.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Mvc.ModelBinding\6.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Mvc.ModelBinding.dll

  Using Package dependency Microsoft.AspNet.Security 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Security\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Security.dll

  Using Package dependency Microsoft.AspNet.WebUtilities 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.WebUtilities\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.WebUtilities.dll

  Using Package dependency Microsoft.Net.Http.Server 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Net.Http.Server\1.0.0-beta1
    File: lib\aspnet50\Microsoft.Net.Http.Server.dll

  Using Package dependency Microsoft.Net.WebSocketAbstractions 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Net.WebSocketAbstractions\1.0.0-beta1
    File: lib\net45\Microsoft.Net.WebSocketAbstractions.dll

  Using Package dependency Microsoft.AspNet.Http.Extensions 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Http.Extensions\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Http.Extensions.dll

  Using Package dependency Microsoft.AspNet.Identity.Core 1.0.0
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Identity.Core\1.0.0
    File: lib\net45\Microsoft.AspNet.Identity.Core.dll

  Using Package dependency mongocsharpdriver 1.8.3
    Source: F:\tools\.kpm\packages\mongocsharpdriver\1.8.3
    File: lib\net35\MongoDB.Bson.dll
    File: lib\net35\MongoDB.Driver.dll

  Using Package dependency NLog 3.1.0.0
    Source: F:\tools\.kpm\packages\NLog\3.1.0.0
    File: lib\net45\NLog.dll

  Using Package dependency Microsoft.Framework.Runtime.Interfaces 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Framework.Runtime.Interfaces\1.0.0-beta1
    File: lib\net45\Microsoft.Framework.Runtime.Interfaces.dll

  Using Package dependency Microsoft.AspNet.HttpFeature 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.HttpFeature\1.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.HttpFeature.dll

  Using Package dependency Microsoft.AspNet.Mvc.Razor.Host 6.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Mvc.Razor.Host\6.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Mvc.Razor.Host.dll

  Using Package dependency Microsoft.CodeAnalysis.CSharp 1.0.0-beta1-20141031-01
    Source: F:\tools\.kpm\packages\Microsoft.CodeAnalysis.CSharp\1.0.0-beta1-20141031-01
    File: lib\net45\Microsoft.CodeAnalysis.CSharp.Desktop.dll
    File: lib\net45\Microsoft.CodeAnalysis.CSharp.dll

  Using Package dependency Microsoft.DataAnnotations 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.DataAnnotations\1.0.0-beta1
    File: lib\net45\Microsoft.DataAnnotations.dll

  Using Package dependency Microsoft.Net.WebSockets 1.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.Net.WebSockets\1.0.0-beta1
    File: lib\net45\Microsoft.Net.WebSockets.dll

  Using Package dependency Microsoft.AspNet.Razor.Runtime 4.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Razor.Runtime\4.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Razor.Runtime.dll

  Using Package dependency Microsoft.CodeAnalysis.Common 1.0.0-beta1-20141031-01
    Source: F:\tools\.kpm\packages\Microsoft.CodeAnalysis.Common\1.0.0-beta1-20141031-01
    File: lib\net45\Microsoft.CodeAnalysis.Desktop.dll
    File: lib\net45\Microsoft.CodeAnalysis.dll

  Using Package dependency Microsoft.AspNet.Razor 4.0.0-beta1
    Source: F:\tools\.kpm\packages\Microsoft.AspNet.Razor\4.0.0-beta1
    File: lib\aspnet50\Microsoft.AspNet.Razor.dll

  Using Package dependency System.Collections.Immutable 1.1.32-beta
    Source: F:\tools\.kpm\packages\System.Collections.Immutable\1.1.32-beta
    File: lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll

  Using Package dependency System.Reflection.Metadata 1.0.17-beta
    Source: F:\tools\.kpm\packages\System.Reflection.Metadata\1.0.17-beta
    File: lib\portable-net45+win8\System.Reflection.Metadata.dll

  Using Assembly dependency gac/mscorlib 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll

  Using Assembly dependency gac/System 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

  Using Assembly dependency gac/System.Core 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

  Using Assembly dependency gac/Microsoft.CSharp 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll

  Using Assembly dependency gac/System.Security 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Security.dll

  Using Assembly dependency gac/System.Xml 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

  Using Assembly dependency gac/System.Xml.Linq 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll

  Using Assembly dependency gac/System.Collections 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll

  Using Assembly dependency gac/System.IO 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.IO\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.IO.dll

  Using Assembly dependency gac/System.Runtime 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

  Using Assembly dependency gac/System.Text.Encoding 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Text.Encoding\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Text.Encoding.dll

  Using Assembly dependency gac/System.Threading.Tasks 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Threading.Tasks\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Tasks.dll

  Using Assembly dependency gac/System.Runtime.Serialization 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll

  Using Assembly dependency gac/System.ComponentModel.DataAnnotations 4.0.0.0
    Source: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll

Mvc -> F:\apps\pcsc\GreenShelter\src\Mvc\bin\Debug\Mvc.1.0.0.0.nupkg
Mvc -> F:\apps\pcsc\GreenShelter\src\Mvc\bin\Debug\Mvc.1.0.0.0.symbols.nupkg

Build succeeded.
    0 Warnings(s)
    0 Error(s)

Time elapsed 00:00:03.8346217
info: Copying Mvc.1.0.0.0.nupkg
info: Copying Mvc.1.0.0.0.symbols.nupkg
info: Copying aspnet50\Mvc.dll
info: Copying aspnet50\Mvc.pdb
info: Copying aspnet50\Mvc.xml
info: Target native-compile
info: Target restore-npm-modules
info: Target restore-bower-components
info: Target run-grunt
info: Target clean-npm-modules
info: Target compile
info: Target test-compile
info: Target xunit-test
info: Exec
info:   program: cmd
info:   commandline: /C k test
info:   workingdir: test\Mvc
xUnit.net K Runtime Environment test runner (32-bit Asp.Net 5.0)
Copyright (C) 2014 Outercurve Foundation.

Discovering: Mvc
System.IO.FileLoadException: Could not load file or assembly 'Mvc' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
warn: Exit code 1 from cmd
verbose: Stack trace: 
   at View50c44a03f8d24ab1825aec504abf6652.K(String command, String workingdir, String kvmUse) in c:\Users\CTCPublic\AppData\Local\Temp\c6e3115201af4be3996f87fffc61bea9-1.cs:line 616
   at View50c44a03f8d24ab1825aec504abf6652.<RenderViewLevel0>b__49() in c:\Users\CTCPublic\AppData\Local\Temp\c6e3115201af4be3996f87fffc61bea9-1.cs:line 2590
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View50c44a03f8d24ab1825aec504abf6652.<RenderViewLevel0>b__39() in c:\Users\CTCPublic\AppData\Local\Temp\c6e3115201af4be3996f87fffc61bea9-1.cs:line 1307
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View50c44a03f8d24ab1825aec504abf6652.<RenderViewLevel0>b__31() in c:\Users\CTCPublic\AppData\Local\Temp\c6e3115201af4be3996f87fffc61bea9-1.cs:line 1163
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

Here's basic information about my project.

Greenshelter\
    \src
        \Mvc
              \bin
                    \Debug
                             Mvc.1.0.0.0.nupkg
                             \aspnet50
                                    Mvc.dll
              project.json
    \test
         \Mvc
              project.json
     global.json
  
global.json
```json
{
    "sources": ["src"]
}
```

\src\Mvc\project.json
```json
{
  "version": "1.0.0.0",
  "authors": [
    "Karega Scott - PCSC"
  ],
  
  "description": "Green Shelter Core Project",
  "compilationOptions": {
    "warningsAsErrors": true
  },
  "exclude": "*.bk",
  
  "dependencies": {
    "Microsoft.Framework.ConfigurationModel": "1.0.0-rc1-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-rc1-*",
	
    "Microsoft.Framework.Logging": "1.0.0-beta1",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta1",
	
    "Kestrel": "1.0.0-beta1",
	
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta1",
    "Microsoft.AspNet.Hosting": "1.0.0-beta1",
    "Microsoft.AspNet.Mvc": "6.0.0-beta1",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-beta1",
    "Microsoft.AspNet.Routing": "1.0.0-beta1",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta1",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta1",
	
	"Mongodb": "1.7.1.4791",
	"MongoDB.AspNet.Identity": "1.0.5",
  },
  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:8080",
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:8181",
  },
  "frameworks": {
    "aspnet50": {
      "dependencies": {
        "Microsoft.Framework.Logging.NLog": "1.0.0-*"
      }
    }
  },
  "configurations": {
    "Debug": {
      "compilationOptions": {
        "define": [
          "DEBUG",
          "TRACE"
        ]
      }
    },
    "Release": {
      "compilationOptions": {
        "define": [
          "RELEASE",
          "TRACE"
        ],
        "optimize": true
      }
    }
  }
}
```

\test\Mvc\project.json
```json
{
  "dependencies": {
    "Microsoft.Framework.ConfigurationModel": "1.0.0-rc1-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-rc1-*",
	
    "Microsoft.Framework.Logging": "1.0.0-beta1",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta1",

	"xunit.runner.kre": "1.0.0-*"	
  },
  
  "commands": {
	"xunit-test": "xunit.runner.kre",
    "test": "xunit.runner.kre"
  },
  
  "frameworks": {
    "aspnet50": {
      "dependencies": {
        "Microsoft.Framework.Logging.NLog": "1.0.0-*"
      }
    }
  }
}
```

**Comment by Praburaj** [comment]
@kscott5 Try including `"test"` in your `global.json` and see if that solves the problem. 

```
{
    "sources": [ "src", "test" ]
}
```

**Comment by kscott5** [comment]
I tried that as well but at this point somethings really wrong.

```powershell
PS F:\apps\pcsc\GreenShelter> .nuget\nuget.exe sources
Registered Sources:

  1.  https://www.nuget.org/api/v2/ [Enabled]
      https://www.nuget.org/api/v2/
PS F:\apps\pcsc\GreenShelter> .nuget\NuGet.exe install KoreBuild -ExcludeVersion
 -o packages -nocache
Unable to find package 'KoreBuild'.
PS F:\apps\pcsc\GreenShelter>
```

Here's a powershell script I run to configure my environment
```powershell

Clear-Host

$env:OS_IS_x64 = Read-Host "x64 OS Y/N (default=N)?" 
$env:STOP_CHROME = Read-Host "Stop Chrome Y/N (default=N)?"
$env:USE_ASPNET50_MASTER = Read-Host "Use ASP.NET 5.0 (master branch) for KRE Y/N (default=Y)?"
$env:USE_KRE_CORE_CLR = Read-Host "Use KRE Core CLR (ASP.NET 5) Y/N (default=Y)?"

Clear-Host

$env:OS_ARCH_TYPE = "x86"
if( $env:OS_IS_x64 -ne $null -and $env:OS_IS_x64.ToLower().Equals("y") ) {
    $env:OS_ARCH_TYPE = "x64"
}


if( $env:STOP_CHROME -ne $null -and $env:STOP_CHROME.ToLower().Equals("y") ) { 
    Stop-Process -name "chrome"
}

Clear-Host

$env:DEVDRIVE = (Get-Location).Drive.Root
$env:TOOLS_HOME = $env:DEVDRIVE + "tools"

$env:JAVA_HOME = $env:TOOLS_HOME + "\Java\" + $env:OS_ARCH_TYPE
$env:CLASSPATH = ".;" + $env:TOOLS_HOME + "\Java\classpath\apktool.jar;"

$env:ANDROID_STUDIO_HOME = $env:TOOLS_HOME + "\android\studio"
$env:ANDROID_HOME = $env:TOOLS_HOME + "\android\sdk\" + $env:OS_ARCH_TYPE

$env:ECLIPSE_HOME = $env:TOOLS_HOME + "\android\adt\" + $env:OS_ARCH_TYPE + "\eclipse"
$env:GRADLE_HOME = $env:TOOLS_HOME + "\gradle\1.10"

$env:KRE_HOME = $env:TOOLS_HOME + "\.kre"
$env:KPM_HOME = $env:TOOLS_HOME + "\.kpm"
$env:KRE_ENV = "Development"

# Remove-Item $env:KRE_HOME -recurse -force
# Remove-Item $env:KPM_HOME -recurse -force

if( $env:USE_ASPNET50_MASTER -eq $null -or $env:USE_ASPNET50_MASTER.ToLower().Equals("y") ) {
    Write-Host "Using ASP.NET 5.0 MASTER Branch"
    $env:KRE_NUGET_API_URL = "https://www.myget.org/F/aspnetmaster/api/v2"
    $env:KRE_FEED = "https://www.myget.org/F/aspnetmaster/api/v2"
    
    $env:KRE_Branch = "master"
} else {
    Write-Host "Using ASP.NET 5.0 Dev (vNext) Branch"
    $env:KRE_NUGET_API_URL = "https://www.myget.org/F/aspnetvnext/api/v2"
    $env:KRE_FEED = "https://www.myget.org/F/aspnetvnext/api/v2"
    
    $env:KRE_Branch = "dev"
}

$env:Path = $env:Path + ";" + $env:DEVDRIVE + "apps\aspnet\" + $env:KRE_Branch + "\kvm\src;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\MongoVUE\1.6.9;"
$env:Path = $env:Path + $env:GRADLE_HOME + "\bin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\miscellaneous;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\nodeJS\" + $env:OS_ARCH_TYPE + ";"
$env:Path = $env:Path + $env:TOOLS_HOME + "\mongoDB\bin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\7-zip;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\Cygwin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\Chrome;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\DevKit\32bit\bin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\DevKit\32bit\mingw\bin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\Git;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\Git\bin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\ILSpy;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\jZip;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\SharpDevelop4.1\bin;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\notepad++;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\Ruby200\bin;"
$env:Path = $env:Path + $env:JAVA_HOME + "\bin;"
$env:Path = $env:Path + $env:ANDROID_STUDIO_HOME + "\bin;"
$env:Path = $env:Path + $env:ANDROID_HOME + ";"
$env:Path = $env:Path + $env:ANDROID_HOME + "\tools;"
$env:Path = $env:Path + $env:ANDROID_HOME + "\platform-tools;"
$env:Path = $env:Path + $env:ECLIPSE_HOME + ";"
$env:Path = $env:Path + $env:TOOLS_HOME + "\sqlite;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\Fiddler2\DotNet2;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\winmerge;"
$env:Path = $env:Path + $env:TOOLS_HOME + "\scripts;"

$env:USERPROFILE = $env:TOOLS_HOME
$env:APPDATA = $env:USERPROFILE + "\AppData"
$env:LocalAppData = $env:USERPROFILE + "\AppData"

Set-Location "\apps"

$nugetFile = "<?xml version=`"1.0`" encoding=`"utf-8`"?>`n" +
"<configuration>`n" +
"`t<packageSources>`n" +
"`t`t<add key=`"NuGet.org`" value=`"https://www.nuget.org/api/v2/`" />`n" +
"`t`t<add key=`"AspNetVNext' value=`""+ $env:KRE_NUGET_API_URL+ "`" />`n" +
"`t</packageSources>`n" +
"</configuration>`n"

$nugetFile > ($env:APPDATA + "\Nuget\Nuget.config")

# Beging appending to Path environment variable
if( $env:USE_KRE_CORE_CLR -ne $null -and $env:USE_KRE_CORE_CLR.ToLower().Equals("y") ) {
    Write-Host "kvm install latest -a core -x86 -r CoreCLR -f"
    kvm install latest -a core -x86 -r CoreCLR -f
} else {
    Write-Host "kvm install latest -a default -x86 -r CLR -f"
    kvm install latest -a default -x86 -r CLR -f
}


Read-Host "Press any key to continue!"

Start-Process Powershell
```

![script_output](https://cloud.githubusercontent.com/assets/132991/5732711/f641a4bc-9b53-11e4-8b04-c5f0db049144.png)

Now I've started completely over and still having issues

**Comment by davidfowl** [comment]
Please reopen if the issue persists with the latest builds. Also use https://github.com/xunit/dnx.xunit
