### ISSUE TITLE
PropertyHelper SetValue method not support value type

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2767]
_From @tangdf on Wednesday, January 10, 2018 4:32:28 PM_

 
```cs
        [Fact]
        public void PropertyHelper_SetValueForStruct()
        {
            // Arrange
            var anonymous = new MyProperties();

            var helper = PropertyHelper.GetProperties(anonymous.GetType().GetTypeInfo()).Where(prop => prop.Name == "IntProp").Single();

            // Act
            helper.SetValue(anonymous, 3);

            Assert.Equal(3, anonymous.IntProp);
        }

        private struct MyProperties
        {
            public int IntProp { get; set; }
            public string StringProp { get; set; }
        }
```

> System.ArgumentException : Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at Microsoft.Extensions.Internal.PropertyHelper.MakeFastPropertySetter(PropertyInfo propertyInfo) in shared\Microsoft.Extensions.PropertyHelper.Sources\PropertyHelper.cs:line 310
   at Microsoft.Extensions.Internal.PropertyHelper.get_ValueSetter() in shared\Microsoft.Extensions.PropertyHelper.Sources\PropertyHelper.cs:line 91
   at Microsoft.Extensions.Internal.PropertyHelper.SetValue(Object instance, Object value) in shared\Microsoft.Extensions.PropertyHelper.Sources\PropertyHelper.cs:line 117
   at Microsoft.Extensions.Internal.PropertyHelperTest.PropertyHelper_SetValueForStruct() in  test\Microsoft.Extensions.Internal.Test\PropertyHelperTest.cs:line 225

_Copied from original issue: aspnet/Common#307_

**Comment by Eilon** [comment]
Hi @tangdf, I don't think this method is meant to work with all property types. It's just an internal piece of infrastructure code used in some limited scenarios.

Did you run into this while using ASP.NET Core? If so, what was the scenario?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
