### ISSUE TITLE
Microsoft.NET.Sdk with Razor support

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#2809]
_From @bgever on August 10, 2017 9:55_

I'm trying to get Razor syntax support for Visual Studio 2017 in a `Microsoft.NET.Sdk` library, which is dynamically loaded into a `Microsoft.NET.Sdk.Web` project.

I've noticed that when I change the library to the Web SDK, .cshtml files get proper support for Razor code, so that I can access `@Html` or `@Context` with IntelliSense, and reports no longer errors (red squiggles).

However, with that SDK I have to add an app entry point, and the output is an EXE. Moreover, when loading the library as an Application Part in MVC, similar to https://github.com/dotnet/sdk/issues/1213, then I get the below exception.

```
System.InvalidOperationException: Can not find compilation library location for package 'quantifeed.webapp.cub'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
```

Is there a way to get Razor support in VS 2017 with a `Microsoft.NET.Sdk`  SDK?

_Copied from original issue: dotnet/sdk#1481_

**Comment by livarcocc** [comment]
I am not aware of it, however, I will move this issue to the aspnet repo, where they might be able to provide some guidance.

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/Razor/issues/1951.
