### ISSUE TITLE
UseDatabaseErrorPage throws NullReferenceException when ef exception occur in background task

### ISSUE THREAD

**Issue by andrewjsaid** [aspnet/Home#2820]
### Functional impact
The original exception thrown by EF is lost and replaced by a NullReferenceException, losing all useful information and muddling debugging.

### Minimal repro steps
1. Create a project with EF and `UseDatabaseErrorPage()`
2. Add an implementation of IHostedService which makes an EF call with the expectation of throwing. For example, server is offline.
3. Run the project and inspect the exception

### Expected result
An exception similar to: `System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: 'No connection could be made because the target machine actively refused it 127.0.0.1:5432'`

### Actual result
An exception in the Diagnostics middleware
<pre>
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 keyValuePair)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.QueryIterationFailed(IDiagnosticsLogger`1 diagnostics, Type contextType, Exception exception)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
</pre>

### Further technical details
It's pretty clear that the error is that `DatabaseErrorPageMiddleware` contains an `AsyncLocal<DiagnosticHolder>` which is always assumed to hold a value. I think that checking whether `localDiagnostic.Value` is null and avoiding the call should be sufficient. Possibly even just doing `?.` (null-safe) calls instead of regular `.` calls in the `OnNext` method.

I also expect the same failure to happen if a database exception happens in an earlier middleware, before the `AsyncLocal.Value` is set. However I have not tested this and I also find the situation somewhat unlikely.

**Comment by Tratcher** [comment]
IHostingService? Did you mean IHostedService? UseDatabaseErrorPage shouldn't apply to an IHostedService.

**Comment by andrewjsaid** [comment]
Excuse me! I did mean IHostedService.

**Comment by muratg** [comment]
cc @ajcvickers

**Comment by ajcvickers** [comment]
Looks like it could be a dup of https://github.com/aspnet/EntityFrameworkCore/issues/9599
/cc @anpete
