### ISSUE TITLE
Failed to bind to address http://localhost:49980.

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#2821]
_From @Erave on January 24, 2018 11:43_

Yesterday, I have installed a major Windows Update and today I can't run my Asp.NET Core web app. I have a permission access problem dureing binding

Not existing process is listening on port 49980. I tried to stop firewall.
Do you see any reason to this exception ?

Thanks
Eric

```
System.IO.IOException: Failed to bind to address http://localhost:49980. ---> System.AggregateException: One or more errors occurred. (Error -4092 EACCES permission denied) (Error -4092 EACCES permission denied) ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4092 EACCES permission denied
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.Bind(IPEndPoint endPoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.ListenTcp(Boolean useFileHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.<>c.<StartAsync>b__8_0(Listener listener)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.CallbackAdapter`1.<>c.<.cctor>b__3_1(Object callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.DoPostWork()






```

_Copied from original issue: dotnet/cli#8462_

**Comment by Tratcher** [comment]
Is it only that port? Does it work if you try a few random other ones?

**Comment by muratg** [comment]
What's the output of `netstat -a -b` when you get this exception?

**Comment by Eilon** [comment]
This issue was moved to aspnet/KestrelHttpServer#2277

**Comment by 82lijinliang** [comment]
HTTP(S)代理服务器：127.0.0.1:49981     china    no
