### ISSUE TITLE
Broken tests on ASPNETCI-A-116: EnsureCreateHttpsCertificate_CreatesACertificate_WhenThereAreNoHttpsCertificates

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#2866]
aspnetci-a-116 is currently disabled because it fails the certificate tests. @javiercn will investigate and re-enable when he's fixed it.

**Comment by mikeharder** [comment]
I re-enabled the agent for now to give us more capacity.  @javiercn will disable when he's ready to investigate.

**Comment by ryanbrandenburg** [comment]
More details on the offending errors here:
```
======= Failed test run #1 ==========
System.InvalidOperationException : Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.RemoveCertificateFromTrustedRoots(X509Certificate2 certificate) in C:\b\w\447b43a298ac237f\shared\Microsoft.AspNetCore.Certificates.Generation.Sources\CertificateManager.cs:line 502
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.RemoveCertificate(X509Certificate2 certificate, RemoveLocations locations) in C:\b\w\447b43a298ac237f\shared\Microsoft.AspNetCore.Certificates.Generation.Sources\CertificateManager.cs:line 477
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.RemoveAllCertificates(CertificatePurpose purpose, StoreName storeName, StoreLocation storeLocation, String subject) in C:\b\w\447b43a298ac237f\shared\Microsoft.AspNetCore.Certificates.Generation.Sources\CertificateManager.cs:line 449
   at Microsoft.AspNetCore.Certificates.Generation.Tests.CertificateManagerTests.EnsureCreateHttpsCertificate_CreatesACertificate_WhenThereAreNoHttpsCertificates() in C:\b\w\447b43a298ac237f\test\Microsoft.Extensions.Internal.Test\CertificateManagerTests.cs:line 35
```
An [example](http://aspnetci/project.html?projectId=AspNetEf&buildTypeId=&tab=testDetails&testNameId=-2621883684559447801&order=AGENT_ASC&branch_AspNetEf=__all_branches__&itemsCount=50).

Future instances of this error should show up in [this](http://aspnetci/httpAuth/app/rest/builds?locator=tag:CertificateSequence,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) list.

This seems confined to ASPNETCI-A-116, but we should better understand why this is happening and how it might affect customers.

**Comment by javiercn** [comment]
I tried this on the agent by running the tests in a loop for 100 iterations and I coudn't repro it. I've added more logging to capture some diagnostic information if the test fails another time. https://github.com/aspnet/Common/pull/329

I don't think there's any more action to take here for preview2

**Comment by mkArtakMSFT** [comment]
@javiercn has added additional logging so we can get more details in the next failure (if there will be such). Moving to the `rc` milestone to give it more time to show up. If not, we'll close it then.

**Comment by ryanbrandenburg** [comment]
This no longer repros on 116. Either we fixed the issue or the state on 116 changed. Either way, without a way to repro I'm closing it out.
