### ISSUE TITLE
PersistKeysToFileSystem in Docker hosted in Linux fails with "Unknown error 524"

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Home#2941]
@joetherod commented on [Thu Mar 08 2018](https://github.com/aspnet/Hosting/issues/1343)

Trying to AddDataProtection for MVC Core app.
services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("etc/keys/"))
                .SetApplicationName("AppName")

The Directory is a configured volume mount in the linux host.
If I dont use the volume mount, it works.
Volume mount is needed as per described in MS Docs since the app is hosted in many Docker containers.
Please advise.

Works locally. But when configured to a Docker container hosted in linux, I get the following exception on startup:

{"Timestamp":"2018-03-08T20:45:37.4873753+00:00","Level":"Error","MessageTemplate":"An error occurred while reading the key ring.","Exception":"System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)","Properties":{"EventId":{"Id":48},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider","RequestId":"0HLC55SODK05P:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC55SODK05P"}}

---

@Tratcher commented on [Thu Mar 08 2018](https://github.com/aspnet/Hosting/issues/1343#issuecomment-371634771)

@natemcmaster 

---

@natemcmaster commented on [Thu Mar 08 2018](https://github.com/aspnet/Hosting/issues/1343#issuecomment-371636962)

This appears to be an issue with your Docker host, not with ASP.NET Core. System.IO.File.Move is failing to write into the mounted directory. Can you verify this with a minimal repro like this?
```c#
public static void Main(string[] args)
{
    var tempFile = Path.Combine(Path.GetTempPath(), "test.txt");
    File.WriteAllText(tempFile, "Hello");
    File.Move(tempFile, "etc/keys/test.txt");
}
```

---

@joetherod commented on [Thu Mar 08 2018](https://github.com/aspnet/Hosting/issues/1343#issuecomment-371659784)

Write and move works, but still getting exception.

An error occurred while reading the key ring.","Exception":"System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)","Properties":{"EventId":{"Id":48},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider","RequestId":"0HLC597NS53I0:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC597NS53I0"}}

An unhandled exception was thrown by the application.","Exception":"System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   --- End of inner exception stack trace ---\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   at Microsoft.AspNetCore.Session.CookieProtection.Protect(IDataProtector protector, String data)\n   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()","Properties":{"ConnectionId":"0HLC597NS53I0","TraceIdentifier":"0HLC597NS53I0:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HLC597NS53I0:00000001","RequestPath":"/_health","CorrelationId":null}}

---

@natemcmaster commented on [Thu Mar 08 2018](https://github.com/aspnet/Hosting/issues/1343#issuecomment-371661817)

Can you provide more log info? There should be an INFO log item just before this File.Move

https://github.com/aspnet/DataProtection/blob/8a42c24f46d728b4728e6b20febd0a11c1111df2/src/Microsoft.AspNetCore.DataProtection/Repositories/FileSystemXmlRepository.cs#L232-L233

---

@joetherod commented on [Thu Mar 08 2018](https://github.com/aspnet/Hosting/issues/1343#issuecomment-371685069)

 services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("etc/talentbrew/keys"))
                .SetApplicationName("XXX")
                .SetDefaultKeyLifetime(TimeSpan.FromDays(365));

Level":"Information","MessageTemplate":"Writing data to file '{FileName}'.","Properties":{"FileName":"/app/etc/talentbrew/keys/key-fb6f8187-5606-445b-9591-3c268c59ff84.xml","EventId":{"Id":39},"SourceContext":"Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC5BJ5EVUU9"}

"Level":"Error","MessageTemplate":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","Exception":"System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   --- End of inner exception stack trace ---\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   at Microsoft.AspNetCore.Session.CookieProtection.Protect(IDataProtector protector, String data)\n   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()","Properties":{"ConnectionId":"0HLC5BJ5EVUU9","TraceIdentifier":"0HLC5BJ5EVUU9:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null}}

"Level":"Information","MessageTemplate":"Creating key {KeyId:B} with creation date {CreationDate:u}, activation date {ActivationDate:u}, and expiration date {ExpirationDate:u}.","Properties":{"KeyId":"fb6f8187-5606-445b-9591-3c268c59ff84","CreationDate":"2018-03-09T01:33:27.3851082+00:00","ActivationDate":"2018-03-09T01:33:27.3843013+00:00","ExpirationDate":"2019-03-09T01:33:27.3843013+00:00","EventId":{"Id":58},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC5BJ5EVUU9"},"Renderings":{"KeyId":[{"Format":"B","Rendering":"{fb6f8187-5606-445b-9591-3c268c59ff84}"}],"CreationDate":[{"Format":"u","Rendering":"2018-03-09 01:33:27Z"}],"ActivationDate":[{"Format":"u","Rendering":"2018-03-09 01:33:27Z"}],"ExpirationDate":[{"Format":"u","Rendering":"2019-03-09 01:33:27Z"}]}}

Level":"Error","MessageTemplate":"An error occurred while reading the key ring.","Exception":"System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)","Properties":{"EventId":{"Id":48},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC5BJ5EVUU9"}}

**Comment by natemcmaster** [comment]
@joetherod it doesn't look like this is an issue in the hosting layer of the application, so I've moved it here.

Can you also provide information about how you've started your docker container? I suspect this issue might be caused by Windows permissions and Docker for Windows. This has often been a problem that causes odd issues like this.

**Comment by joetherod** [comment]
job "dotnet-clientapp" {
  datacenters = ["datacenter"]
  type = "service"
  group "Dotnet.clientapp" {
    count = 2 
    update {
      max_parallel      = 1
      health_check      = "checks"
      min_healthy_time  = "10s"
      healthy_deadline  = "5m"
      auto_revert       = false
      canary            = 0
      stagger           = "120s"  
    }

    task "dotnet-clientapp" {
      driver = "docker"
      kill_timeout = "60s"
      env {
        "ASPNETCORE_ENVIRONMENT" = "Dev",
      }
      config {
        image = "hosted.docker.host/dotnet-clientapp:Jenkins.$BUILD_ID"
        logging {
          type = "syslog"
          config {
            syslog-address = "",
            tag = "dotnet-clientapp",
            tag = "docker:{{ (.ExtraAttributes nil).service }}"
          }
        }
        labels {
          service = "dotnet-clientapp",
          version = "Jenkins.$BUILD_ID",
          traefik.domain = "www.blank.com"
        }
        volumes = [
          "/etc/hosts:/etc/hosts",
          "/app/nfs4/share:/app/etc/clientapp/keys"
        ]

        port_map {
          http = 80
        }
        

        network_mode = "overlay-driver"
      }
      resources {
        cpu    = 500 # 500 MHz
        memory = 1024 # 256MB
        network {
          mbits = 100
          port "http" {}
        }
      }
      # By default services will advertise the weave address
      service {
        name = "dotnet-clientapp"
        tags = ["dotnet-clientapp"]
        port = "http"
        # Since checks are done by Consul on the host system, they default to
        # the host IP:Port.
        address_mode = "driver"

        check {
          name     = "host-alive"
          type     = "tcp"
          interval = "1s"
          timeout  = "3s"
        }
        
        check {
          name     = "health-check"
          type     = "http"
          path     = "/_health"
          interval = "2s"
          timeout  = "4s"
        }
        
        check {
          name     = "prime site"
          type     = "http"
          port     = "http"
          path     = "/"
          interval = "10s"
          timeout  = "120s"
          header {
             Host = ["www.blank.com"]
          }
        }
        
        check {
          name     = "prime site"
          type     = "http"
          port     = "http"
          path     = "/prime"
          interval = "10s"
          timeout  = "300s"
          header {
             Host = ["www.blank.com"]
          }
        }
      }
      # Setting address_mode = "host" will create a service entry with the
      # host's address.
      service {
        name = "host-dotnet-clientapp"
        tags = ["dotnet-clientapp", "host-addr"]
        port = "http"
		# default for address_mode is host but specify here to be clear
        address_mode = "host"
      }
    }
  }
}

**Comment by joetherod** [comment]
FROM microsoft/aspnetcore:2.0

WORKDIR /app

COPY . /app

## Set to SIGTERM to gracefully clean up connections and processes
STOPSIGNAL SIGTERM
EXPOSE 80

RUN \
  DUMB_INIT_VERSION=1.2.1 && \
  DUMB_INIT_SHA256SUM=057ecd4ac1d3c3be31f82fc0848bf77b1326a975b4f8423fe31607205a0fe945 && \
  curl -fsSLo /sbin/dumb-init "https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_amd64" && \
  echo "${DUMB_INIT_SHA256SUM} */sbin/dumb-init" | sha256sum -c - && \
  chmod +x /sbin/dumb-init

RUN mkdir -p /app/etc/talentbrew/keys

ENTRYPOINT [ "/sbin/dumb-init", "--" ]
CMD ["dotnet", "Tmp.Dotnet.Client.App.dll"]

**Comment by mywebpower** [comment]
Just to add some background on the issue.  The containers are scheduled using Hashicorp Nomad.  The keys directory is a NFS share on the Docker Host.  The Docker Host is running Centos 7.4.  The volume is visible and writable inside the container.  The process currently runs as root in order to test.

**Comment by natemcmaster** [comment]
I don't see anything obvious in the setup that would lead to this error.

Does it repro if you run this code?
```csharp
public static void Main(string[] args)
{
    var tempFile = Path.Combine(Path.GetTempPath(), "test.tmp");
    File.WriteAllText(tempFile, "<keys></keys>");
    Directory.CreateDirectory("/app/etc/talentbrew/keys/");
    File.Move(tempFile, "/app/etc/talentbrew/keys/key-fb6f8187-5606-445b-9591-3c268c59ff84.xml");
}
```

FYI - the code that is throwing isn't doing anything special with file permissions: https://github.com/aspnet/DataProtection/blob/2.0.1/src/Microsoft.AspNetCore.DataProtection/Repositories/FileSystemXmlRepository.cs#L213-L239

**Comment by joetherod** [comment]
@natemcmaster tried your test and it works fine with no exceptions. Could it be because the file location is different from the default location?

**Comment by natemcmaster** [comment]
Unlikely. I picked that file path from your logging output above. The stack trace is this:
```
System.IO.IOException: Unknown error 524
 at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
 at System.IO.File.Move(String sourceFileName, String destFileName)
 at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)
```

@stephentoub any ideas how to figure out what error 524 might mean for a File.Move call?

**Comment by stephentoub** [comment]
This is the error that comes back from libc for errno 524, as can be seen with:
```C
#include <stdio.h>
#include <errno.h>

int main(int argc, char** argv)
{
    errno = 524;
    perror("");
    return 0;
}
```
I've not seen this errno value before, though, and don't know what it means.  Searching around the net, some sites suggest it's ENOSUPP, but I'm not sure in what circumstances this would happen.

**Comment by natemcmaster** [comment]
> The keys directory is a NFS share on the Docker Host.

This is the only clue I have to offer.

@joetherod @mywebpower - to reproduce this in isolation from aspnetcore, can you try testing some other `File.Move` actions? Large files, concurrent writes, `File.Move` if the file already exists, writing a bunch of files in a blast, setting a file watcher on the directory, etc. The `File.Move` action from `FileSystemXmlRepository` may not be the issue. For example, there may be issues writing to the NFS share from multiple threads at the same time.

**Comment by joetherod** [comment]
We are going to use redis to store the keys. Unfortunately there is no resolution to this issue. The key store location needs to be accessed by many containers.
Thanks!

**Comment by blowdart** [comment]
As you have a way forward @joetherod and the problem appears to be in .NET Core, I'm going to close the issue as External. @stephentoub I'll leave investigation up to you now.

**Comment by stephentoub** [comment]
> I'll leave investigation up to you now.

I'm not planning to investigate anything.

**Comment by natemcmaster** [comment]
@joetherod if you can find a way to reproduce issues with writing to a NFS share on your Docker host, can you share? We don't have enough info to investigate any more.

**Comment by jhudsoncedaron** [comment]
Well I found out what 524 is and I think some screw is lose.

https://github.com/spotify/linux/blob/master/include/linux/errno.h

**Comment by jhudsoncedaron** [comment]
Update: turns out this bug is a real bug in .NET Core. It tried to call MoveFile() which turned into link() on a filesystem that doesn't support hard links. The documentation suggests it should fall back on a copy file operation but failed to decode. 524 is ENOTSUPP which needs to be added to the ladder near line 101 in https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs

**Comment by jhudsoncedaron** [comment]
So here's the calling code:
                // Once the file has been fully written, perform the rename.
                // Renames are atomic operations on the file systems we support.
                _logger?.WritingDataToFile(finalFilename);
File.Move(tempFilename, finalFilename);

I'm not sure you want to do that. This will fail to be atomic on Windows when pointing at a NAS (for failover cluster support) as well as this case here.

**Comment by joetherod** [comment]
@jhudsoncedaron  Thanks for looking into this. Hopefully, it can be fixed soon.

**Comment by natemcmaster** [comment]
Thanks @jhudsoncedaron. Given that there isn't a FileSystem.MoveClobber API in .NET Core, what would you recommend instead?

https://github.com/aspnet/DataProtection/blob/2.0.1/src/Microsoft.AspNetCore.DataProtection/Repositories/FileSystemXmlRepository.cs#L233

At the moment, it's still not clear to me if this is a bug in File.Move or something we should change in aspnetcore.

**Comment by jhudsoncedaron** [comment]
You would replace that `File.Move` with
    if (Windows) WindowsNativeMethods.MoveFileEx(tempFilename, finalFilename, WindowsNativeMethods.MOVEFILE_REPLACE_EXISTING) else UnixNativeMethods.rename(tempFilename, finalFilename);

I checked the expectations of this call already, it does the right thing.

Given the sheer number of times this has come up in my code alone, making a File.MoveClobber that does exactly that P/Invoke is attractive. Written like this, it would never attempt a copy, which is probably a good thing.

**Comment by natemcmaster** [comment]
Thanks for the additional info. I'll re-open this so we can take another look. It my be reasonable for us to add some retries or fallbacks when File.Move fails.

**Comment by natemcmaster** [comment]
@blowdart @Eilon - marking for re-triage. We may be able to fix this issue with a few minor changes to DataProtection.

**Comment by Eilon** [comment]
Let's do the solution you suggested:

> We could fix this with a retry/fallback that does File.Copy + File.Delete instead.

And let's be careful about the retry logic (e.g. make sure it has reasonable limits and isn't infinite).

**Comment by joetherod** [comment]
Thanks. When we update to that version, we will try this out again. We went to using Redis for now to store keys.
