### ISSUE TITLE
Flaky tests: ConfigurationTests.CreatingWritingDeletingCreatingFileWillReload ConfigurationTests.TouchingFileWillReload

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#2991]
These tests have recently taken to failing on OSx: http://aspnetci/project.html?projectId=XPlat&buildTypeId=XPlat_Mac_MacUniverseCoreCLR&tab=testDetails&testNameId=3759396832575739260&order=START_DATE_DESC&branch_XPlat=__all_branches__&itemsCount=50

Offending tests include:

- ConfigurationTests.CreatingWritingDeletingCreatingFileWillReload
- ConfigurationTests.TouchingFileWillReload
```
Assert.Equal() Failure
                   ↓ (pos 9)
Expected: JsonValue2
Actual:   JsonValue1
                   ↑ (pos 9)
   at Microsoft.Extensions.Configuration.Test.ConfigurationTests.<TouchingFileWillReload>d__32.MoveNext() in /_/test/Config.FunctionalTests/ConfigurationTests.cs:line 598
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

A non-exhaustive list of the builds affected by this can be found here.

Split off from aspnet/DotNetTools#412.

**Comment by natemcmaster** [comment]
No recent test failures.
