### ISSUE TITLE
Debug type set to None throws InvalidOperationException (VS 15.7 Preview 2, IIS Express , ASP.NET Core MVC 2.1)

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/Home#2994]
When starting an ASP.NET Core MVC 2.1 (preview 1) application (default MVC project) -- via Visual Studio 15.7 Preview 2 => IIS Express --, and **debug type** is set to **none**, the following exception is thrown.

```
System.InvalidOperationException: The debug type specified in the dependency context could be parsed. The debug type value 'none' is not supported.
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CSharpCompiler.GetEmitOptions(CompilationOptions dependencyContextOptions)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CSharpCompiler.EnsureOptions()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CSharpCompiler.get_ParseOptions()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CSharpCompiler.CreateSyntaxTree(SourceText sourceText)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCompilation(String compilationContent, String assemblyName)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.<ExecuteAsync>d__6.MoveNext()
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__27`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__25.MoveNext()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

```

**Comment by rockerinthelocker** [comment]
As per https://github.com/aspnet/Mvc/commit/3517ecda2f7eee421159d4e3206f937264f5b56b, this should be fixed. Is this fix not part of .NET Core 2.1 Preview 1?

**Comment by rynowak** [comment]
This is not in preview1. This is the code as-of the preview1 tag https://github.com/aspnet/Mvc/blob/4921bcf7b4b581e178395993fa501f7dd6aac497/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CSharpCompiler.cs

**Comment by rockerinthelocker** [comment]
Thanks @rynowak for the quick response! Closing this now.
