### ISSUE TITLE
DataProtection - encryption with high-protected capi certificate

### ISSUE THREAD

**Issue by marian-margeta** [aspnet/Home#2997]
I have a problem with DataProtection when is used together with `ProtectKeysWithCertificate` to protect the data at rest. If I create highProtected certificate with CryptoAPI, e.g. using `New-SelfSignedCertificate` powershell cmdlet

```
New-SelfSignedCertificate `
         -Subject localhost `
         -DnsName localhost `
         -FriendlyName "ASP.NET Data Protection`
         -NotBefore (Get-Date) `
         -NotAfter (Get-Date).AddYears(10) `
         -CertStoreLocation "cert:CurrentUser\My" `
         -KeyAlgorithm RSA `
         -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" `
         -KeyLength 2048 `
         -KeyUsage KeyEncipherment, DataEncipherment `
         -KeyProtection ProtectHigh
```

then the certificate is protected with additional password. Windows will ask for it every time the application is started. It shows modal window like that (in Slovak lang):

![image](https://user-images.githubusercontent.com/6164767/37865531-1f27fa18-2f7e-11e8-8fc1-ef794bfd3d60.png)

If I type correct password, everything is good. However, when I type wrong password for the first time, and then correct one, DataProtection generates new master key, whereas the old one is still active (not expired or revoked). The application don't start until the correct password to the cert is given, but it nevertheless uses newly-generated key. Is there any way how to suppress this behavior? If I use method `DisableAutomaticKeyGeneration`, it also disables the key rotation.

Btw, the log printed to console every time the incorrect password is given:

```
fail: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[24]
      An exception occurred while processing the key element '<key id="bc5319fd-63a4-45f2-b75e-1ef181f6ec19" version="1" />'.
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access denied
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, Byte[] input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, EncryptOrDecryptAction encryptOrDecrypt)
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, EncryptOrDecryptAction encryptOrDecrypt)
   at System.Security.Cryptography.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding)
   at System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange(Byte[] rgbIn)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptKey(Byte[] keyData, RSA rsa, Boolean useOAEP)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey)
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[12]
      Key {bc5319fd-63a4-45f2-b75e-1ef181f6ec19} is ineligible to be the default key because its CreateEncryptor method failed.
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access denied
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, Byte[] input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, EncryptOrDecryptAction encryptOrDecrypt)
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, EncryptOrDecryptAction encryptOrDecrypt)
   at System.Security.Cryptography.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding)
   at System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange(Byte[] rgbIn)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptKey(Byte[] keyData, RSA rsa, Boolean useOAEP)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey)
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver.CanCreateAuthenticatedEncryptor(IKey key)
```

**Comment by blowdart** [comment]
Why would you want a dialog to appear on a web server? We weren't expecting anyone to use `-KeyProtection ProtectHigh` and it's not something we'd support.

**Comment by marian-margeta** [comment]
As I understood, protection with certificate is one of the way how to protect the data at rest. I know that certificates using CAPI are encrypted with DPAPI, but sometimes it would be reasonable to use additional password along with windows credentials. And such password should be typed right from the admin user, so the dialog is needed. Hard-coded password doesn't make any sense for protection data at rest, e.g. in this way 

```csharp

services.AddDataProtection()
     .ProtectKeysWithCertificate(new X509Certificate2("cert.pfx", "secretPassword"));
```

**Comment by blowdart** [comment]
But this is meant for a web application. You would have to logon interactively to the server and type in a password when the application starts for the first time, it really makes no sense. No-one is asking you to hard code a password, you can put the certificate in the certificate store and retrieve it that way.

**Comment by blowdart** [comment]
Closing as this isn't an expected or supported scenario.

**Comment by marian-margeta** [comment]
But when I put the certificate **with password** in the cert storage, I will end up with the problem described above. So if this won't be supported, if I store my certs in windows storage, the protection of the data at rest can be based only on user's password, i.e. DPAPI? I'd like to protect the data in case of physical theft on non-encrypted HDD.
