### ISSUE TITLE
Flaky test: System_NoKeysDirectoryProvided_UsesDefaultKeysDirectory

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#3034]
This test [fails](http://aspnetci/viewLog.html?buildId=442272&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId1329483692832033125) sometimes with the following error:

```
System.IO.IOException : Cannot create 'C:\Users\asplab\AppData\Local\ASP.NET\DataProtection-Keys' because a file or directory with the same name already exists.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_NoKeysDirectoryProvided_UsesDefaultKeysDirectory() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\DataProtection\test\Microsoft.AspNetCore.DataProtection.Extensions.Test\DataProtectionProviderTests.cs:line 89
======= Failed test run #2 ==========
System.IO.IOException : Cannot create 'C:\Users\asplab\AppData\Local\ASP.NET\DataProtection-KeysTemp' because a file or directory with the same name already exists.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_NoKeysDirectoryProvided_UsesDefaultKeysDirectory() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\DataProtection\test\Microsoft.AspNetCore.DataProtection.Extensions.Test\DataProtectionProviderTests.cs:line 55
```

Future instances of this failure can be tracked [here](http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=1329483692832033125&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50).

**Comment by Eilon** [comment]
@muratg / @natemcmaster - can you take a look?

**Comment by natemcmaster** [comment]
sure, i have a hunch it's just some tests running in parallel that shouldn't.

**Comment by ryanbrandenburg** [comment]
This is [still happening](http://aspnetci/viewLog.html?buildId=456871&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe), though with a slightly different error:

```
System.IO.IOException : Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_NoKeysDirectoryProvided_UsesDefaultKeysDirectory()
```

**Comment by ryanbrandenburg** [comment]
This is [still happening](http://aspnetci/viewLog.html?buildId=498335&buildTypeId=Releases_21Public_Win2012):

```
System.IO.IOException : Cannot create a file when that file already exists
   at System.IO.Win32FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_NoKeysDirectoryProvided_UsesDefaultKeysDirectory() in /_/test/Microsoft.AspNetCore.DataProtection.Extensions.Test/DataProtectionProviderTests.cs:line 89
```

**Comment by natemcmaster** [comment]
This was fixed in the release/2.2 branch, but wasn't backported to release/2.1.  @muratg what's the thinking on backporting fixes to flaky tests if they require substantial changes such as https://github.com/aspnet/DataProtection/pull/306?

**Comment by muratg** [comment]
I think we should consider these on a case-by-case basis looking at both the cost and the benefit.  release/2.1 is the LTS branch so we should take that into consideration. 

What's your guys' recommendation here?

cc @Eilon

**Comment by Eilon** [comment]
@muratg - let's bring this to shiproom. Can you work with @natemcmaster to update the shiproom bug list?

**Comment by muratg** [comment]
We decided to punt this based on other higher priority work for 2.1.3. 

We'll try to bring this in in 2.1.4 or 2.1.5.

**Comment by muratg** [comment]
@natemcmaster moved this to 2.1.5 based on the current dates. Let me know if you think we can/should do it in 2.1.4

**Comment by natemcmaster** [comment]
It's okay to stay in 2.1.5.

**Comment by natemcmaster** [comment]
@muratg PR to fix the flakiness in 2.1.5. https://github.com/aspnet/DataProtection/pull/322. Since this is not a product change, only a test update, it doesn't need shiproom approval, right?

**Comment by muratg** [comment]
Sent notification mail to shiproom and added the `servicing-approved` label to the PR.

**Comment by Eilon** [comment]
The PR, as sent, includes a product change, so I don't think it is acceptable for a patch release. Can we do a test-only change? E.g. just disable parallelization for the test assembly?

**Comment by Eilon** [comment]
Yeah I say disable the test. Unfortunate, but I consider it lower risk.

**Comment by natemcmaster** [comment]
If risk minimization is our goal, disabling the test is the worst of the option. Losing regression coverage increases the risk that a future 2.1.x servicing update will break something and we will miss it. Since any change to the src/ folder is _a priori_ disallowed now, I'm willing to put a comment in test code that says "this test is flaky, sorry." The only risk in that is that someone is fetching our source and asserting the number of comments in it, or that someone in the future looking at this flaky test failure has to investigate and wastes more time.

> The change itself looks safe overall, but changing the API surface in a patch would be questionable.

But it's not changing the public API surface. That's why I'm so confused about the push back here. What is the risk you are worried about? The only risk I can think of is:

1. Someone is using private reflection and asserts that there are 2 constructors on `XmlKeyManager`
2. Someone is using private reflection and asserts that `FileSystemXmlRepository` only implement 1 interface

But honestly, if someone depends on either of these scenarios, they're doing something seriously wrong.
