### ISSUE TITLE
Websocket fails

### ISSUE THREAD

**Issue by ygoe** [aspnet/Home#3082]
I've followed the instructions in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1) and created a simple echo websocket application to begin with.

Since I have no client yet, I used the one from [websocket.org](http://websocket.org/echo.html). On connecting, this exception is thrown:

**The remote party closed the WebSocket connection without completing the close handshake.**

I'm not closing anything. I'm just connecting and then want to send something through the connection to have it echoed by my application. but it doesn't get that far and already believes the client has misbehaved and closed the connection. Which I cannot believe because the demo works nicely with the websocket.org echo server.

```
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DemoServer.Controllers.RmpController.<Echo>d__1.MoveNext() in C:\Source\Komprenu\RoutedMessagingProtocol\DemoServer\Controllers\RmpController.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DemoServer.Controllers.RmpController.<Index>d__0.MoveNext() in C:\Source\Komprenu\RoutedMessagingProtocol\DemoServer\Controllers\RmpController.cs:line 22
```

I'm using the latest versions of VS 2017 and .NET Core. Testing with Firefox. There was an older issue somewhere here that was resolved. I'm not sure where this error comes from but it means that I cannot use Websockets right now, which is very unfortunate (I'd say critical).

**Comment by Tratcher** [comment]
Please share the relevant controller code. `async void` is the most common cause of issues like this.

**Comment by ygoe** [comment]
This is the controller file:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.WebSockets;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DemoServer.Controllers
{
	[Route("api/[controller]")]
	public class RmpController : Controller
	{
		public async void Index()
		{
			if (HttpContext.WebSockets.IsWebSocketRequest)
			{
				try
				{
					var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync();
					await Echo(HttpContext, webSocket);
				}
				catch (Exception ex)
				{
				}
			}
			else
			{
				HttpContext.Response.StatusCode = 400;
			}
		}

		private async Task Echo(HttpContext context, WebSocket webSocket)
		{
			byte[] buffer = new byte[1024 * 4];
			var result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
			while (!result.CloseStatus.HasValue)
			{
				await webSocket.SendAsync(new ArraySegment<byte>(buffer, 0, result.Count), result.MessageType, result.EndOfMessage, CancellationToken.None);
				result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
			}
			await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, CancellationToken.None);
		}
	}
}
```

The action is indeed `async void` because I had nothing to return and then needed async. After changing it to `async Task` it works correctly. Somehow I don't like that I have to specify the `Task` return type manually when the compiler does so much of the rest. It feels broken design, the async keyword shouldn't require other optional parts to make it work properly.

**Comment by Tratcher** [comment]
No, you can't use async void here, it causes the request to end pre-maturely. Use async Task instead.

**Comment by John0King** [comment]
@Tratcher @ygoe  When work with WebSocket  should us use `[FromService]CancelationToken cancelationToken` and pass it into  `ReceiveAsync` ?

**Comment by Tratcher** [comment]
It would help with graceful shutdown.

**Comment by davidfowl** [comment]
It's amazing how many people use async void with websockets...
