### ISSUE TITLE
[Common]: Running tests pops up a dialog asking to confirm removing certs

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Home#3124]
```
Failed   Microsoft.AspNetCore.Certificates.Generation.Tests.CertificateManagerTests.EnsureCreateHttpsCertificate_DoesNotCreateACertificate_WhenThereIsAnExistingHttpsCertificates
RUNDOTNET : error Message: 
   Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The operation was canceled by the user
  Stack Trace:
     at Internal.Cryptography.Pal.StorePal.Remove(ICertificatePal certificate)
     at System.Security.Cryptography.X509Certificates.X509Store.Remove(X509Certificate2 certificate)
     at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.RemoveCertificateFromTrustedRoots(X509Certificate2 certificate) in D:\work\Common\shared\Microsoft.AspNetCore.Certificates.Generation.Sources\CertificateManager.cs:line 506
     at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.RemoveCertificate(X509Certificate2 certificate, RemoveLocations locations) in D:\work\Common\shared\Microsoft.AspNetCore.Certificates.Generation.Sources\CertificateManager.cs:line 467
     at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.RemoveAllCertificates(CertificatePurpose purpose, StoreName storeName, StoreLocation storeLocation, String subject) in D:\work\Common\shared\Microsoft.AspNetCore.Certificates.Generation.Sources\CertificateManager.cs:line 451
     at Microsoft.AspNetCore.Certificates.Generation.Tests.CertificateManagerTests.EnsureCreateHttpsCertificate_DoesNotCreateACertificate_WhenThereIsAnExistingHttpsCertificates() in D:\work\Common\test\Microsoft.Extensions.Internal.Test\CertificateManagerTests.cs:line 140
  [xUnit.net 00:00:17.2386222]     Microsoft.AspNetCore.Certificates.Generation.Tests.CertificateManagerTests.EnsureAspNetCoreHttpsDevelopmentCertificate_CanRemoveCertificates [SKIP]
  [xUnit.net 00:00:17.2400855]     Microsoft.AspNetCore.Certificates.Generation.Tests.CertificateManagerTests.EnsureAspNetCoreHttpsDevelopmentCertificate_ReturnsCorrectResult_WhenUserCancelsTrustStepOnWindows [SKIP]
```

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by javiercn** [comment]
@pranavkm What platform?

Its probably due to a trusted cert. There's nothing really we can do other than skipping the tests, but we can look into it in the future.

**Comment by pranavkm** [comment]
This was on my Windows dev box.

**Comment by javiercn** [comment]
Ok, I'll take a look next week.

**Comment by javiercn** [comment]
This is probably something specific to your machine. Doesn't repro on the CI and we don't have more info, so closing it for now until is reproed again and we can capture more information.
