### ISSUE TITLE
aspnet-webpack is failing and not working with spatemplates or manual configuration webpack dev middleware failed because of an error while loading 'aspnet-webpack'

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Home#3151]
I keep getting this error when running the example on this page

https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.0#webpack-dev-middleware

`System.AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\choles\source\repos\WebApplication1test\WebApplication1test\node_modules\aspnet-webpack\WebpackDevMiddleware.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
`

**Comment by Eilon** [comment]
This issue was moved to aspnet/JavaScriptServices#1722

**Comment by raptorage527** [comment]
whats the solution for this problem? has anyone figured it out?

**Comment by Eilon** [comment]
@raptorage527 please use the destination issue https://github.com/aspnet/JavaScriptServices/issues/1722 to discuss this topic. Thanks!
