### ISSUE TITLE
SafeHandle has been closed when using WindowsIdentity.RunImpersonated

### ISSUE THREAD

**Issue by ge0rgi** [aspnet/Home#3217]
Hello everyone.

I am having trouble using Impersonation in asp.net core. I have an .NET core web API and .NET web application both running .NET core 2.1 and  using Windows Authentication.

I am trying to access the web service from the web application like this:

`
           var identity = User.Identity as WindowsIdentity;
            
            var test = WindowsIdentity.RunImpersonated(identity.AccessToken, () =>
            {
               var client = new HttpClient(new HttpClientHandler() { UseDefaultCredentials = true }) { BaseAddress = new Uri(MY_URL) };
                try
                {
                    var rq = new HttpRequestMessage(HttpMethod.Get, "mymethod");
                    var response = client.SendAsync(rq).Result;
                    var responseString = response.Content.ReadAsStringAsync().Result;
                    return responseString;
                }
                catch (Exception e)
                {
                    return null;
                }
            });`

I am getting the following Error on the production server and occasionally on my local machine 

> The process was terminated due to an unhandled exception.System.ObjectDisposedException: Safe handle has been closed
 
Full stack trace:

> Application: dotnet.exe
CoreCLR Version: 4.6.26515.7
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: An exception was not handled in an AsyncLocal<T> notification callback.
Description: The process was terminated due to an unhandled exception.System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.ImpersonateLoggedOnUser(SafeAccessTokenHandle userToken)
   at System.Security.Principal.WindowsIdentity.CurrentImpersonatedTokenChanged(AsyncLocalValueChangedArgs`1 args)
   at System.Threading.AsyncLocal`1.System.Threading.IAsyncLocal.OnValueChanged(Object previousValueObj, Object currentValueObj, Boolean contextChanged)
   at System.Threading.ExecutionContext.OnValuesChanged(ExecutionContext previousExecutionCtx, ExecutionContext nextExecutionCtx)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Threading.ExecutionContext.OnValuesChanged(System.Threading.ExecutionContext, System.Threading.ExecutionContext)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(System.Exception, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.MultipleConnectAsync.AsyncFail(System.Exception)
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean, System.Exception)
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(System.IAsyncResult, Boolean)
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult+<>c.<Complete>b__15_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.NameResolutionPal+GetAddrInfoExState+<>c.<CompleteAsyncResult>b__5_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__278_1(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe()
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Am I misusing the the access token somehow and how do I prevent the handle from being disposed. I tried wrapping my code inside a using block, however this did not help.

**Comment by Tratcher** [comment]
This belongs in https://github.com/dotnet/corefx.
Possibly related: https://github.com/dotnet/corefx/issues/25477

**Comment by ge0rgi** [comment]
@Tratcher is there a way to move the issue, or should I create a new one?

**Comment by Tratcher** [comment]
You'll need a new issue.

**Comment by ge0rgi** [comment]
Moved the issue to [dotnet/corefx](https://github.com/dotnet/corefx/issues/30275)
