### ISSUE TITLE
Application will not start even with HOME variable set

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#3222]
_From @a1g3 on June 14, 2018 1:30_

## Steps to reproduce
I am aware that this issue has been seen before, but I have my home directory set to the correct location. Whenever I try to run my application(via dotnet _[Path to Application]_), it will not start and I receive the error below. I ran `echo $HOME` and it gives me the correct location `/home/ubuntu`.

## Expected  behavior
The application should run.

## Actual behavior
```
Application startup exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Vulnerabilities.io.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/ubuntu/test/Vulnerabilities.io/Vulnerabilities.io/Startup.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Vulnerabilities.io.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/ubuntu/test/Vulnerabilities.io/Vulnerabilities.io/Startup.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Vulnerabilities.io.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/ubuntu/test/Vulnerabilities.io/Vulnerabilities.io/Startup.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Vulnerabilities.io.Program.Main(String[] args) in /home/ubuntu/test/Vulnerabilities.io/Vulnerabilities.io/Program.cs:line 11
Aborted (core dumped)
```

## Environment data
`dotnet --info` output:
```
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

_Copied from original issue: dotnet/cli#9487_

**Comment by Tratcher** [comment]
That stack trace is in your own startup code. What are you doing there?

**Comment by a1g3** [comment]
This was due to incorrect file permissions. Thank you for your help!

**Comment by a1g3** [comment]
This can be closed
