### ISSUE TITLE
Controller with relatively large payload fails during transfer on HTTPS

### ISSUE THREAD

**Issue by twilliamsgsnetx** [aspnet/Home#3225]
I have migrated from HTTP to HTTPS with ASP.NET Core 2.1, and I am facing an issue where a controller that once worked just fine transferring ~10mb via HttpPost seems to hang and fail without any clear reason why.

Please tell me what other information I should provide.

```
[Authorize(Policy = "Administrator")]
        [Route("api/membership/memberinfo")]
        [LogAction]
        [RequestSizeLimit(26214400)]
        [HttpPost]
        public IActionResult AddMemberInfo([FromBody]IEnumerable<ViewModels.Membership.MemberInfo> memberInfo)
```

```
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Trace: Authorization Filter: After executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Trace: Resource Filter: Before executing OnResourceExecuting on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Trace: Resource Filter: After executing OnResourceExecuting on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder:Debug: Attempting to bind parameter 'memberInfo' of type 'System.Collections.Generic.IEnumerable`1[DataPlatform.ViewModels.Membership.MemberInfo]' ...
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder:Debug: Attempting to bind model of type 'System.Collections.Generic.IEnumerable`1[DataPlatform.ViewModels.Membership.MemberInfo]' using the name '' in request data ...
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder:Debug: Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json; charset=UTF-8'.
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder:Debug: Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json; charset=UTF-8'.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51M", Request id "0HLEHVRAAJ51M:00000002": started reading request body.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51M" paused.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51M" resumed.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51K" reset.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51L" reset.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51L" disconnecting.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51K" disconnecting.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51K" sending FIN.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51L" sending FIN.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51L" stopped.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51K" stopped.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51M" reset.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51M" disconnecting.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets:Debug: Connection id "0HLEHVRAAJ51M" sending FIN.
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51M", Request id "0HLEHVRAAJ51M:00000002": done reading request body.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Trace: Resource Filter: Before executing OnResourceExecuted on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Trace: Resource Filter: After executing OnResourceExecuted on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action DataPlatform.Controllers.Membership.MembershipController.AddMemberInfo (DataPlatform) in 129386.9625ms
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware:Debug: Microsoft.AspNetCore.Connections.ConnectionResetException occurred, checking if Entity Framework recorded this exception as resulting from a failed database operation.
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware:Debug: Entity Framework did not record any exceptions due to failed database operations. This means the current exception is not a failed Entity Framework database operation, or the current exception occurred from a DbContext that was not obtained from request services.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.

Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitable.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessSends()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoSend()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 129549.0613ms 500 text/html; charset=utf-8
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLEHVRAAJ51M" stopped.
```

**Comment by twilliamsgsnetx** [comment]
I thought this might be a timeout issue since my chrome tools indicate 2 minutes every time it fails on the client side, so I was thinking I am actually hitting the default 2 minute `KeepAliveTimeout` with Kestrel. I increased that timeout though and still experience the issue.
```
.UseKestrel(options =>
                {
                    options.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(4);
                })
```

**Comment by gustavnavar** [comment]
I'm also gettind a similar error after upgrading to .net core 2.1. It happens when users upload large files. In this case the error  is:

An unhandled exception has occurred while executing the request. Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitable.GetResult() at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives() at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive() --- End of inner exception stack trace --- at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.GetReadAsyncResult() at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync() at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.GetReadAsyncResult() at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token) --- End of stack trace from previous location where exception was thrown --- at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessSends() at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.GetReadAsyncResult() at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken) at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoSend() at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.EnsureBufferedAsync(Int32 minCount, CancellationToken cancellationToken) at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken) at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken) at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken) at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext) at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext) at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

Let me know if you need additional info

**Comment by muratg** [comment]
@twilliamsgsnetx @gustavnavar Is it possible for you guys to share an app that reproduces this problem? We would like to try and debug this here. Thanks!

**Comment by halter73** [comment]
@twilliamsgsnetx Kestrel's `KeepAliveTimeout` is the amount of time Kestrel will allow a client to keep an HTTP connection idle *between* requests. It does not affect anything that happens while receiving a request and/or sending a response.

@twilliamsgsnetx @gustavnavar ConnectionResetExceptions originate for the client. It means the client ungracefully terminated the connection, not the server. Perhaps you're hitting some sort of client timeout.

**Comment by gustavnavar** [comment]
I haven't seen any error since the application was updated to version 2.1.1 sdk 1 week ago
