### ISSUE TITLE
Developer Exception Page displaying white page

### ISSUE THREAD

**Issue by joaobhering** [aspnet/Home#3301]
### Problem:

We have a application that recently have been migrated to Core 2.1.
Since then we notice that our application is not showing the default Developer Exception Page when an error occur on Dapper SQL Executions.

If an Exception is throw on my code, the Page displays successfully.

After spending some time figuring out why the middleware displays a white page, I found on log that an Exception of type `System.InvalidOperationException` is occurring.

### Extra info:
Windows 10 Pro (v17134.112)
.NET Core 2.1 SDK v2.1.301
Visual Studio 2017 15.7.4

| Project Name | Packages | References |
| :-------------: | :-------------: | :-------------: |
| `MyProject.Web` | `Microsoft.AspNetCore.App(2.1.1)`<br/>`BuildBundlerMinifier(2.8.391)`<br/>`Newtonsoft.Json(11.0.2)`<br/>`NLog.Web.AspNetCore(4.5.4)` | `MyProject.DTO`<br/>`MyProject.BLL` |
| `MyProject.BLL` | `NLog(4.5.6)` | `MyProject.DTO`<br/>`MyProject.DAL` |
| `MyProject.DAL` | `NLog(4.5.6)`<br/>`Microsoft.Extensions.Configuration(2.1.1)`<br/>`Microsoft.Extensions.Configuration.Json(2.1.1)` | `MyProject.DTO`<br/>`MyProject.Dapper` |
| `MyProject.DTO` | | |
| `MyProject.Dapper` | `Microsoft.Extensions.Configuration(2.1.1)`<br/>`Microsoft.Extensions.Configuration.Json(2.1.1)`<br/>`System.Data.SqlClient(4.5.1)`<br/>`Dapper(1.50.5)` | |

Call Stack:
Page (`MyProject.Web`) -> Controller Action (`MyProject.Web`) -> Business Logic (`MyProject.BLL`) ->  Data Access (`MyProject.DAL`) ->  SQL Execution (`MyProject.Dapper` | Return: `MyProject.DTO`)

Console Debug Log (Error only):
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Data.DataException: Error parsing column 2 (Login=username - String) ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan\`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan\`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserialize96427131-d37e-4747-a448-e49a43e1ea6d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:line 3609
   at Deserialize96427131-d37e-4747-a448-e49a43e1ea6d(IDataReader )
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command)
   at MyProject.Dapper.DapperProvider.ReadListAsync[T](String procedure, DynamicParameters parametros)
   at MyApplication.DAL.User.GetUsersAsync[T](Int32 idEmpresa)
   at MyApplication.BLL.User.GetUsersAsync(Int32 idEmpresa)
   at MyApplication.Web.Controllers.UserController.Index()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask\`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[3]
      An exception was thrown attempting to display the error page.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Reflection.MemberInfo.get_MetadataToken()
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset)
   at Microsoft.Extensions.StackTrace.Sources.StackTraceHelper.GetFrames(Exception exception)
   at Microsoft.Extensions.StackTrace.Sources.ExceptionDetailsProvider.GetDetails(Exception exception)+MoveNext()
   at Microsoft.AspNetCore.Diagnostics.RazorViews.ErrorPage.ExecuteAsync()
   at Microsoft.Extensions.RazorViews.BaseView.ExecuteAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLF38758SPBJ", Request id "0HLF38758SPBJ:00000001": An unhandled exception was thrown by the application.
System.Data.DataException: Error parsing column 2 (Login=username - String) ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan\`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan\`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserialize96427131-d37e-4747-a448-e49a43e1ea6d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:line 3609
   at Deserialize96427131-d37e-4747-a448-e49a43e1ea6d(IDataReader )
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command)
   at MyProject.Dapper.DapperProvider.ReadListAsync[T](String procedure, DynamicParameters parametros)
   at MyApplication.DAL.User.GetUsersAsync[T](Int32 idEmpresa)
   at MyApplication.BLL.User.GetUsersAsync(Int32 idEmpresa)
   at MyApplication.Web.Controllers.UserController.Index()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask\`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication\`1 application)
```

**Comment by Tratcher** [comment]
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Reflection.MemberInfo.get_MetadataToken()
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset)
```
@pranavkm ?

**Comment by pranavkm** [comment]
Perhaps `MethodBase` is on a generated type that does not implement the property - https://referencesource.microsoft.com/#mscorlib/system/reflection/memberinfo.cs,65?

**Comment by pranavkm** [comment]
`PortablePdbReader` attempts to ignore dynamically generated assemblies: https://github.com/aspnet/Common/blob/master/shared/Microsoft.Extensions.StackTrace.Sources/StackFrame/PortablePdbReader.cs#L22. Maybe it's missing additional checks?

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.

**Comment by chucker** [comment]
Hi,

I saw someone struggle with a dependency injection error in an RC project, where adding an `@inject` statement to their component caused a blank page to render. No error was logged to the browser console or the VS output window.

Will this PR improve this behavior, or should I file a separate issue?

**Comment by pranavkm** [comment]
> or should I file a separate issue?

A different issue. Razor Component's isn't running in to the same problem as this issue.

**Comment by chucker** [comment]
…oops. I meant to post that comment on #7165.
