### ISSUE TITLE
Flaky test: TestValidateAndBuild

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#3365]
This test [fails](http://aspnetci/viewLog.html?buildId=517794&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
System.InvalidOperationException : Restore failed with exit code: 1 :: Dotnet path: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet
   at Microsoft.VisualStudio.Web.CodeGeneration.MsBuildProjectSetupHelper.RestoreAndBuild(String path, ITestOutputHelper output) in /_/test/Shared/MsBuildProjectSetupHelper.cs:line 114
   at Microsoft.VisualStudio.Web.CodeGenerators.Mvc.IdentityGeneratorTemplateModelBuilderTests.TestValidateAndBuild() in /_/test/VS.Web.CG.Mvc.Test/IdentityGeneratorTemplateModelBuilderTests.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
Restoring packages for /mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Library1/Library1.csproj...
  Restoring packages for /mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj...
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error : Unable to load the service index for source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json. [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :   Resource temporarily unavailable [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error : NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json. ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    --- End of inner exception stack trace --- [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result() [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result() [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result() [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at NuGet.Protocol.ServerWarningLogHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) [/mnt/temp/buildTmp/tmpfiles/dddbf267-b7c9-4975-a80d-51eb1df52637/Root/Test.csproj]
/mnt/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.302/NuGet.targets(114,5): error :    at NuGet.P
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestControllerGenerators [failed again](http://aspnetci/viewLog.html?buildId=517794&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestIdentityGenerator_IndividualFiles_AllFilesBuild [failed again](http://aspnetci/viewLog.html?buildId=517757&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@natemcmaster / @ryanbrandenburg - would this be a NuGet failure? Or an Azure blob failure?

**Comment by natemcmaster** [comment]
It looks like the result of networking issues on our agents.
