### ISSUE TITLE
ASP.NET 5 Console Application as Azure WebJob

### ISSUE THREAD

**Issue by djanosik** [aspnet/Home#338]
Hi,

what do I need to publish ASP.NET 5 Console Application as an Azure WebJob? AFAIK there is no executable I can use to run the application.

Thank you!

**Comment by victorhurdugaci** [comment]
Bundle the application using `kpm bundle --runtime <runtime>`, zip the output folder and deploy it as webjob.

**Comment by Eilon** [comment]
There is no direct executable, but when you use `kpm bundle` it'll generated CMD file for whichever commands were registered in the `project.json` file, such as `run` --> `run.cmd`

**Comment by djanosik** [comment]
Thank you! I am able to deploy the web job, but it fails with this error message.

    [03/18/2015 21:11:50 > 21031f: SYS INFO] Status changed to Initializing
    [03/18/2015 21:11:52 > 21031f: SYS INFO] Run script 'WebJob.cmd' with script host - 'WindowsScriptHost'
    [03/18/2015 21:11:52 > 21031f: SYS INFO] Status changed to Running
    [03/18/2015 21:11:52 > 21031f: ERR ] '"klr.exe"' is not recognized as an internal or external command,
    [03/18/2015 21:11:52 > 21031f: ERR ] operable program or batch file.
    [03/18/2015 21:11:52 > 21031f: SYS INFO] Status changed to Failed
    [03/18/2015 21:11:52 > 21031f: SYS ERR ] Job failed due to exit code 1

**Comment by victorhurdugaci** [comment]
You have to bundle the application with the runtime (like I showed above). Otherwise it will not work

**Comment by djanosik** [comment]
Great, it works now. Thank you!

**Comment by mburumaxwell** [comment]
Hi,
I have a problem when I try to use the webjobs sdk with a console application.
The code:
```cs
var jobconfig = new JobHostConfiguration("key here");
var host = new JobHost(jobconfig);
host.RunAndBlock();
```

It fails in the first line with the following error:
```
An exception of type 'System.IO.FileLoadException' occurred in Microsoft.Azure.WebJobs.Host.dll but was not handled in user code
Additional information: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

Checking further I get this
```
A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

The Stack Trace is:
```
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageCredentialsValidator..ctor()
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider..ctor()
   at Microsoft.Azure.WebJobs.JobHostConfiguration..ctor(String dashboardAndStorageConnectionString)
   at TestWebJob.Program.Main(String[] args) in C:\Users\Me\Documents\TestWebJob\Program.cs:line 20
```

After reading through some issues, I realized I should sign the output. I tried two options as below but none worked on the Console App:
Option 1:
```json
"compilationOptions": {
    "keyFile": "TestWebJob.snk"
  }
```

Option 2:
```json
"compilationOptions": {
    "strongName": true
  }
```

Anyone have a solution or workaround?
Thanks in advance

**Comment by Eilon** [comment]
Looks like you logged this here: https://github.com/Azure/azure-webjobs-sdk/issues/566

**Comment by mburumaxwell** [comment]
yes I did so
