### ISSUE TITLE
kpm build command: global.json

### ISSUE THREAD

**Issue by kscott5** [aspnet/Home#339]
Is it possible to run kpm build command using the global.json. If so, what is the correct format for the global.json file and command to execute.

THIS DOESN"T WORK

```powershell
PS C:\apps\pcsc\GreenShelter> kpm build global.json --out bin
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.Framework.PackageManager.BuildManager.Normalize(String projectDir)
   at Microsoft.Framework.PackageManager.BuildManager..ctor(IServiceProvider hostServices, BuildOptions buildOptions)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_4.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
PS C:\apps\pcsc\GreenShelter>
```
[global.json in my repository](https://github.com/kscott5/greenshelter/)
```json
{
    "sources": ["%project:Directory%/src/Mvc", "%project.Directory%/test/Mvc"]	
}
```

Also tried with global.json like this
```json
{
	"projects": [ "%project:Directory/src/Mvc/project.json", "%project:Directory%/test/Mvc/project.json"],
    "sources": ["%project:Directory%/src/Mvc", "%project:Directory%/test/Mvc"]
}
```

I reviewed [Issue #243](https://aspnet/Home/issues/243) and it links to the [scheme store for global.jsonl | http//json.schemastore.org/global] but looking at [aspnet/MVC global.json](https://github.com/aspnet/Mvc/blob/dev/global.json) there's a disconnect.

**Comment by kscott5** [comment]
Currenty .NET Core 1.0.1 restoring as expected on global.json

**Comment by MaximRouiller** [comment]
Awesome and congrats! 😄
