### ISSUE TITLE
Support for multiple authorities for the same JWT bearer scheme

### ISSUE THREAD

**Issue by jimmy3912msncom** [aspnet/Home#3455]
We recently started moving our applications from our legacy ASP.NET owin web hosted web API to ASP.NET Core. Our application supported JWT Bearer authentication for various clouds: the Azure global cloud, Azure China cloud, the Azure German cloud, and the Azure US government cloud.

The way we did this was having multiple configurations for each cloud and calling
foreach (var tokenConfiguration in this.config.TokenAuthenticationConfigurations)
{
    var aadTokenOptions = new WindowsAzureActiveDirectoryBearerAuthenticationOptions()
    {
        Tenant = tokenConfiguration.TenantId,
        MetadataAddress = $"{tokenConfiguration.OpenIdConnectDiscoveryMetadataEndpoint}/{tokenConfiguration.TenantId}/{tokenConfiguration.FederationMetadataUrlSuffix}",
        TokenHandler = new JwtSecurityTokenHandler(),
        TokenValidationParameters = new TokenValidationParameters()
        {
            ValidAudiences = tokenConfiguration.AadTokenValidAudiences,
            ValidateIssuer = false,  // can't set to true due to multi-tenant access enabled apps and different metadata address for each
            ValidateAudience = tokenConfiguration.ValidateAudience,
            ValidateIssuerSigningKey = tokenConfiguration.ValidateIssuerSigningKey,
            ValidateLifetime = tokenConfiguration.ValidateLifetime
        }
    };
    app.UseWindowsAzureActiveDirectoryBearerAuthentication(aadTokenOptions);
}

By doing this we could have the same authentication scheme support any of our users from any cloud since the authority to use when making open id connect metadata discovery calls were different for each cloud (and the corresponding metadata itself was different e.g. signing keys, etc...).

This way all of our callers can use the same authorization bearer scheme when calling our APIs, regardless of cloud.

With ASP.NET Core 2.1, I tried to do this as well as below:

var authenticationConfigurations = this.configuration.GetSection("AuthenticationConfigurations").Get<IEnumerable<AuthenticationConfiguration>>();
var authenticationBuilder = services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme);
foreach (var authenticationConfiguration in authenticationConfigurations)
{
    authenticationBuilder.AddJwtBearer(options =>
    {
        options.Authority = authenticationConfiguration.Authority;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            RequireExpirationTime = authenticationConfiguration.RequireExpirationTime,
            ValidateLifetime = authenticationConfiguration.ValidateLifetime,
            ValidateIssuer = authenticationConfiguration.ValidateIssuer,
            ValidateAudience = authenticationConfiguration.ValidateAudience,
            ValidAudiences = authenticationConfiguration.ValidAudiences
        };
    });
}

but it fails with:
System.InvalidOperationException: 'Scheme already exists: Bearer'
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action`1 configureBuilder)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__0(AuthenticationOptions o)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options, IDictionary`2 schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)

Is there a way to enable this? I want to avoid having to make our users change call patterns if it is unnecessary to.

Microsoft.NETCore.App version 2.1.0
Microsoft.AspNetCore.All 2.1.2

**Comment by blowdart** [comment]
This issue was moved to aspnet/Security#1847
