### ISSUE TITLE
TypeLoadException: The generic type 'System.Func`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

### ISSUE THREAD

**Issue by RemarkLima** [aspnet/Home#3457]
I have a webapp that works in Core 2.0 without issue.

I've attempted to upgrade to 2.1 without success. Most of the application works, except for certain pages and only when posting data. The issue appears to be in the model-binder but I can't diagnose any further as there's no more info other than the stack trace.

I've updated all version, I've uninstalled old SDK's and tried to put the latest `System.Private.CoreLib` in the bin directory however, the same error always happens when `POST`ing data back to a controller.

I've cut out all references where possible, and cut down my project.json to the bare minimum. I've tried to remove packages but all has had the same result. My project.json is:

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>xxx</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" PrivateAssets="All" />
	<PackageReference Include="EPPlus.Core" Version="1.5.4" />
	<PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="1.1.15" />
    <PackageReference Include="CsvHelper" Version="7.1.1" />    
    <PackageReference Include="NReco.PdfGenerator.LT" Version="1.1.15" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0005" />
    <PackageReference Include="MailKit" Version="2.0.6" />
    <PackageReference Include="MimeKit" Version="2.0.6" />
    <PackageReference Include="SSH.NET" Version="2016.1.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.8.16" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="1.8.8" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.21" />
  </ItemGroup>

</Project>`

The full stack trace is below:

> System.RuntimeType.MakeGenericType(Type[] instantiation)
Microsoft.Extensions.Internal.PropertyHelper.MakeFastPropertyGetter(Type openGenericDelegateType, MethodInfo propertyGetMethod, MethodInfo openGenericWrapperMethod)
Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreateSinglePropertyDetails(ModelMetadataIdentity propertyKey, PropertyHelper propertyHelper)
Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreatePropertyDetails(ModelMetadataIdentity key)
Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.GetMetadataForProperties(Type modelType)
Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata.get_Properties()
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreCached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, object token)
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.GetParameterBindingInfo(IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.CreateBinderDelegate(ParameterBinder parameterBinder, IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler+<>c__DisplayClass8_0.<RouteAsync>b__0(HttpContext c)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

As support is short for 2.0 it is something that would be good to get resolved.

**Comment by Eilon** [comment]
Hmm you definitely shouldn't ever need to put `System.Private.CoreLib` in the app's bin directory...

Is there any chance you can run this app under a debugger and see what the parameters are to `MakeFastPropertyGetter` towards the top of the stack?

**Comment by RemarkLima** [comment]
Hi @Eilon I've just tried to debug in Visual Studio 2017 but even with every single exception enabled and checked to break on, it doesn't break so it's happening before.

If I clear the output window, then I get the below:

> Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:55319/Outbound/OutboundClaims/UpdateUcmSection application/x-www-form-urlencoded 584
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:55319/Outbound/OutboundClaims/UpdateUcmSection application/x-www-form-urlencoded 584
Microsoft.EntityFrameworkCore.Infrastructure:Information: Entity Framework Core 2.1.2-rtm-30932 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
Microsoft.EntityFrameworkCore.Infrastructure:Information: Entity Framework Core 2.1.2-rtm-30932 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.

Then the rest of the stack trace as above...

> System.TypeLoadException: The generic type 'System.Func`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.Internal.PropertyHelper.MakeFastPropertyGetter(Type openGenericDelegateType, MethodInfo propertyGetMethod, MethodInfo openGenericWrapperMethod)
   at Microsoft.Extensions.Internal.PropertyHelper.MakeFastPropertyGetter(PropertyInfo propertyInfo, MethodInfo propertyGetterWrapperMethod, MethodInfo propertyGetterByRefWrapperMethod)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreateSinglePropertyDetails(ModelMetadataIdentity propertyKey, PropertyHelper propertyHelper)

The only "thing" potentially different is that the mapping has a couple of child objects, so the form is posting `parentObj.ChildObj.Property` as the name of the items to map into view object.

**Comment by Eilon** [comment]
@RemarkLima sorry for the delay getting back to you. Are you still hitting this issue? Do you have a simplified app that can reproduce this issue so that we can investigate?

**Comment by Eilon** [comment]
@jkotas / @A-and - is this the same issue as https://github.com/dotnet/coreclr/issues/18700 ? If so, what release is that fix in?

**Comment by jkotas** [comment]
dotnet/coreclr#18700 was an invalid test setup. It was not a product issue.

**Comment by Eilon** [comment]
Oh 😢 

Could whatever caused the invalid test setup also be in play here? ("You're holding it wrong"?)

**Comment by jkotas** [comment]
> Could whatever caused the invalid test setup also be in play here?

The invalid test setup was using mismatched set of binaries from netcoreapp2.0 and netcoreapp2.1. Yes, it is possible that it is somehow happening here as well.

@RemarkLima Could you please find out the values in `Type[] instantiation` argument when the failure happens? It would help us diagnose this issue.

**Comment by rynowak** [comment]
> but even with every single exception enabled and checked to break on

You probably need to disable "Just my code"

Based on the call stack it's one of your model types from the action method that's failing.

**Comment by RemarkLima** [comment]
Hi all,

@jkotas that's the part I can't seem to get VS to break on - it just throws the error, but sounds like @rynowak may have the solution to this.

I've been trying to distil the project down to get the error on its own, but it's taking a while to copy over the various models and the like in between work required!

Hopefully, I'll get a chance tomorrow to complete the project so I can get a repo up.

**Comment by RemarkLima** [comment]
OK, managed to refine this down the issue and it would seem to be something with a 3rd party library, MimeKit. I'll raise the issue there but this may also have additional cases, and it's something that is not an issue in 2.0 and only happens in 2.1.

My repo is here:
https://github.com/RemarkLima/Func2Test

The essence of the issue is the binding to a model with a getter with the `MailboxAddress` type, this may happen with other complex types but not had a chance to test

    namespace Func2Test.Models
    {
        public class Func2ViewModel
        {
            public MailboxAddress GetFunc2Issue
            {
                get { return null; }
            }
        }
    }

The return type of `MailboxAddress` causes this error - as said, there may be other types, and this code works in 2.0 so there's something changed.

Hopefully this help, but appreciate it may not be a core issue, as it's a 3rd party library casuing the issue.

**Comment by jstedfast** [comment]
I'm not sure what MailboxAddress has to do with Func`2 - especially since you're not even instantiating a new MailboxAddress.

**Comment by rynowak** [comment]
So it ends up throwing somewhere in here: https://github.com/aspnet/Common/blob/master/shared/Microsoft.Extensions.PropertyHelper.Sources/PropertyHelper.cs#L263

So the generic instantiation is failing for `Func<Func2ViewModel, MailboxAddress>` https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MailboxAddress.cs

**Comment by jkotas** [comment]
The instantiation that this is failing for is `Func<Encoding, ReadOnlySpan<byte>>`. `ReadOnlySpan<byte>` is ref-like type that cannot be used as generic argument. It is by design that the runtime will fail to create this instantiation. 

The problem seems to be that Microsoft.AspNetCore.Mvc.ModelBinding decided to bind to the new 2.1 method overloads that take `ReadOnlySpan<byte>` that did not exist in 2.0.

**Comment by rynowak** [comment]
Thanks @jkotas 

I think we need to do something inside MVC to avoid this case, or report a clearer failure when someone does it. I wonder if we should consider a semantic where we only bind `System.` types if they have a type converter. 

@RemarkLima  - I'd really suggest when you model bind types that you only supply types that you actually expect to get model bound. If you have extra things on parameters that you didn't intend to come from the request, then you're also subject to [overposting](https://andrewlock.net/preventing-mass-assignment-or-over-posting-in-asp-net-core/) - as well, MVC will attempt to model bind and validate these objects, which can cause issues if they are especially deep. 

/cc @pranavkm as FYI

**Comment by rynowak** [comment]
I'm moving this to aspnet/MVC so we can track it as actionable.

**Comment by rynowak** [comment]
@RemarkLima - if you have more questions about this feel free to ask on aspnet/Mvc#8545
