### ISSUE TITLE
Failing to write to loggers cause Kestrel connection processing to end abnormally

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#3460]
When writing to a logger fails, it crashes the request and Kestrel will not return a response. Any exception handling middleware won't be invoked: 

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
System.AggregateException: An error occurred while writing to logger(s).

...

crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unexpected exception in HttpConnection.ProcessRequestsAsync.
```

A minimal repro looks like this:

```cs
public class Program
{
    public static void Main(string[] args) => CreateWebHostBuilder(args).Build().Run();

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging(l => l.Services.AddSingleton<ILoggerProvider, FooLoggerProvider>())
            .Configure(app =>
            {
                app.UseDeveloperExceptionPage();
                app.Run(async (context) =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });
            });
}

public class FooLoggerProvider : ILoggerProvider
{
    public ILogger CreateLogger(string categoryName) => new FooLogger();

    public void Dispose() { }
}

public class FooLogger : ILogger
{
    public IDisposable BeginScope<TState>(TState state) => NoopDisposable.Instance;

    public bool IsEnabled(LogLevel logLevel) => logLevel >= LogLevel.Information;

    public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
    {
        throw new InvalidOperationException("It's broken");
    }

    private class NoopDisposable : IDisposable
    {
        public static NoopDisposable Instance = new NoopDisposable();

        public void Dispose() { }
    }
}
```

It repro's on a `netcoreapp2.1` application with the 2.1.401 SDK and 2.1.3 runtime.

<details>
<summary>The full stack-trace</summary>

```
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:5001/
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
System.AggregateException: An error occurred while writing to logger(s). (It's broken) ---> System.InvalidOperationException: It's broken
   at WebApplication3.FooLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\Henk Mollema\source\repos\WebApplication3\WebApplication3\Program.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.LogRequestStarting(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.CreateContext(IFeatureCollection contextFeatures)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) System.InvalidOperationException: It's broken
   at WebApplication3.FooLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\Henk Mollema\source\repos\WebApplication3\WebApplication3\Program.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unexpected exception in HttpConnection.ProcessRequestsAsync.
System.AggregateException: An error occurred while writing to logger(s). (It's broken) ---> System.InvalidOperationException: It's broken
   at WebApplication3.FooLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\Henk Mollema\source\repos\WebApplication3\WebApplication3\Program.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogWarning(ILogger logger, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
---> (Inner Exception #0) System.InvalidOperationException: It's broken
   at WebApplication3.FooLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\Henk Mollema\source\repos\WebApplication3\WebApplication3\Program.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

crit: Microsoft.AspNetCore.Server.Kestrel[0]
      ConnectionDispatcher.Execute() 0HLGAEBC3422F
System.AggregateException: An error occurred while writing to logger(s). (It's broken) ---> System.InvalidOperationException: It's broken
   at WebApplication3.FooLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\Henk Mollema\source\repos\WebApplication3\WebApplication3\Program.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogCritical(ILogger logger, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1.OnConnectionAsync(ConnectionContext connectionContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher.Execute(ConnectionContext connectionContext)
---> (Inner Exception #0) System.InvalidOperationException: It's broken
   at WebApplication3.FooLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\Henk Mollema\source\repos\WebApplication3\WebApplication3\Program.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
```
</details>

<details>
<summary>.NET Core environment info</summary>

```
λ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
</details>

Even though writing to loggers should not fail, this behavior is rather destructive and hard to debug since no exception handlers are hit. Is this by design?

**Comment by Eilon** [comment]
@Tratcher / @halter73 - thoughts on where this issue should go? Kestrel? Hosting? Logging?

**Comment by halter73** [comment]
If there's action to be taken here, it should be in Logging. It's far too burdensome to expect the server/framework to handle exceptions from loggers. The type of defensive coding that would require would be unwieldy to say the least.

It's possible we could have Logging wrap ILoggers in order to catch these exceptions, but that leaves us with the question on how we report exceptions from the throwing ILogger and if/how we report the original log. Stderr?

It might be better to have guidance to not ever throw from ILoggers.

**Comment by davidfowl** [comment]
Loggers can't throw. Lets just beef up our docs. It's not really reasonable for all consumers of logging to assume a logger can throw, better to just let logging implementations know they should never throw when logging

**Comment by davidfowl** [comment]
> I guess you could argue what the point is of throwing the aggregate exception here:

You could but it doesn't hurt, it just means you get N exceptions instead of the first one. Also all loggers get a chance to run currently.

**Comment by henkmollema** [comment]
> You could but it doesn't hurt, it just means you get N exceptions instead of the first one. Also all loggers get a chance to run currently.

I understand. My point is that after each logger has ran any exceptions that were caught result in a aggregated error which gets thrown, but there is effectively no one to catch the error which results in a destabilized response. Writing each error to the stderr might make more sense than throwing an error.

**Comment by Eilon** [comment]
Looks like we don't currently plan to have official docs on writing custom loggers: https://github.com/aspnet/Docs/issues/6157

And given that no product work is planned in this issue, I'm closing it.
