### ISSUE TITLE
PersistKeysToRedis - Connection refused (ASP.Net Core 2.1.3)

### ISSUE THREAD

**Issue by mylifelineio** [aspnet/Home#3464]
1. I use Docker, trying to persist the data protection keys to redis, but get the following error:

2. Exception
```
app.monitor    | Unhandled Exception: System.AggregateException: One or more errors occurred. (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
app.monitor    |    at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
app.monitor    |    at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
app.monitor    |    at System.Net.Sockets.Socket.PostOneBeginConnect(MultipleAddressConnectAsyncResult context)
app.monitor    | --- End of stack trace from previous location where exception was thrown ---
app.monitor    |    at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
app.monitor    |    at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
app.monitor    |    at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
app.monitor    |    at System.Net.Sockets.Socket.ConnectAsync(String host, Int32 port)
app.monitor    |    at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, String host, Int32 port)
app.monitor    |    at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\SocketManager.cs:line 194
app.monitor    |    at StackExchange.Redis.PhysicalConnection.BeginConnect(TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 121
app.monitor    |    at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalBridge.cs:line 699
app.monitor    |    at StackExchange.Redis.PhysicalBridge.ResetNonConnected() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalBridge.cs:line 301
app.monitor    |    at StackExchange.Redis.ServerEndPoint.ResetNonConnected() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ServerEndPoint.cs:line 55
app.monitor    |    at StackExchange.Redis.ConnectionMultiplexer.ResetAllNonConnected() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1599
app.monitor    |    at StackExchange.Redis.ConnectionMultiplexer.ReconfigureAsync(Boolean first, Boolean reconfigureAll, TextWriter log, EndPoint blame, String cause, Boolean publishReconfigure, CommandFlags publishReconfigureFlags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1537
app.monitor    |    --- End of inner exception stack trace ---
app.monitor    |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
app.monitor    |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
app.monitor    |    at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 874
app.monitor    |    at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 855
app.monitor    |    at app.Monitor.Startup.ConfigureServices(IServiceCollection services) in /src/app.Monitor/Startup.cs:line 72
app.monitor    | --- End of stack trace from previous location where exception was thrown ---
app.monitor    |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
app.monitor    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
app.monitor    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
app.monitor    |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```
Docker Compose:

```
redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

```
Startup.cs

```
var redis = ConnectionMultiplexer.Connect(Environment.GetEnvironmentVariable("REDIS_CONNECTION_STRING"));
services.AddDataProtection().PersistKeysToRedis(redis, "DataProtection-Keys");
services.AddSignalR().AddRedis(Environment.GetEnvironmentVariable("REDIS_CONNECTION_STRING"));

```
`REDIS_CONNECTION_STRING = "localhost,abortConnect=false"`

Versions:

> Microsoft.AspNetCore.All (2.1.3)
> Microsoft.AspNetCore.DataProtection.Redis (0.4.1)
> Ubuntu 16.04
> Docker-Compose 3.4

Redis Output

```
redis                 | 1:C 27 Aug 09:44:17.981 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis                 | 1:C 27 Aug 09:44:17.981 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
redis                 | 1:C 27 Aug 09:44:17.982 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis                 | 1:M 27 Aug 09:44:17.984 * Running mode=standalone, port=6379.
redis                 | 1:M 27 Aug 09:44:17.985 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis                 | 1:M 27 Aug 09:44:17.985 # Server initialized
redis                 | 1:M 27 Aug 09:44:17.985 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis                 | 1:M 27 Aug 09:44:17.985 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis                 | 1:M 27 Aug 09:44:17.985 * Ready to accept connections

```

**Comment by mylifelineio** [comment]
I needed to reference the container and port

`REDIS_CONNECTION_STRING = "redis:6379,abortConnect=false"`
