### ISSUE TITLE
Test failure: System_CanUnprotectWithCert

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#3496]
This test [fails](http://aspnetci/viewLog.html?buildId=544356&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
System.Security.Cryptography.CryptographicException : An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Security.Cryptography.Pkcs, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyRingBasedDataProtector.cs:line 141
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext) in /_/src/Microsoft.AspNetCore.DataProtection.Abstractions/DataProtectionCommonExtensions.cs:line 199
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.<>c__DisplayClass7_0.<System_CanUnprotectWithCert>b__0(DirectoryInfo directory) in /_/test/Microsoft.AspNetCore.DataProtection.Extensions.Test/DataProtectionProviderTests.cs:line 272
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.WithUniqueTempDirectory(Action`1 testCode) in /_/test/Microsoft.AspNetCore.DataProtection.Extensions.Test/DataProtectionProviderTests.cs:line 298
----- Inner Stack Trace -----
   at System.Security.Cryptography.Xml.KeyInfoX509Data.GetXml(XmlDocument xmlDocument)
   at System.Security.Cryptography.Xml.KeyInfo.GetXml(XmlDocument xmlDocument)
   at System.Security.Cryptography.Xml.EncryptedKey.GetXml(XmlDocument document)
   at System.Security.Cryptography.Xml.KeyInfo.GetXml(XmlDocument xmlDocument)
   at System.Security.Cryptography.Xml.EncryptedData.GetXml(XmlDocument document)
   at System.Security.Cryptography.Xml.EncryptedXml.ReplaceElement(XmlElement inputElement, EncryptedData encryptedData, Boolean content)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.CertificateXmlEncryptor.EncryptElement(XElement plaintextElement) in /_/src/Microsoft.AspNetCore.DataProtection/XmlEncryption/CertificateXmlEncryptor.cs:line 104
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.CertificateXmlEncryptor.Encrypt(XElement plaintextElement) in /_/src/Microsoft.AspNetCore.DataProtection/XmlEncryption/CertificateXmlEncryptor.cs:line 85
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element) in /_/src/Microsoft.AspNetCore.DataProtection/XmlEncryption/XmlEncryptionExtensions.cs:line 100
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate) in /_/src/Microsoft.AspNetCore.DataProtection/KeyManagement/XmlKeyManager.cs:line 414
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate) in /_/src/Microsoft.AspNetCore.DataProtection/KeyManagement/XmlKeyManager.cs:line 133
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in /_/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyRingProvider.cs:line 102
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow) in /_/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyRingProvider.cs:line 177
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyRingBasedDataProtector.cs:line 102
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
System_UsesInMemoryCertificate [failed with about the same error](http://aspnetci/viewLog.html?buildId=544356&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
System_CanUnprotectWithCert [failed with about the same error](http://aspnetci/viewLog.html?buildId=544512&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@muratg can you assign?

**Comment by muratg** [comment]
@natemcmaster could you take an initial look please?

**Comment by natemcmaster** [comment]
Nothing changed in dataprotection that would have caused this. My guess is this was caused by changes in the corefx package System.Security.Cryptography.Xml or its dependencies.

**Comment by muratg** [comment]
@GrabYourPitchforks @joshfree Are you guys aware of any recent changes in `System.Security.Cryptography.Xml` or `System.Security.Cryptography.Pkcs`?

**Comment by Eilon** [comment]
@muratg might be a good idea to send mail too.

**Comment by natemcmaster** [comment]
Assigning to myself. Root cause is packaging changes in corefx. We can unblock tests by upgrading master to netcoreapp3.0. https://github.com/aspnet/DataProtection/pull/324.

**Comment by aspnet-hello** [comment]
XmlCanRoundTrip [failed with about the same error](http://aspnetci/viewLog.html?buildId=545176&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
