### ISSUE TITLE
Test failure: CanValidateMixDataAnnotations

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#3506]
This test [fails](http://aspnetci/viewLog.html?buildId=545178&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Expected: DataAnnotation validation failed for members Dep1, Dep2 with the error 'Dep1 != Dep2'.
DataAnnotation validation failed for members Required with the error 'The Required field is required.'.
DataAnnotation validation failed for members StringLength with the error 'Too long.'.
DataAnnotation validation failed for members IntRange with the error 'Out of range.'.
DataAnnotation validation failed for members Custom with the error 'The field Custom is invalid.'. - I don't want to go to nowhere!
Expected: True
Actual:   False
   at Microsoft.Extensions.Options.Tests.OptionsBuilderTest.ValidateFailure[TOptions](OptionsValidationException e, String name, String[] errors) in /_/test/Microsoft.Extensions.Options.Test/OptionsBuilderTest.cs:line 399
   at Microsoft.Extensions.Options.Tests.OptionsBuilderTest.CanValidateMixDataAnnotations() in /_/test/Microsoft.Extensions.Options.Test/OptionsBuilderTest.cs:line 616
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@HaoK can you take a look?

cc @ajcvickers

**Comment by Eilon** [comment]
Yeah I don't really see how that could happen... these tests presumably have no races in them...

**Comment by HaoK** [comment]
Yeah nothing too special here, i would assume data annotations validates the properties in a deterministic order, that would be the only thing I could think of that might change

The datavalidation is just calling  Validate using the DataAnnotations class:

```C#
        public ValidateOptionsResult Validate(string name, TOptions options)
        {
            // Null name is used to configure all named options.
            if (Name == null || name == Name)
            {
                var validationResults = new List<ValidationResult>();
                if (Validator.TryValidateObject(options,
                    new ValidationContext(options, serviceProvider: null, items: null), 
                    validationResults, 
                    validateAllProperties: true))
                {
                    return ValidateOptionsResult.Success;
                }

                return ValidateOptionsResult.Fail(String.Join(Environment.NewLine,
                    validationResults.Select(r => "DataAnnotation validation failed for members " +
                        String.Join(", ", r.MemberNames) +
                        " with the error '" + r.ErrorMessage + "'.")));
            }

            // Ignored if not validating this instance.
            return ValidateOptionsResult.Skip;
        }

        [Fact]
        public void CanValidateMixDataAnnotations()
        {
            var services = new ServiceCollection();
            services.AddOptions<AnnotatedOptions>()
                .Configure(o =>
                {
                    o.StringLength = "111111";
                    o.IntRange = 10;
                    o.Custom = "nowhere";
                    o.Dep1 = "Not dep2";
                })
                .ValidateDataAnnotations()
                .Validate(o => o.Custom != "nowhere", "I don't want to go to nowhere!");

            var sp = services.BuildServiceProvider();

            var error = Assert.Throws<OptionsValidationException>(() => sp.GetRequiredService<IOptions<AnnotatedOptions>>().Value);
            ValidateFailure<AnnotatedOptions>(error, Options.DefaultName, 
                @"DataAnnotation validation failed for members Required with the error 'The Required field is required.'.
DataAnnotation validation failed for members StringLength with the error 'Too long.'.
DataAnnotation validation failed for members IntRange with the error 'Out of range.'.
DataAnnotation validation failed for members Custom with the error 'The field Custom is invalid.'.
DataAnnotation validation failed for members Dep1, Dep2 with the error 'Dep1 != Dep2'.",
                "I don't want to go to nowhere!");
        }
```

**Comment by Eilon** [comment]
Deterministic order? I think not. It's presumably in Reflection order, which is presumably random. But that's just a guess.

**Comment by Eilon** [comment]
The only DataAnnotations thing that I think is guaranteed is that it will run all RequiredAttribute's on a property first, and only if that passes, it would then run all the non-RequiredAttribute's, but within each group, presumably a random order.

**Comment by Eilon** [comment]
Why does the test failure not show the expected/actual text, though? It just shows true/false?

**Comment by Eilon** [comment]
OIC because it's checking that an exception was thrown with that exact message....

**Comment by Eilon** [comment]
I wonder if one other improvement to the test is to change this line of code:

https://github.com/aspnet/Options/blob/53e879f400d93e88f209cc8ad1e4fac36e55f63f/test/Microsoft.Extensions.Options.Test/OptionsBuilderTest.cs#L398

And instead of using LINQ's SequenceEqual method, to use an xUnit assertion that shows a more detailed error?

**Comment by HaoK** [comment]
Yeah this looks like an ordering failure due to the data annotations error
