### ISSUE TITLE
how to access a remote shared folder with credential in asp.net core ?

### ISSUE THREAD

**Issue by tangname** [aspnet/Home#3515]
i  want to access a remote shared folder with credential,neither my app server nor remote file sever is in domain.

i notice that asp.net core use  under code to specify a local path:
```
app.UseStaticFiles(new StaticFileOptions()
{
    FileProvider = new PhysicalFileProvider("C:\\Files"),
    RequestPath = "/files"
});
```
then i can browser `localhost:5000/files/test.jgp` to view a file.

but now i need to aceess a  remote server file with credential,.

i instead of the '"C:\\Files' to '\\\\10.1.0.10\files',unfortually,it thow an exception: `The directory name \\10.1.0.10\files is invalid.`

detail error shows under: 
```
System.ArgumentException: The directory name \\10.1.0.10\files is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at WU.OnlineReport.Web.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\work\Report.Web\Startup\Startup.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
How can I resolve this problem ?

**Comment by Tratcher** [comment]
For IIS hosted apps: https://stackoverflow.com/questions/1496068/asp-net-read-files-from-a-password-protected-network-share

**Comment by tangname** [comment]
@Tratcher  thanks! I'm at home now and have no dev enviroment.I'll try it next monday.

**Comment by Tratcher** [comment]
@tangname running your web app as admin is very dangerous. Find a more restricted account you can use.
