### ISSUE TITLE
Access to IServiceProvider/Startup used by TestServer

### ISSUE THREAD

**Issue by phatcher** [aspnet/Home#3575]
Is it possible to get access to the IServiceProvider and/or the Startup class used by TestServer.

I'm trying to write some tests that confirm if service dependencies have been registered correctly in the underlying container.

**Comment by Eilon** [comment]
@javiercn - any idea on this?

**Comment by Tratcher** [comment]
TestServer.Host.Services?

**Comment by Tratcher** [comment]
That's a low level networking error, it shouldn't be related to anything in the service container. Is this Azure App Service using IIS & Kestrel? Did you modify Program.Main at all?

**Comment by phatcher** [comment]
It's a standard App Service Plan so I presume it's using Kestrel/IIS, the Program.Main is fairly standard...
```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseApplicationInsights()
            .UseStartup<Startup>();
}
```
I'm using Simple.OData.Client, which is creates it's own HttpClient, to talk to my REST Api, it runs ok locally indefinitely but on Azure about 10 mins after I bounce the App Service Plan I start getting socket errors. 

I was guessing at port exhaustion, but I'm not getting any Azure alerts and I don't know if I can find open  connections via Kudu?

I'm trying to work around the multiple HttpClient creations by using AddHttpClient but this is complicated by needing to provide OAuth tokens on a per-user basis.

**Comment by javiercn** [comment]
@phatcher Why don't you write a unit test instead?

```csharp
// arrange
var services = new ServiceCollection();
var startup = new Startup();

// act
startup.ConfigureServices(services);

// assert
Assert.Contains(services, sd => sd.ServiceType == typeof(MyType));
```

**Comment by Tratcher** [comment]
> but this is complicated by needing to provide OAuth tokens on a per-user basis.

?

**Comment by phatcher** [comment]
@Tratcher What I'm not sure of at the moment is whether my client code, which wrappers Simple .OData.Client and was ported from .NET Framework and has been running for ~2 years, is sharing HttpClient instances inappropriately leading to the socket errors, so I'm trying to re-write using the AddHttpClient helpers...

The REST api is secured using OAuth 2.0, so each request from the web app has to have a bearer authentication token appropriate to the current user, this is delivered (eventually there's about 3 more layers in the way)  by a class that uses the MsalSessionCache e.g.
```
private async Task<string> GetTokenAsync(ClaimsPrincipal principal = null, IList<string> scope = null)
{
    var context = httpContextAccessor.HttpContext;

    principal = principal ?? context.User;

    var scopes = openIdOptions.ApiScopes.Split(' ');
    var signedInUserId = principal.FindFirstValue(ClaimTypes.NameIdentifier);
    if (!string.IsNullOrEmpty(signedInUserId))
    {
	var userTokenCache = new MSALSessionCache(signedInUserId, context).GetMsalCacheInstance();
	var cca = new ConfidentialClientApplication(openIdOptions.ClientId, openIdOptions.Authority, openIdOptions.RedirectUri, new ClientCredential(openIdOptions.ClientSecret), userTokenCache, null);
	var user = cca.Users.FirstOrDefault();

	// Check as we can have a signed in user but cca.Users is null
	if (user != null)
	{
	    var result = await cca.AcquireTokenSilentAsync(scopes, user, openIdOptions.Authority, false);

	    // Prefer the access token but give back the id if not present
	    return result.AccessToken ?? result.IdToken;
	}
    }

    return null;
}
```

**Comment by phatcher** [comment]
@javiercn I have unit tests like this already but as this seems to be a server configuration issue I was trying to see how I could get to the service configuration that is actually running i.e. a form of integration testing of the configuration.

**Comment by Tratcher** [comment]
Your cache doesn't seem to cache anything since you recreate it on every call.

What do you do with the AccessToken once you have it? Add it to a request? How?

**Comment by phatcher** [comment]
@Tratcher It creates a cache for the duration of the request and handles token refresh - I didn't write this directly it's the recommended MS code for how to handle Azure B2C OAuth tokens; I agree that it looks odd but it seems to lookup/store the MSALSessionCache against the HttpContext.   I am surprised that we are given sample code rather than a library for this since every app that wants to talk to a secured API needs this, and it would be good if it used one of the caches rather than being invoked per request.

It does seem to work in that I can see a single call out to MS to get the token on the first request on the page and then subsequent calls are cached. 

Simple.OData.Client allows for a BeforeRequest delegate which allows me to put the token into the header, for the re-write I'm implementing this as a delegating handler which takes a IHttpContextAccessor to get to the current user - this is then passed in to the class that produces the token and I put it in the header in the same way.

**Comment by phatcher** [comment]
Ok, with the re-write the incidence of the socket error has greatly reduced but I am still getting some occasionally, is there anyway of seeing these with .NET Core as ServicePointManager doesn't work?

Happy to raise a different issue as the original query has been answered

**Comment by Tratcher** [comment]
Stack trace?

**Comment by phatcher** [comment]
The call from my app is just a standard http get to retrieve OData metadata, e.g. ` GET /api/odata/asset/$metadata` - this works 99.9% of the time but occasionally it fails and I get a HttpRequestException reported in Application Insights..

```
System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```
There are webjobs in the same app service plan and [#1876](https://github.com/Azure/azure-webjobs-sdk/issues/1876) seems to be similar (see last two comments), what I'm not sure is whether this error gets raised per endpoint you talk to, or across all outbound requests.

The endpoint I'm trying to talk to is in the same app service plan and is actually a virtual application within the same web site.

**Comment by Tratcher** [comment]
Hmm, you should report that one to dotnet/corefx.
