### ISSUE TITLE
Test failure: TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#3577]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=566978&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) with the following error:

```
System.TimeoutException : Operation in TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally timed out at /_/test/Microsoft.AspNetCore.Http.Connections.Tests/WebSocketsTests.cs:166
   at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 38
   at Microsoft.AspNetCore.Http.Connections.Tests.WebSocketsTests.TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally() in /_/test/Microsoft.AspNetCore.Http.Connections.Tests/WebSocketsTests.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.131s] TestLifetime Information: Starting test TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally at 2018-10-02T23:14:59
| [0.250s] TestLifetime Information: Starting test TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally at 2018-10-02T23:15:00
| [5.972s] TestLifetime Information: Finished test TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally in 5.7223159s
| [7.004s] TestLifetime Information: Finished test TransportCommunicatesErrorToApplicationWhenClientDisconnectsAbnormally in 6.8794734s
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
@muratg - please assign.

**Comment by Tratcher** [comment]
Note this is actually a SignalR test. I've moved it to Brennan for now.
