### ISSUE TITLE
Unable to restore or run vNext application

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/Home#368]
Development platform: Windows Server 2012 R2 Datacenter (Azure Visual Studio Template CTP6 build)

All of the projects that I have been playing around with are no longer build in Visual Studio or at the command line. Let me use the simplest example. A web project with the following project.json:

```

{
    "dependencies": {
    
        "Kestrel": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-*",
        "Microsoft.AspNet.Hosting": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-*",

    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004"
    },
    "frameworks": {
	"aspnet50": {},
        "aspnetcore50": {}
	}
}

```

When attempting to run a kpm restore at the command line I get the following error:

```

C:\Git\vnhelloweb>kpm restore
Restoring packages for C:\Git\vnhelloweb\project.json
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Kestrel'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Kestrel'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Diagnostics'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Diagnostics'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Hosting'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Hosting'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Server.WebListener'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Server.WebListener'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'
Writing lock file C:\Git\vnhelloweb\project.lock.json
----------
System.ArgumentException: Can not add property Microsoft.AspNet.Hosting to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WritePackageDependencySet(PackageDependencySet item)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteLibrary(LockFileLibrary library)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteLockFile(LockFile lockFile)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write(Stream stream, LockFile lockFile)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write(String filePath, LockFile lockFile)
   at Microsoft.Framework.PackageManager.RestoreCommand.WriteLockFile(String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass89_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext()
----------
Restore failed
Can not add property Microsoft.AspNet.Hosting to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.

C:\Git\vnhelloweb>

***

This seems to be happening across my projects. I tried to get the development version of the KVM (that has helped in the past when things break):

***

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))}"

***

...but that fails with the error:

***

Using temporary directory: C:\Users\tdu\AppData\Local\Temp\2\kvminstall
Downloading from https://raw.githubusercontent.com/aspnet/Home/dev
Downloading KVM.ps1 to C:\Users\tdu\AppData\Local\Temp\2\kvminstall\kvm.ps1
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:16 char:1
+ $webClient.DownloadFile("$BaseUrl/kvm.ps1", $kvmPs1Path)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Downloading KVM.cmd to C:\Users\tdu\AppData\Local\Temp\2\kvminstall\kvm.cmd
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:18 char:1
+ $webClient.DownloadFile("$BaseUrl/kvm.cmd", $kvmCmdPath)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Installing KVM
& : The term 'C:\Users\tdu\AppData\Local\Temp\2\kvminstall\kvm.cmd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:20 char:3
+ & $kvmCmdPath setup
+   ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\tdu\Ap...install\kvm.cmd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

I can see some changes came in over the weekend moving from kvm to dnvm, but I am not sure if that is related to this. I am a bit stuck. Any help would be much appreciated. Here are the KRE's installed on my machine:

```

C:\Git\vnhelloweb>kvm list

Active Version           Runtime Architecture Location                 Alias
------ -------           ------- ------------ --------                 -----
       1.0.0-beta3       clr     x64          C:\Users\tdu\.k\runtimes
       1.0.0-beta3       clr     x86          C:\Users\tdu\.k\runtimes
       1.0.0-beta3       coreclr x64          C:\Users\tdu\.k\runtimes
       1.0.0-beta3       coreclr x86          C:\Users\tdu\.k\runtimes
       1.0.0-beta4-11169 clr     x86          C:\Users\tdu\.k\runtimes
       1.0.0-beta4-11169 coreclr x86          C:\Users\tdu\.k\runtimes
  *    1.0.0-beta4-11181 clr     x86          C:\Users\tdu\.k\runtimes default
       1.0.0-beta4-11181 coreclr x86          C:\Users\tdu\.k\runtimes

```

**Comment by victorhurdugaci** [comment]
@ChengTian I've seen a similar issue yesterday while restoring the MVC package. I think there is a bug there...

**Comment by davidfowl** [comment]
There's no bug here. You can't use k/kre/kvm with the newest packages, it doesn't understand the DNX TFMs.

@jsacapdev You need to download the dnvm from the Home repository or stick to packages that existed before last friday.

**Comment by cherrydev** [comment]
Come on, folks.  This is the second time in as many months that the dev branch has had a complete and total compatibility break with current dev tools and that users of it were provided no notification or instructions about it.  To top it off, all of the associated packages were changed so that they will only work with DNX, but there was no semantic version change.  "You'll have to use the packages that existed before last friday" is not terribly helpful when the packages from before last friday and today are BOTH -beta4-11xxx packages!  What other realistic option do we have other than back-tracking entirely to beta3?
I've installed DNX and of course Visual Studio has no idea what to do with it.  Junctioning .dnx to .k doesn't help this time (as it did for the .kvm to .k change).
While obviously we're playing with the bleeding edge here and have no expectation of things being stable, I also want to point out that there's obviously value in having a significant number of developers involved with the dev branch and I imagine that this is going to cause a significant number of those developers to drop it.
Therefore I have a few questions:

1) Is there a list of packages, or a dedicated feed that will provide us with the latest versions of the "kvm"-compatible packages before they all switched to DNX?
2) Is there any known way of getting DNX working with Visual Studio?
3) If not, is there any sort of ETA for when that's going to happen?
4) Is there some sort of place where people can look for announcements and have discussions about major changes like this, so that we can have some sort of warning or information?  I would imagine that the Home page would be a place for this, but no information gets posted on there.
5) **For those of us who have been using the dev branch with Visual Studio, do we have absolutely any recourse other than just waiting, or dropping back to beta-3 packages, which are now months old?**
6) **If the answer is no, should we expect that major compatibility breakages like this will be the norm from now on and that we should not expect it to be usable with Visual Studio until the next master release?  Has there been a conscious decision by the project leads that this is a compromise that's for the greater good of the project, assuming that each time this happens you lose a major chunk of the devs using Visual Studio?**

I've been in the beginning stages of starting a major project with the assumption that aspnet5 will be production ready around the time when the project is completed (in another 6-9 months) and while I've been having very good experiences with the state of most of the frameworks themselves (excluding EF7, which we're probably dropping) the constant state of flux of the runtime and build tools has been making this experience feel pretty excruciating over the last few months (since the .kvm to .k switchover).

**Comment by cherrydev** [comment]
This video answers most of the questions:

https://www.youtube.com/watch?v=-qt0POsiAF8

So far the answers seem like:

1) No
2) No
3) No
5) Not really

**Comment by davidfowl** [comment]
I'll see if we can get a list of package versions that work.

**Comment by cherrydev** [comment]
Thanks.  You've probably seen that I've created issue #377 specifically for that.
