### ISSUE TITLE
failing nuget package restore with unreachable server

### ISSUE THREAD

**Issue by vermegi** [aspnet/Home#374]
In my package sources I have an additional package source listed, which is unreachable once not connected to the corporate network. I also have the official nuget package source listed. Once I open a solution, it will try and restore my nuget packages, but it fails doing this, since it keeps on complaining about the unreachable corporate network server. As a result of this any Bower packages will fail to restore as well.

Unchecking the unreachable server in my nuget package sources solves the problem.

Output:

```
Restoring packages for d:\Documents\Visual Studio 2015\Projects\WebApplication1\src\WebApplication1\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Runtime'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Text.Encoding'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Text.Encoding'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Threading.Tasks'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Collections'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Globalization'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Globalization'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Reflection'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.IO'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.ObjectModel'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.ObjectModel'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Xml.ReaderWriter'
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Xml.ReaderWriter'.
Warning: FindPackagesById: System.Text.Encoding
  An error occurred while sending the request.
Warning: FindPackagesById: System.Threading.Tasks
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Text.Encoding'.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Threading.Tasks'.
Warning: FindPackagesById: System.Runtime
  An error occurred while sending the request.
Warning: FindPackagesById: System.Collections
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Runtime'.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Collections'.
Warning: FindPackagesById: System.Globalization
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Globalization'.
Warning: FindPackagesById: System.Reflection
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Reflection'.
Warning: FindPackagesById: System.IO
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.IO'.
Warning: FindPackagesById: System.ObjectModel
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.ObjectModel'.
Warning: FindPackagesById: System.Xml.ReaderWriter
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Xml.ReaderWriter'.
Warning: FindPackagesById: System.Threading.Tasks
  An error occurred while sending the request.
Warning: FindPackagesById: System.Collections
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Threading.Tasks'.
Warning: FindPackagesById: System.Globalization
  An error occurred while sending the request.
Warning: FindPackagesById: System.Text.Encoding
  An error occurred while sending the request.
Warning: FindPackagesById: System.Runtime
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Text.Encoding'.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Runtime'.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Globalization'.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Collections'.
Warning: FindPackagesById: System.Reflection
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Reflection'.
Warning: FindPackagesById: System.IO
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.IO'.
Warning: FindPackagesById: System.ObjectModel
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.ObjectModel'.
Warning: FindPackagesById: System.Xml.ReaderWriter
  An error occurred while sending the request.
  GET http://10.100.162.13/nuget/nuget/FindPackagesById()?Id='System.Xml.ReaderWriter'.
Error: FindPackagesById: System.Globalization
  An error occurred while sending the request.
Error: FindPackagesById: System.Runtime
  An error occurred while sending the request.
----------
Error: FindPackagesById: System.Reflection
  An error occurred while sending the request.
Error: FindPackagesById: System.Collections
  An error occurred while sending the request.
Error: FindPackagesById: System.Threading.Tasks
  An error occurred while sending the request.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.100.162.13:80
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource.<GetAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.PackageFeed.<FindPackagesByIdAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibraryBySnapshot>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibraryByVersion>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__1.MoveNext()
----------
Restore failed
An error occurred while sending the request.
Error: FindPackagesById: System.Text.Encoding
  An error occurred while sending the request.
Error: FindPackagesById: System.IO
  An error occurred while sending the request.
```

**Comment by muratg** [comment]
This is by design.  Use ```kpm restore --ignore-failed-sources``` to ignore unreachable sources.

We have a work item to improve the error message and make this command line option more discoverable.  https://github.com/aspnet/DNX/issues/1271
