### ISSUE TITLE
AmbiguousMatchException when starting ASP.NET 5 Web Application

### ISSUE THREAD

**Issue by rausmaus** [aspnet/Home#402]
Starting a web application with multiple `Configure` overloads in `Startup.cs` causes a `AmbigousMatchException`.

Here is the stack trace.

    System.Reflection.AmbiguousMatchException: Ambiguous match found.
       at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
       at System.Type.GetMethod(String name, BindingFlags bindingAttr)
       at System.Reflection.TypeInfo.GetDeclaredMethod(String name)
       at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindMethod(Type startupType, String methodName, String environmentName, Type returnType, Boolean  required)
       at Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadStartup(String applicationName, String environmentName, IList`1 diagnosticMessages)
       at Microsoft.AspNet.Hosting.Startup.StartupManager.LoadStartup(String applicationName, String environmentName)
       at Microsoft.AspNet.Hosting.HostingEngine.EnsureApplicationStartup(HostingContext context)
       at Microsoft.AspNet.Hosting.HostingEngine.EnsureApplicationDelegate(HostingContext context)
       at Microsoft.AspNet.Hosting.HostingEngine.Start(HostingContext context)
       at Microsoft.AspNet.Hosting.Program.Main(String[] args)

This is probably "by design", but the Exception does not provide much information about what the underlaying cause is.

My suggestion is to wrap the `AmbigousMatchException` that occurs in another `Exception`, possibly a `NotSupportedException` or similar, with some further information.

See my [StackOverflow](http://stackoverflow.com/questions/29185164/ambiguousmatchexception-when-starting-asp-net-5-mvc-6-web-application/29185375) question for more information.

**Comment by davidfowl** [comment]
@rausmaus Can you file a bug on https://github.com/aspnet/Hosting

**Comment by rausmaus** [comment]
@davidfowl will do!
