### ISSUE TITLE
dnu restore linux PlatformNotSupportedException

### ISSUE THREAD

**Issue by worfox** [aspnet/Home#559]
$ dnu restore
System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()

This is running 1.0.0-beta5-11624, there is the same problem with 11682 with the coreclr and on arch x64. I am using Arch Linux.

**Comment by davidfowl** [comment]
Known issue dnu + coreclr aren't friends yet.

**Comment by worfox** [comment]
Alright sorry, I didn't see any already open issues about this. Is there any workaround?

**Comment by davidfowl** [comment]
Yes, use mono to dnu restore.
