### ISSUE TITLE
ArgumentNullException dnu restore with coreclr on Mac

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Home#598]
I'm using yeoman on Mac to generate a project. Running `yo aspnet` and choosing 'Web Application'. Then when running `dnu restore` I get the following exception:

```
----------
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.SettingsUtils.ReadSettings(String solutionDir, String nugetConfigFile, IFileSystem fileSystem, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadSettings(String solutionDirectory)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__72.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: path1
```

I am using 1.0.0-beta5-11760 of the coreclr runtime x64 and the beta4 release of ASP.NET

I have an alias for the mono package so `dmvm use mono` and a `dnu restore` with this, everything works as normal.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/dnx/issues/1793

**Comment by damienpontifex** [comment]
Thanks
