### ISSUE TITLE
 [Microsoft.Net.Http.Server.WebListener] Start System.MissingMethodException: Method not found: 'Int32 

### ISSUE THREAD

**Issue by ballwood** [aspnet/Home#600]
Trying to start the server on windows via dnx . web and getting the following error.

error   : [Microsoft.Net.Http.Server.WebListener] Start
System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Microsoft.Net.Http.Server.WebListener.SetRequestQueueLimit()
   at Microsoft.Net.Http.Server.WebListener.Start()
System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Microsoft.Net.Http.Server.WebListener.SetRequestQueueLimit()
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNet.Server.WebListener.MessagePump.Start(Func`2 app)
   at Microsoft.AspNet.Server.WebListener.ServerFactory.Start(IServerInformation
 server, Func`2 app)
   at Microsoft.AspNet.Hosting.HostingEngine.Start(HostingContext context)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)

**Comment by davidfowl** [comment]
Whenever I see method missing I think version mismatch of your packages. Is everything beta4?

/cc @Tratcher

**Comment by ballwood** [comment]
Think so: my dnx package repository contains the following.

C:\Users\ballwood\.dnx\packages\Microsoft.Net.Http.Server\1.0.0-beta4
"dnu list" on the project contains - Microsoft.AspNet.Server.WebListener 1.0.0-beta4.

Trying to start up by using dnx . web. 
Additionally tried to use kestrel under windows but was getting libuv errors and C++ compiler errors.

Regards,

Barry

**Comment by Tratcher** [comment]
https://github.com/aspnet/Home/issues/632
