### ISSUE TITLE
MissingMethodException on Microsoft.Net.Http.Server.WebListener

### ISSUE THREAD

**Issue by MaximRouiller** [aspnet/Home#632]
The machine does not have Visual Studio 2015.
Project created using the latest `generator-aspnet` and latest yeoman package.
`.dnx` folder completely deleted and completely reinstalled.

`dnu restore` executed. Package `Microsoft.Net.Http.Server` only have one version and it's `1.0.0-beta4`.

I run `dnx . web` / `dnx . kestrel` on the same port and I get the following:

![capture](https://cloud.githubusercontent.com/assets/209384/7800133/a4228852-02de-11e5-862a-3338982aaef8.PNG)

They are not running "at the same time". One after the other after the process is killed.

Here are the commands in my `project.json` file:

```json
"commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5002",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5002",
        "gen": "Microsoft.Framework.CodeGeneration",
        "ef": "EntityFramework.Commands"
    }
```

Thanks

**Comment by Tratcher** [comment]
Did you run this using CLR or CoreCLR? I'd guess this only repros for CoreCLR.

**Comment by Tratcher** [comment]
This appears to be working fine on beta6. Can you try again?

**Comment by MaximRouiller** [comment]
Trying now.

**Comment by MaximRouiller** [comment]
Well.... I think there is too much things that change to say that it works or not. 

![capture](https://cloud.githubusercontent.com/assets/209384/8189405/19cee396-142a-11e5-9c99-2305566a0692.PNG)

That is using the current Yeoman generator for aspnet (generator-aspnet)

**Comment by Tratcher** [comment]
Make sure you're using dnx beta6 with the beta6 packages.

**Comment by MaximRouiller** [comment]
Right... this again :P 

Clearing and reinstalling packages

**Comment by MaximRouiller** [comment]
So first, I added the aspnetwebstacknightly feed, removed the "packages" cache in my `.dnx` folder.

Ran `dnu restore`. Waited... waited... waited... 

Restore failed with this:

```
Done, without errors.
Restore complete, 107303ms elapsed
Errors in C:\_prototypes\MyApp\project.json
    Unable to locate Newtonsoft.Json >= 6.0.6
    Unable to locate System.Collections.Immutable >= 1.1.36
    Unable to locate System.Reflection.Metadata >= 1.0.21
    Unable to locate Remotion.Linq >= 2.0.0-alpha-002
    Unable to locate System.Collections.Immutable >= 1.1.34-rc
    Unable to locate Ix-Async >= 1.2.3
```
Running `dnx . web` would fail with this message:

```
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
   Ix-Async 1.2.3
   Newtonsoft.Json 6.0.6
   Remotion.Linq 2.0.0-alpha-002
   System.Collections.Immutable 1.1.34-rc
   System.Reflection.Metadata 1.0.21
```

So I decided to cross the streams and added myget nightly AND nuget current to ensure that everything would work.

Nope. Still not running. I'm guessing that the `project.json` would need to have the proper dependencies on it to run. So yeah... I'm in package hell. :P

**Comment by Tratcher** [comment]
You need both nuget.org and https://www.myget.org/F/aspnetvnext/api/v2 feeds. You also need to do `dnvm upgade -u` to get the beta6 version of dnx.

**Comment by MaximRouiller** [comment]
Alright. Strike 2. :P let's do this again.

**Comment by MaximRouiller** [comment]
`.dnx/packages` and `.dnx/runtimes` were deleted prior to running `dnvm upgrade -u`

Current runtimes:
```
Active Version           Runtime Architecture Location                       Alias
------ -------           ------- ------------ --------                       -----
  *    1.0.0-beta6-12081 clr     x86          C:\Users\mrouill\.dnx\runtimes default
```

Current feed:
```xml
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="nuget.org2" value="https://www.myget.org/F/aspnetvnext/api/v2" />
  </packageSources>
```

Ran `dnu restore`. No issues. Restore complete and no red text.

Ran my app. Same error as before. `No service for type `Microsoft.Framework.Runtime.IApplicationEnvironment`.

**Comment by Tratcher** [comment]
And your project.json dependencies?

**Comment by MaximRouiller** [comment]
Didn't touch them. Should I?

Here they are:

```json
"dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta4",
        "EntityFramework.Commands": "7.0.0-beta4",
        "Microsoft.AspNet.Mvc": "6.0.0-beta4",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.UserSecrets": "1.0.0-beta4",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4",
        "Microsoft.Framework.Logging": "1.0.0-beta4",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta4",
        "Kestrel": "1.0.0-beta4"
    }
```

**Comment by Tratcher** [comment]
Yeah, move all the `-beta4` items to `-beta6-*` or just `-*`. I'm trying to see if you can still reproduce your original issue on beta6 packages and runtime.

**Comment by MaximRouiller** [comment]
Replaced `-beta4` to `-*`

Ran `dnu restore` again. Successfull. No "red".

Ran `dnx . web`. Result: 
```
C:\_prototypes\MyApp>dnx . web
System.IO.FileLoadException: Could not load file or assembly 'MyApp' or one of its dependencies. General Exception (Exce
ption from HRESULT: 0x80131500)
File name: 'MyApp' ---> Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: C:\_prototypes\MyApp\Migrations\0
00000000000000_CreateIdentitySchema.cs(160,32): error CS0115: 'CreateIdentitySchema.Target': no suitable method found to
 override
C:\_prototypes\MyApp\Migrations\ApplicationDbContextModelSnapshot.cs(16,32): error CS0115: 'ApplicationDbContextModelSna
pshot.Model': no suitable method found to override
C:\_prototypes\MyApp\Migrations\ApplicationDbContextModelSnapshot.cs(14,19): error CS0534: 'ApplicationDbContextModelSna
pshot' does not implement inherited abstract member 'ModelSnapshot.BuildModel(ModelBuilder)'
C:\_prototypes\MyApp\Migrations\ApplicationDbContextModelSnapshot.cs(20,35): error CS0246: The type or namespace name 'B
asicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)
C:\_prototypes\MyApp\Migrations\000000000000000_CreateIdentitySchema.cs(164,35): error CS0246: The type or namespace nam
e 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)
C:\_prototypes\MyApp\Startup.cs(52,45): error CS1503: Argument 2: cannot convert from 'Microsoft.Framework.Configuration
Model.IConfiguration' to 'System.Action<MyApp.AppSettings>'
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext load
Context)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Ass
embly& assembly)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Runtim
eAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Runtime
Assembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntros
pection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, Ru
ntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessa
ges)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)


Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: C:\_prototypes\MyApp\Migrations\000000000000000_CreateIde
ntitySchema.cs(160,32): error CS0115: 'CreateIdentitySchema.Target': no suitable method found to override
C:\_prototypes\MyApp\Migrations\ApplicationDbContextModelSnapshot.cs(16,32): error CS0115: 'ApplicationDbContextModelSna
pshot.Model': no suitable method found to override
C:\_prototypes\MyApp\Migrations\ApplicationDbContextModelSnapshot.cs(14,19): error CS0534: 'ApplicationDbContextModelSna
pshot' does not implement inherited abstract member 'ModelSnapshot.BuildModel(ModelBuilder)'
C:\_prototypes\MyApp\Migrations\ApplicationDbContextModelSnapshot.cs(20,35): error CS0246: The type or namespace name 'B
asicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)
C:\_prototypes\MyApp\Migrations\000000000000000_CreateIdentitySchema.cs(164,35): error CS0246: The type or namespace nam
e 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)
C:\_prototypes\MyApp\Startup.cs(52,45): error CS1503: Argument 2: cannot convert from 'Microsoft.Framework.Configuration
Model.IConfiguration' to 'System.Action<MyApp.AppSettings>'
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext load
Context)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Ass
embly& assembly)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

```

**Comment by MaximRouiller** [comment]
Same result with kestrel.

**Comment by Tratcher** [comment]
Ok, that just looks like some API changes between beta4 and beta6. You should be able to comment out most of that code for the sake of this experiment.

**Comment by MaximRouiller** [comment]
Alright... so I'm running the `dnu build --quiet` and found the files where the issue happened.

Commented out all Migrations.  Also commented out the following in the Startup.cs since it looks like there was a signature change:

```cs
services.Configure<AppSettings>(Configuration.GetSubKey("AppSettings"));
```

Now it builds. Let's try the dnx . web:

```
C:\_prototypes\MyApp>dnx . web
System.InvalidOperationException: Unable to resolve path 'config.json'; construct this IConfigurationSourceRoot with a n
on-null BasePath.
   at Microsoft.Framework.ConfigurationModel.Helper.ConfigurationHelper.ResolveConfigurationFilePath(IConfigurationSourc
eRoot configuration, String path)
   at Microsoft.Framework.ConfigurationModel.JsonConfigurationExtension.AddJsonFile(IConfigurationSourceRoot configurati
on, String path, Boolean optional)
   at Microsoft.Framework.ConfigurationModel.JsonConfigurationExtension.AddJsonFile(IConfigurationSourceRoot configurati
on, String path)
   at MyApp.Startup..ctor(IHostingEnvironment env) in C:\_prototypes\MyApp\Startup.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider prov
ider)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instance
Type, Object[] parameters)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, T
ype type)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadMethods(Type startupType, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

```

**Comment by Tratcher** [comment]
You can compare to the updated templates for breaking changes like this:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L23

**Comment by MaximRouiller** [comment]
404

**Comment by MaximRouiller** [comment]
In any case.... I removed the `AddJsonFile` and I endup with the following:

```
error   : [Microsoft.Net.Http.Server.WebListener] Start
System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Microsoft.Net.Http.Server.WebListener.SetRequestQueueLimit()
   at Microsoft.Net.Http.Server.WebListener.Start()
System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Microsoft.Net.Http.Server.WebListener.SetRequestQueueLimit()
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNet.Server.WebListener.MessagePump.Start(Func`2 app)
   at Microsoft.AspNet.Server.WebListener.ServerFactory.Start(IServerInformation server, Func`2 app)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

**Comment by Tratcher** [comment]
Sorry, that was a private repo link.

Thanks for going through all of that. It's strange I can't reproduce this issue locally. I'll play with it some more and see if I can get it to break.

**Comment by MTRo** [comment]
Hi. I had the same issues regarding MissingMethodExpectin.
When I change a runtime to CoreCLR versions then it was disappeared.

I tried to check 3 of version of runtime.
1) 1.0.0-beta4 clr x86
2) 1.0.0-beta4 clr x64
3) 1.0.0-beta4 coreclr x86
4) 1.0.0-beta4 coreclr x64

3 and 4 was OK. but 1 and 2 doesn't work.

And also, I don't have VisualStudio 2015.

**Comment by MTRo** [comment]
Hi, Again.
I tried to check with the PC that has Visual Studio 2015.
It was OK in every 1 to 4 situations on exact same project as previous post.

I'm using Windows7 64bit in both cases with following project.json.
I hope this is useful information for you guys.

{
    "userSecretsId": "thas_was_super_interesting",
    "webroot": "wwwroot",
    "version": "1.0.0-*",

    "dependencies": {
        "Microsoft.AspNet.Mvc": "6.0.0-beta4",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
        "Typescript.Compiler": "2.0.0"
    },

    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
    },

    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    },

    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ],
    "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ]
}

**Comment by Tratcher** [comment]
I'd done some cleanup that should address this. Please try again with Microsoft.AspNet.Server.WebListener 1.0.0-beta6-12326 or later, which should be available later today.
