### ISSUE TITLE
Visual Studio RC 2015 Enterprise Crashes Constantly with project loaded in with Bower and NPM packages already loaded in the tree

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Home#635]
I wanted to check if my grunt task processes would now be able to run with the new VS RC 2015 and I couldn't even get the project to load into VS.  I do get an error message but this is far from stable as the previous CTP 6 version was.  

Any thoughts? 

https://github.com/xtianus79/generator-aspnet  this git repo is different than the npm package as I work out the issues. so if you npm install -g xtianus79/generator-aspent will install the git version

@madskristensen @davidfowl

**Comment by xtianus79** [comment]
Any word on this?

**Comment by xtianus79** [comment]
here is the file that generated @madskristensen @davidfowl 

    =====================
5/27/2015 8:49:40 PM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The request to update the project tree was rejected. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateExcludedItem(IProjectTree tree, String relativePath, String fullPath, Boolean alwaysInvisible)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__115.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass94_0.<<Initialize>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass101_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Utilities.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The request to update the project tree was rejected. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateExcludedItem(IProjectTree tree, String relativePath, String fullPath, Boolean alwaysInvisible)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__115.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass94_0.<<Initialize>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass101_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Utilities.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
