### ISSUE TITLE
dnu restore cannot restore with errors

### ISSUE THREAD

**Issue by joeizang** [aspnet/Home#663]
Hi,

dnu restore cannot restore after I do a yo aspnet generation of a web application. It restores most of the packages but it spits errors on NewtonSoft.Json 6.0.6 and Microsoft.CodeAnalysis.CSharp 1.0.0-rc and spits the following error in powershell:

Error: DownloadPackageAsync: https://www.nuget.org/api/v2/package/Microsoft.CodeAnalysis.CSharp/1.0.0-rc2
##   A task was canceled.

System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEn
coding)
   at Microsoft.Framework.PackageManager.PackageUtilities.<OpenNuspecStreamFromNupkgAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv2Feed.<OpenNuspecStreamAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<GetDependencies>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass73_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##    at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__73.MoveNext()

Restore failed
Value cannot be null.

**Comment by davidfowl** [comment]
This is on mono right?

**Comment by frialex** [comment]
This also happens on windows while running "dnu restore" on samples\HelloMvc"

There is a so post on it: http://stackoverflow.com/questions/30534632/asp-net-vnext-dnu-restore-error

**Comment by frialex** [comment]
Steps taken: 

1) delete ~/.dnx
2) reinstall dnvm, follow doc
3) download aspnet/home

4) cd aspnet/home/samples/latest/HelloMvc

5) dnu restore --no-cache

--crashes while "Writing lock file ... project.lock.json" ---

[Errors Thrown]
![image](https://cloud.githubusercontent.com/assets/1047886/8109242/a27d6056-1023-11e5-9159-6737388cf797.png)

[Old version of Newtonsoft.Json?]
![image](https://cloud.githubusercontent.com/assets/1047886/8109290/cdc27a80-1023-11e5-863e-efe926e746e7.png)

[Potential crash path?]
![image](https://cloud.githubusercontent.com/assets/1047886/8109312/ecf669ac-1023-11e5-9632-b5d31642d756.png)

**Comment by davidfowl** [comment]
Windows 7? That stack isn't very interesting. It looks like the wrong versions of things are being used or we have an OS incompatibility (based on that exception message you're getting)

**Comment by frialex** [comment]
Yep on Windows 7. The issue turned out to be that c:\users\..\.dnx\packages\Newtonsoft.Json\6.0.6 
had the same exact PublicKeyToken and assembly version ([assembly: AssemblyVersion("6.0.0.0")]).

The crash happens on the company laptop, which has the real Newtonsoft.Json version 6.0.0.0 GACed. 

The error message is spot on. The Newtonsoft.Json package needs to update its AssemblyVersion attribute

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
