### ISSUE TITLE
Bootstrapper Exception on IIS: The Main function returned unexpectedly ...

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#735]
For my ADAL on `dnxcore50` project (`dnx-coreclr-win-x64.1.0.0-beta6-12189`): When the first request hits the app after deployment, I'm getting:
```
    Exception type: SEHException 
    Exception message: External component has thrown an exception.
   at AspNet.Loader.Bootstrapper.<>c__DisplayClass2_0.<LoadApplicationK10>b__0(Object _)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNet.Loader.Bootstrapper.LoadApplicationK10(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize, String runtimePackagePath, String appBasePath)
   at AspNet.Loader.Bootstrapper.LoadApplication(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.ProcessHost.System.Web.Hosting.IProcessHostLite.ReportCustomLoaderError(String appId, Int32 hr, AppDomain newlyCreatedAppDomain)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
```
subsequent requests result in
```
    Exception type: Exception 
    Exception message: The Main function returned unexpectedly with status code -2146233079.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNet.Loader.Bootstrapper.LoadApplicationK10(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize, String runtimePackagePath, String appBasePath)
   at AspNet.Loader.Bootstrapper.LoadApplication(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.ProcessHost.System.Web.Hosting.IProcessHostLite.ReportCustomLoaderError(String appId, Int32 hr, AppDomain newlyCreatedAppDomain)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
```
Searching states that it's a symptom of something else in [Need investigation: Crossgen coreclr KRE will break the IIS hosted scenario - dnx/issues/1319](https://github.com/aspnet/dnx/issues/1319), which is the "path too long" issue, and [Downlevel App cannot start on full IIS - dnx/issues/793](https://github.com/aspnet/dnx/issues/793).

Dependencies are
```
"Microsoft.IdentityModel.Protocol.Extensions": "2.0.0-*",
"Microsoft.AspNet.Mvc": "6.0.0-*",
"Microsoft.AspNet.Authentication.Cookies": "1.0.0-*",
"Microsoft.AspNet.Diagnostics": "1.0.0-*",
"Microsoft.AspNet.Server.IIS": "1.0.0-*",
"Microsoft.AspNet.StaticFiles": "1.0.0-*",
"Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
"Microsoft.Framework.ConfigurationModel": "1.0.0-*",
"Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-*",
"Microsoft.AspNet.Identity": "3.0.0-*",
"Microsoft.AspNet.Http": "1.0.0-*",
"System.Runtime.Serialization.Json": "4.0.0-beta-*",
"Microsoft.IdentityModel.Clients.ActiveDirectory": "3.5.207081303-alpha"
```
This app runs fine from localhost ... it's failing on IIS 8 (WS 2012). I can put up a repo if that would help.

**Comment by GuardRex** [comment]
This turned out to be a mismatch between two runtime settings. When I upgrade my runtime, it's easy for me to remember that I need to update this one:
![capture1](https://cloud.githubusercontent.com/assets/1622880/8627622/d0463daa-2711-11e5-859c-07db4b9284a0.png)
... but I forgot the one buried in the Publish to Filesystem wizard. That wizard opens to the last panel (Preview), and the runtime setting is on the third panel (Settings). It's easy to miss.
![capture2](https://cloud.githubusercontent.com/assets/1622880/8627647/fed9a81e-2711-11e5-9499-8fcadff938d6.png)
@madskristensen Perhaps the DDL should default to the one in the project's properties. Wouldn't they always need to be set to the same runtime?

@davidfowl @Eilon Also, the exception here was completely opaque: A cryptic bootstrapper exception was reported when the deployed runtime (set by the project property) didn't match the one in the `Web.config` file generated for the project (set by the Publish to Filesystem wizard).
