### ISSUE TITLE
Could not find a part

### ISSUE THREAD

**Issue by jrock2004** [aspnet/Home#737]
I am running into all of these issues after upgrading to beta5 around finding a part of a file. Here is my most recent console output

```
Writing lock file C:\Development\testpro\test\test.Web\project.lock.js
on
----------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\User
s\costanzoj\.dnx\packages\NLog\3.1.0.0\NLog.3.1.0.0.nupkg.sha512'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detec
tEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean
 checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Framework.PackageManager.Utils.LockFileUtils.CreateLockFileLibra
ry(LockFileLibrary previousLibrary, IPackagePathResolver resolver, IPackage pack
age, String correctedPackageName)
   at Microsoft.Framework.PackageManager.RestoreCommand.WriteLockFile(LockFile p
reviousLockFile, String projectLockFilePath, Project project, List`1 graphItems,
 PackageRepository repository, IEnumerable`1 contexts)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__77
.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass76_0.<<
Execute>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__76.MoveNext(
)
----------
Restore failed
Could not find a part of the path 'C:\Users\costanzoj\.dnx\packages\NLog\3.1.0.0
\NLog.3.1.0.0.nupkg.sha512'.
```

I have tried deleteing the whole .dnx/packages directory and still same result

**Comment by tlk** [comment]
Perhaps #729 could be useful for you.

**Comment by tillig** [comment]
[Looks like this was fixed in beta 6.](https://github.com/aspnet/dnx/issues/2240)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
