### ISSUE TITLE
Running error 

### ISSUE THREAD

**Issue by GVX111** [aspnet/Home#769]
I made dnvm upgrade -u than dnu restore and there are some erros. dnx versions

```
------ -------           ------- ------------ --------                    -----
       1.0.0-beta4       clr     x86          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta5       clr     x64          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta5       clr     x86          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta5       coreclr x64          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta5       coreclr x86          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta7-12264 clr     x86          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta7-12274 clr     x64          C:\Users\Givi\.dnx\runtimes
  *    1.0.0-beta7-12274 clr     x86          C:\Users\Givi\.dnx\runtimes de...
```

Error

```
>dnx . web
System.IO.FileLoadException: Could not load file or assembly 'OrchardVNext, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
File name: 'OrchardVNext, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: C:\Users\Givi\Desktop\Brochard-Autofac-test\Brochard-master\src\OrchardVNext\Environment\DefaultAssemblyLoader.cs(68,55): DNX,Version=v4.5.1 error CS1501: No overload for method 'GetExportsRecursive' takes 5 arguments
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Assembly& assembly)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at OrchardVNext.Web.Startup.ConfigureServices(IServiceCollection services)
Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: C:\Users\Givi\Desktop\Brochard-Autofac-test\Brochard-master\src\OrchardVNext\Environment\DefaultAssemblyLoader.cs(68,55): DNX,Version=v4.5.1 error CS1501: No overload for method 'GetExportsRecursive' takes 5 arguments
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Assembly& assembly)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

**Comment by Eilon** [comment]
So you're using the latest `beta7` build of DNX - did you also update to the `beta7` versions of all the packages that  are being used in the project?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
