### ISSUE TITLE
OOM Exception in BrowserLink.Runtime

### ISSUE THREAD

**Issue by buddyspike** [aspnet/Home#795]
After about 48 hrs of continuous operation, my development server started to fail all requests with the following exception:

```
System.OutOfMemoryException
Exception of type 'System.OutOfMemoryException' was thrown.
at Microsoft.VisualStudio.Web.BrowserLink.Runtime.SocketReader..ctor(ISocketAdapter socket) 
at Microsoft.VisualStudio.Web.BrowserLink.Runtime.HttpSocketAdapter.ResponseReader..ctor(ISocketAdapter socket)
at Microsoft.VisualStudio.Web.BrowserLink.Runtime.HttpSocketAdapter.GetResponseReader() 
at Microsoft.VisualStudio.Web.BrowserLink.Runtime.HttpSocketAdapter.SetResponseHandler(ResponseHandler handler)
at Microsoft.VisualStudio.Web.BrowserLink.Runtime.ScriptInjectionFilterStream..ctor(IHttpSocketAdapter visualStudioSocket, IScriptInjectionFilterContext context)
at Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.<ExecuteWithFilter>d__5.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass29_0.<<Start>b__0>d.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__10.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__10.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.<InvokeProcessRequestAsyncImpl>d__9.MoveNext()
```

I'm on following bits:

```
.NET Framework CLR version 4.0.30319.42000   
DNX x86 version 1.0.0-beta6-12256
Microsoft.AspNet.Loader.IIS version 1.0.0-beta6-12090
IIS version 10.0.10117.0 (fbl_srv2_iis_dev(sujitn).150512-1839)
Windows 10.0.10240.0
```

**Comment by Eilon** [comment]
@jodavis is this the issue you recently fixed?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (241/200 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:47607 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkII-0001Sh-52
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:18 -0600
Date: Sun, 31 Dec 2017 12:32:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752377;
	bh=RmzoLChKhl/kJ+orodmu+GOGjGjJFT6NcoHGoUqpGMg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TwRe5B7fImuE1fXJnimc+HWFNcHkU/tVbydMqygHaRwuzuul3nvshesF2BmTll22U
	 Rro7c4dN7Xq3BpyUsrr4kBk/6ZfFW0x0Yh6ZzK7sstEEtn0eKlxfB2eOWkT37gq9J4
	 eEXJqF+og83WRNrBpkR9pY0Q0TUZHBAIBsUxay2s=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (243/200 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:56704)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkIJ-0001Si-Tu
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:20 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lzFYisTuu8mBq9Pau0lod5L4ilk=; b=it9hbVxv+41yAGMA
	qLPL5z9y8Sx2ZKDvJS/m320zBWp6qHr+3LMNqRTIMqlT2aSnnjtd0NCvDe12S6DF
	xzcqyg3dV/n8RguBH+Fo/S8lpYD7zqYEti9rMYfD5BnC5Oh1JcYXfJH47YlbA42k
	cmY9UOGUqAciq7vlec7+tnc3Iks=
Received: by filter0013p1las1.sendgrid.net with SMTP id filter0013p1las1-14249-5A49497A-C
        2017-12-31 20:32:58.283764511 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0014p1iad2.sendgrid.net (SG) with ESMTP id 85KGx5p-ThaXeV-ZizsVoQ
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:58.349 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:58 +0000 (UTC)
