### ISSUE TITLE
Beta6 MissingMethodException: DependencyInjection.ServiceCollectionExtensions.TryAdd()

### ISSUE THREAD

**Issue by rkeithhill** [aspnet/Home#797]
I converted a Beta5 project to Beta6 in VS 2015 and I get this error on startup.  I have a breakpoint in the Startup method and it is not getting there.  Here is the exception info as it appears is IE:
```
System.MissingMethodException: Method not found: 'Void Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd(Microsoft.Framework.DependencyInjection.IServiceCollection, Microsoft.Framework.DependencyInjection.ServiceDescriptor)'.
   at Microsoft.Framework.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services)
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application)
   at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)
```
I think I've gotten everything migrated off of beta5.  Here's the global.json file:
```json
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta6",
        "runtime": "clr",
        "architecture": "x86"
    }
}
```
and here are the dependencies section from my project.json file:
```json
  "dependencies": {
    "Kestrel": "1.0.0-beta6-11775",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta6",
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
    "Microsoft.AspNet.Session": "1.0.0-beta6",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta6",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6",
    "Microsoft.Framework.Configuration": "1.0.0-beta6",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta6",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta6",
    "Microsoft.Framework.Logging": "1.0.0-beta6",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta6",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta6"
  },
```

**Comment by rkeithhill** [comment]
Bit more info.  This is from the Debug -> Module Window during a debug session where this error occurs:
```
Microsoft.Framework.DependencyInjection.Abstractions.dll
    C:\Users\hillr\.dnx\packages\Microsoft.Framework.DependencyInjection.Abstractions\1.0.0-beta6-11429\lib\dnx451\Microsoft.Framework.DependencyInjection.Abstractions.dll
    1.00.0.10528	5/28/2015 11:14 AM	
Microsoft.Framework.DependencyInjection.dll
    C:\Users\hillr\.dnx\packages\Microsoft.Framework.DependencyInjection\1.0.0-beta6-11429\lib\dnx451\Microsoft.Framework.DependencyInjection.dll
    1.00.0.10528	5/28/2015 11:14 AM		
```
Shouldn't the build of the DI DLLs be from after the 6/28 change that modified ServiceCollectionExtensions.TryAdd (returns void instead of bool now)?  Or maybe I'm getting a Logging assembly this is post beta6?

This VS 2015 Ent RTM with DotNetVersionManager-x64.msi and WebToolsExtensionsvS14.msi installed.

**Comment by rkeithhill** [comment]
Nevermind. I was able to fix this by one of (or both) - removing the project.lock.json file and changing the Kestrel version from 1.0.0-beta6-11775 to just 1.0.0-beta6.
