### ISSUE TITLE
Got the following error after publishing to Azure App Service

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Home#854]
Hi My project can be published and worked on IIS.
However after I published it to Azure App Service, I got the following error in the event log. The static content can be accessed without any problem.

```
</Data><Data>http://primeobjects.azurewebsites.net/search/cloudknowledge/latest/?count=10&amp;needmediaurl=false</Data><Data>/search/cloudknowledge/latest/</Data><Data>216.40.101.89</Data><Data></Data><Data>False</Data><Data></Data><Data>IIS APPPOOL\PrimeObjects</Data><Data>12</Data><Data>IIS APPPOOL\PrimeObjects</Data><Data>False</Data><Data>   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
</Data></EventData></Event><Event><System><Provider Name="ASP.NET 4.0.30319.0"/><EventID>1309</EventID><Level>2</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2015-08-19T20:24:27Z"/><EventRecordID>1213452359</EventRecordID><Channel>Application</Channel><Computer>RD000D3A313E67</Computer><Security/></System><EventData><Data>3005</Data><Data>An unhandled exception has occurred.</Data><Data>8/19/2015 8:24:27 PM</Data><Data>8/19/2015 8:24:27 PM</Data><Data>f93e2b6750554f1ca2fbea07ff3ab0a3</Data><Data>1</Data><Data>1</Data><Data>0</Data><Data>/LM/W3SVC/1199578095/ROOT-5-130844894678138322</Data><Data></Data><Data>/</Data><Data>D:\home\site\wwwroot\</Data><Data>RD000D3A313E67</Data><Data></Data><Data>14216</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\PrimeObjects</Data><Data>DirectoryNotFoundException</Data><Data>Unable to find the runtime directory 'D:\home\site\wwwroot\..\approot\runtimes\dnx-clr-win-x86.1.0.0-beta6'.
Possible causes:
1. The runtime was not packaged with the application.
2. The packaged runtime architecture is different from the application pool architecture.
   at AspNet.Loader.Bootstrapper.LoadApplication(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.ProcessHost.System.Web.Hosting.IProcessHostLite.ReportCustomLoaderError(String appId, Int32 hr, AppDomain newlyCreatedAppDomain)
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)

</Data><Data>http://primeobjects.azurewebsites.net/search/cloudknowledge/latest/?count=10&amp;needmediaurl=false</Data><Data>/search/cloudknowledge/latest/</Data><Data>216.40.101.89</Data><Data></Data><Data>False</Data><Data></Data><Data>IIS APPPOOL\PrimeObjects</Data><Data>12</Data><Data>IIS APPPOOL\PrimeObjects</Data><Data>False</Data><Data>   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
</Data></EventData></Event></Events>
```

**Comment by davidfowl** [comment]
Are any of those 2 possible reasons valid?

> Possible causes:
> 1. The runtime was not packaged with the application.
> 2. The packaged runtime architecture is different from the application pool architecture.
