### ISSUE TITLE
dnx kestrel on HelloMvc throws MissingMethodException for beta7

### ISSUE THREAD

**Issue by IRooc** [aspnet/Home#885]
When running ```dnx kestrel``` on the latest version of HelloMvc sample it just throws this message on the console without further information
```
flexpc1:HelloMvc testuser$ dnx kestrel
System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.String[]> Microsoft.AspNet.Http.Features.IHttpRequestFeature.get_Headers()'.
Trace/BPT trap: 5
```
Another empty test project with Mvc also just throws this exception without further context.

**Comment by IRooc** [comment]
When I explicitly checkout ```tags/v1.0.0-beta7``` the output changes a little:
```

System.MissingMethodException: Method not found: 'Microsoft.Framework.DependencyInjection.IServiceCollection Microsoft.Framework.DependencyInjection.OptionsServiceCollectionExtensions.Configure(Microsoft.Framework.DependencyInjection.IServiceCollection, System.Action`1<!!0>, Int32, System.String)'.
   at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at HelloMvc.Startup.ConfigureServices(IServiceCollection services)

```

**Comment by IRooc** [comment]
nevermind, removed the local clone and re-cloned and now it works fine
