### ISSUE TITLE
Include after GroupBy throws InvalidOperationException

### ISSUE THREAD

**Issue by SaphuA** [aspnet/Home#978]
From what I understand doing a Include before a GroupBy is expected not to work. However, a recommended workaround would be to move it to after the GroupBy. This doesn't seem to be working either. Is this expected as well?

This simple query:
```C#
_context.Stories
    .GroupBy(c => c.Title)
    .Select(c => c.First())
    .Include(c => c.Comments)
    .ToList();
```
Throws:

	System.InvalidOperationException was unhandled by user code
	  HResult=-2146233079
	  Message=The expression '{[c] => First()}.Comments' passed to the Include operator could not be bound.
	  Source=EntityFramework.Core
	  StackTrace:
		   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<IncludeNavigations>b__29_0(IncludeQueryAnnotation annotation)
		   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
		   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
		   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
		   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
		   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
		   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
		   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
		   at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileQuery[TResult](QueryModel queryModel)
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
		   at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__7`1.<Execute>b__7_0(Expression q, IDatabase ds)
		   at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase database, Boolean isAsync, Func`3 compiler)
		   at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDatabase database, QueryContext queryContext)
		   at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
		   at Remotion.Linq.QueryableBase`1.GetEnumerator()
		   at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
		   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
		   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
		   at Adventure.Web.Controllers.LibraryController.Index() in C:\Users\Tijs\Repos\Adventure\src\Adventure.Web\Controllers\LibraryController.cs:line 33
	  InnerException:

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by Tratcher** [comment]
This issue was moved to aspnet/EntityFramework#3418
